var COMPILED=!0,goog=goog||{};goog.global=this;goog.define=function(a,d){var k=d;COMPILED||goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(k=goog.global.CLOSURE_DEFINES[a]);goog.exportPath_(a,k)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;
goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var d=a;(d=d.substring(0,d.lastIndexOf(".")))&&!goog.getObjectByName(d);)goog.implicitNamespaces_[d]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,d,k){a=a.split(".");k=k||goog.global;a[0]in k||!k.execScript||k.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&goog.isDef(d)?k[e]=d:k=k[e]?k[e]:k[e]={}};goog.getObjectByName=function(a,d){for(var k=a.split("."),e=d||goog.global,l;l=k.shift();)if(goog.isDefAndNotNull(e[l]))e=e[l];else return null;return e};
goog.globalize=function(a,d){var k=d||goog.global,e;for(e in a)k[e]=a[e]};goog.addDependency=function(a,d,k){if(!COMPILED){var e;a=a.replace(/\\/g,"/");for(var l=goog.dependencies_,p=0;e=d[p];p++)l.nameToPath[e]=a,a in l.pathToNames||(l.pathToNames[a]={}),l.pathToNames[a][e]=!0;for(e=0;d=k[e];e++)a in l.requires||(l.requires[a]={}),l.requires[a][d]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var d=goog.getPathFromDeps_(a);if(d){goog.included_[d]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,d){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),d=a.length-1;0<=d;--d){var k=a[d].src,e=k.lastIndexOf("?"),e=
-1==e?k.length:e;if("base.js"==k.substr(e-7,7)){goog.basePath=k.substr(0,e-7);break}}},goog.importScript_=function(a){var d=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&d(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var d=goog.global.document;if("complete"==d.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}d.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(l){if(!(l in e.written)){if(!(l in e.visited)&&(e.visited[l]=!0,l in e.requires))for(var q in e.requires[l])if(!goog.isProvided_(q))if(q in e.nameToPath)a(e.nameToPath[q]);else throw Error("Undefined nameToPath for "+q);l in k||(k[l]=!0,d.push(l))}}var d=[],k={},e=goog.dependencies_,l;for(l in goog.included_)e.written[l]||a(l);for(l=0;l<d.length;l++)if(d[l])goog.importScript_(goog.basePath+d[l]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var d=typeof a;if("object"==d)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return d;var k=Object.prototype.toString.call(a);if("[object Window]"==k)return"object";if("[object Array]"==k||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==k||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==d&&"undefined"==typeof a.call)return"object";return d};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var d=goog.typeOf(a);return"array"==d||"object"==d&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var d=typeof a;return"object"==d&&null!=a||"function"==d};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(d){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var d=goog.typeOf(a);if("object"==d||"array"==d){if(a.clone)return a.clone();var d="array"==d?[]:{},k;for(k in a)d[k]=goog.cloneObject(a[k]);return d}return a};goog.bindNative_=function(a,d,k){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,d,k){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var l=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(l,e);return a.apply(d,l)}}return function(){return a.apply(d,arguments)}};goog.bind=function(a,d,k){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,d){var k=Array.prototype.slice.call(arguments,1);return function(){var d=Array.prototype.slice.call(arguments);d.unshift.apply(d,k);return a.apply(this,d)}};goog.mixin=function(a,d){for(var k in d)a[k]=d[k]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var d=goog.global.document,k=d.createElement("script");k.type="text/javascript";k.defer=!1;k.appendChild(d.createTextNode(a));d.body.appendChild(k);
d.body.removeChild(k)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,d){var k=function(a){return goog.cssNameMapping_[a]||a},e=function(a){a=a.split("-");for(var d=[],q=0;q<a.length;q++)d.push(k(a[q]));return d.join("-")},e=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?k:e:function(a){return a};return d?a+"-"+e(d):e(a)};goog.setCssNameMapping=function(a,d){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=d};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,d){var k=d||{},e;for(e in k){var l=(""+k[e]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),l)}return a};goog.getMsgWithFallback=function(a,d){return a};goog.exportSymbol=function(a,d,k){goog.exportPath_(a,d,k)};goog.exportProperty=function(a,d,k){a[d]=k};
goog.inherits=function(a,d){function k(){}k.prototype=d.prototype;a.superClass_=d.prototype;a.prototype=new k;a.prototype.constructor=a};
goog.base=function(a,d,k){var e=arguments.callee.caller;if(goog.DEBUG&&!e)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(e.superClass_)return e.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var l=Array.prototype.slice.call(arguments,2),p=!1,q=a.constructor;q;q=q.superClass_&&q.superClass_.constructor)if(q.prototype[d]===e)p=!0;else if(p)return q.prototype[d].apply(a,
l);if(a[d]===e)return a.constructor.prototype[d].apply(a,l);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};/*

 Lo-Dash 1.3.1 (Custom Build) <http://lodash.com/>
 Build: `lodash modern -o ./dist/lodash.js`
 Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>
 Based on Underscore.js 1.4.4 <http://underscorejs.org/>
 Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud Inc.
 Available under MIT license <http://lodash.com/license>
*/
(function(a){function d(a,f,b){b=(b||0)-1;for(var d=a.length;++b<d;)if(a[b]===f)return b;return-1}function k(a,b){var c=typeof b;a=a.cache;if("boolean"==c||null==b)return a[b];"number"!=c&&"string"!=c&&(c="object");var m="number"==c?b:za+b;a=a[c]||(a[c]={});return"object"==c?a[m]&&-1<d(a[m],b)?0:-1:a[m]?0:-1}function e(a){var b=this.cache,c=typeof a;if("boolean"==c||null==a)b[a]=!0;else{"number"!=c&&"string"!=c&&(c="object");var d="number"==c?a:za+a,m=b[c]||(b[c]={});"object"==c?(m[d]||(m[d]=[])).push(a)==
this.array.length&&(b[c]=!1):m[d]=!0}}function l(a){return a.charCodeAt(0)}function p(a,b){var c=a.index,d=b.index;a=a.criteria;b=b.criteria;if(a!==b){if(a>b||"undefined"==typeof a)return 1;if(a<b||"undefined"==typeof b)return-1}return c<d?-1:1}function q(a){var b=-1,c=a.length,d=t();d["false"]=d["null"]=d["true"]=d.undefined=!1;var m=t();m.array=a;m.cache=d;for(m.push=e;++b<c;)m.push(a[b]);return!1===d.object?(w(m),null):m}function C(a){return"\\"+Aa[a]}function v(){return s.pop()||[]}function t(){return u.pop()||
{array:null,cache:null,criteria:null,"false":!1,index:0,leading:!1,maxWait:0,"null":!1,number:null,object:null,push:null,string:null,trailing:!1,"true":!1,undefined:!1,value:null}}function r(a){a.length=0;s.length<ma&&s.push(a)}function w(a){var b=a.cache;b&&w(b);a.array=a.cache=a.criteria=a.object=a.number=a.string=a.value=null;u.length<ma&&u.push(a)}function b(a,b,c){b||(b=0);"undefined"==typeof c&&(c=a?a.length:0);var d=-1;c=c-b||0;for(var m=Array(0>c?0:c);++d<c;)m[d]=a[b+d];return m}function c(e){function f(a){return a&&
"object"==typeof a&&!K(a)&&E.call(a,"__wrapped__")?a:new s(a)}function s(a){this.__wrapped__=a}function u(a,g,h,n){function x(){var n=arguments,m=f?this:g;b||(a=g[c]);h.length&&(n=n.length?(n=D.call(n),d?n.concat(h):h.concat(n)):h);return this instanceof x?(m=M(a.prototype)?na(a.prototype):{},n=a.apply(m,n),M(n)?n:m):a.apply(m,n)}var b=S(a),f=!h,c=g;if(f){var d=n;h=g}else if(!b){if(!n)throw new tb;g=a}return x}function ma(a){return Wa[a]}function J(a,g,h){var n=(n=f.indexOf)===Xa?d:n;return n}function X(a){return function(g,
h,n,b){"boolean"!=typeof h&&null!=h&&(n=(b=n)&&b[h]===g?m:h,h=!1);null!=n&&(n=f.createCallback(n,b));return a(g,h,n,b)}}function Aa(a){var g,h;if(!a||F.call(a)!=T||(g=a.constructor,S(g)&&!(g instanceof g)))return!1;W(a,function(g,a){h=a});return h===m||E.call(a,h)}function ub(a){return vb[a]}function Ba(a,g,h,n,x,Y){var c=a;"boolean"!=typeof g&&null!=g&&(n=h,h=g,g=!1);if("function"==typeof h){h="undefined"==typeof n?h:f.createCallback(h,n,1);c=h(c);if("undefined"!=typeof c)return c;c=a}if(n=M(c)){var d=
F.call(c);if(!N[d])return c;var z=K(c)}if(!n||!g)return n?z?b(c):Ca({},c):c;n=Q[d];switch(d){case ca:case da:return new n(+c);case ea:case Z:return new n(c);case fa:return n(c.source,wb.exec(c))}d=!x;x||(x=v());Y||(Y=v());for(var e=x.length;e--;)if(x[e]==a)return Y[e];c=z?n(c.length):{};z&&(E.call(a,"index")&&(c.index=a.index),E.call(a,"input")&&(c.input=a.input));x.push(a);Y.push(c);(z?A:B)(a,function(a,n){c[n]=Ba(a,g,h,m,x,Y)});d&&(r(x),r(Y));return c}function oa(a){var g=[];W(a,function(a,n){S(a)&&
g.push(n)});return g.sort()}function Ya(a){for(var g=-1,h=L(a),n=h.length,b={};++g<n;){var f=h[g];b[a[f]]=f}return b}function $(a,g,h,n,b,c){var d=h===y;if("function"==typeof h&&!d){h=f.createCallback(h,n,2);var m=h(a,g);if("undefined"!=typeof m)return!!m}if(a===g)return 0!==a||1/a==1/g;var z=typeof a,e=typeof g;if(a===a&&(!a||"function"!=z&&"object"!=z)&&(!g||"function"!=e&&"object"!=e))return!1;if(null==a||null==g)return a===g;e=F.call(a);z=F.call(g);e==ga&&(e=T);z==ga&&(z=T);if(e!=z)return!1;switch(e){case ca:case da:return+a==
+g;case ea:return a!=+a?g!=+g:0==a?1/a==1/g:a==+g;case fa:case Z:return a==R(g)}z=e==pa;if(!z){if(E.call(a,"__wrapped__ ")||E.call(g,"__wrapped__"))return $(a.__wrapped__||a,g.__wrapped__||g,h,n,b,c);if(e!=T)return!1;var e=a.constructor,l=g.constructor;if(e!=l&&!(S(e)&&e instanceof e&&S(l)&&l instanceof l))return!1}l=!b;b||(b=v());c||(c=v());for(e=b.length;e--;)if(b[e]==a)return c[e]==g;var k=0,m=!0;b.push(a);c.push(g);if(z){e=a.length;k=g.length;m=k==a.length;if(!m&&!d)return m;for(;k--;)if(z=e,
l=g[k],d)for(;z--&&!(m=$(a[z],l,h,n,b,c)););else if(!(m=$(a[k],l,h,n,b,c)))break;return m}W(g,function(g,f,d){if(E.call(d,f))return k++,m=E.call(a,f)&&$(a[f],g,h,n,b,c)});m&&!d&&W(a,function(g,a,h){if(E.call(h,a))return m=-1<--k});l&&(r(b),r(c));return m}function S(a){return"function"==typeof a}function M(a){return!(!a||!I[typeof a])}function Za(a){return"number"==typeof a||F.call(a)==ea}function ha(a){return"string"==typeof a||F.call(a)==Z}function $a(a,g,h){var n=arguments,b=0,c=2;if(!M(a))return a;
if(h===y)var d=n[3],e=n[4],m=n[5];else{var l=!0,e=v(),m=v();"number"!=typeof h&&(c=n.length);3<c&&"function"==typeof n[c-2]?d=f.createCallback(n[--c-1],n[c--],2):2<c&&"function"==typeof n[c-1]&&(d=n[--c])}for(;++b<c;)(K(n[b])?A:B)(n[b],function(g,h){var n,b,x=g,c=a[h];if(g&&((b=K(g))||Da(g))){for(x=e.length;x--;)if(n=e[x]==g){c=m[x];break}if(!n){var f;d&&(x=d(c,g),f="undefined"!=typeof x)&&(c=x);f||(c=b?K(c)?c:[]:Da(c)?c:{});e.push(g);m.push(c);f||(c=$a(c,g,y,d,e,m))}}else d&&(x=d(c,g),"undefined"==
typeof x&&(x=g)),"undefined"!=typeof x&&(c=x);a[h]=c});l&&(r(e),r(m));return a}function Ea(a){for(var g=-1,h=L(a),n=h.length,b=G(n);++g<n;)b[g]=a[h[g]];return b}function ab(a,g,h){var n=-1,b=J(),c=a?a.length:0,f=!1;h=(0>h?O(0,c+h):h)||0;c&&"number"==typeof c?f=-1<(ha(a)?a.indexOf(g,h):b(a,g,h)):B(a,function(a){if(++n>=h)return!(f=a===g)});return f}function bb(a,g,h){var n=!0;g=f.createCallback(g,h);h=-1;var b=a?a.length:0;if("number"==typeof b)for(;++h<b&&(n=!!g(a[h],h,a)););else B(a,function(a,h,
b){return n=!!g(a,h,b)});return n}function qa(a,g,h){var n=[];g=f.createCallback(g,h);h=-1;var b=a?a.length:0;if("number"==typeof b)for(;++h<b;){var c=a[h];g(c,h,a)&&n.push(c)}else B(a,function(a,h,b){g(a,h,b)&&n.push(a)});return n}function Fa(a,g,h){g=f.createCallback(g,h);h=-1;var n=a?a.length:0;if("number"==typeof n)for(;++h<n;){var b=a[h];if(g(b,h,a))return b}else{var c;B(a,function(a,h,b){if(g(a,h,b))return c=a,!1});return c}}function A(a,g,h){var b=-1,c=a?a.length:0;g=g&&"undefined"==typeof h?
g:f.createCallback(g,h);if("number"==typeof c)for(;++b<c&&!1!==g(a[b],b,a););else B(a,g);return a}function Ga(a,g,h){var b=-1,c=a?a.length:0;g=f.createCallback(g,h);if("number"==typeof c)for(var d=G(c);++b<c;)d[b]=g(a[b],b,a);else d=[],B(a,function(a,h,c){d[++b]=g(a,h,c)});return d}function cb(a,g,h){var b=-Infinity,c=b;if(!g&&K(a)){h=-1;for(var d=a.length;++h<d;){var e=a[h];e>c&&(c=e)}}else g=!g&&ha(a)?l:f.createCallback(g,h),A(a,function(a,h,f){h=g(a,h,f);h>b&&(b=h,c=a)});return c}function Ha(a,
g){var h=-1,b=a?a.length:0;if("number"==typeof b)for(var c=G(b);++h<b;)c[h]=a[h][g];return c||Ga(a,g)}function Ia(a,g,h,b){if(!a)return h;var c=3>arguments.length;g=f.createCallback(g,b,4);var d=-1,e=a.length;if("number"==typeof e)for(c&&(h=a[++d]);++d<e;)h=g(h,a[d],d,a);else B(a,function(a,b,n){h=c?(c=!1,a):g(h,a,b,n)});return h}function db(a,g,h,b){var c=a?a.length:0,d=3>arguments.length;if("number"!=typeof c)var e=L(a),c=e.length;g=f.createCallback(g,b,4);A(a,function(b,n,f){n=e?e[--c]:--c;h=d?
(d=!1,a[n]):g(h,a[n],n,f)});return h}function eb(a,g,h){var b;g=f.createCallback(g,h);h=-1;var c=a?a.length:0;if("number"==typeof c)for(;++h<c&&!(b=g(a[h],h,a)););else B(a,function(a,h,c){return!(b=g(a,h,c))});return!!b}function fb(a){var g=-1,h=J(),b=a?a.length:0,c=aa.apply(H,D.call(arguments,1)),f=[],e=b>=Ja&&h===d;if(e){var m=q(c);m?(h=k,c=m):e=!1}for(;++g<b;)m=a[g],0>h(c,m)&&f.push(m);e&&w(c);return f}function Ka(a,g,h){if(a){var n=0,c=a.length;if("number"!=typeof g&&null!=g){var d=-1;for(g=f.createCallback(g,
h);++d<c&&g(a[d],d,a);)n++}else if(n=g,null==n||h)return a[0];return b(a,0,ra(O(0,n),c))}}function Xa(a,g,h){if("number"==typeof h){var b=a?a.length:0;h=0>h?O(0,b+h):h||0}else if(h)return h=gb(a,g),a[h]===g?h:-1;return a?d(a,g,h):-1}function La(a,g,h){if("number"!=typeof g&&null!=g){var n=0,c=-1,d=a?a.length:0;for(g=f.createCallback(g,h);++c<d&&g(a[c],c,a);)n++}else n=null==g||h?1:O(0,g);return b(a,n)}function gb(a,g,h,b){var c=0,d=a?a.length:c;h=h?f.createCallback(h,b,1):Ma;for(g=h(g);c<d;)b=c+d>>>
1,h(a[b])<g?c=b+1:d=b;return c}function hb(a){for(var g=-1,h=a?cb(Ha(a,"length")):0,b=G(0>h?0:h);++g<h;)b[g]=Ha(a,g);return b}function ib(a,g){for(var h=-1,b=a?a.length:0,c={};++h<b;){var f=a[h];g?c[f]=g[h]:c[f[0]]=f[1]}return c}function Na(a,g){return jb.fastBind||U&&2<arguments.length?U.call.apply(U,arguments):u(a,g,D.call(arguments,2))}function kb(a,g,h){function b(){sa(s);sa(r);l=0;s=r=null}function c(){var g=p&&(!u||1<l);b();g&&(!1!==q&&(k=new ta),e=a.apply(m,d))}function f(){b();if(p||q!==g)k=
new ta,e=a.apply(m,d)}var d,e,m,l=0,k=0,q=!1,s=null,r=null,p=!0;g=O(0,g||0);if(!0===h)var u=!0,p=!1;else M(h)&&(u=h.leading,q="maxWait"in h&&O(g,h.maxWait||0),p="trailing"in h?h.trailing:p);return function(){d=arguments;m=this;l++;sa(r);if(!1===q)u&&2>l&&(e=a.apply(m,d));else{var h=new ta;s||u||(k=h);var b=q-(h-k);0>=b?(sa(s),s=null,k=h,e=a.apply(m,d)):s||(s=ua(f,b))}g!==q&&(r=ua(c,g));return e}}function lb(a){var g=D.call(arguments,1);return ua(function(){a.apply(m,g)},1)}function Ma(a){return a}
function mb(a){A(oa(a),function(g){var h=f[g]=a[g];f.prototype[g]=function(){var a=this.__wrapped__,g=[a];va.apply(g,arguments);g=h.apply(f,g);return a&&"object"==typeof a&&a===g?this:new s(g)}})}function nb(){return this.__wrapped__}e=e?V.defaults(a.Object(),e,V.pick(a,xb)):a;var G=e.Array,ia=e.Boolean,ta=e.Date,Oa=e.Function,P=e.Math,yb=e.Number,ja=e.Object,Pa=e.RegExp,R=e.String,tb=e.TypeError,H=[],Qa=ja.prototype,zb=e._,ba=Pa("^"+R(Qa.valueOf).replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,
".+?")+"$"),Ab=P.ceil,sa=e.clearTimeout,aa=H.concat,ob=P.floor,Bb=Oa.prototype.toString,ka=ba.test(ka=ja.getPrototypeOf)&&ka,E=Qa.hasOwnProperty,va=H.push,wa=e.setImmediate,ua=e.setTimeout,F=Qa.toString,U=ba.test(U=F.bind)&&U,na=ba.test(na=ja.create)&&na,Ra=ba.test(Ra=G.isArray)&&Ra,Cb=e.isFinite,Db=e.isNaN,xa=ba.test(xa=ja.keys)&&xa,O=P.max,ra=P.min,Sa=e.parseInt,pb=P.random,D=H.slice,P=ba.test(e.attachEvent),P=U&&!/\n|true/.test(U+P),Q={};Q[pa]=G;Q[ca]=ia;Q[da]=ta;Q[qb]=Oa;Q[T]=ja;Q[ea]=yb;Q[fa]=
Pa;Q[Z]=R;s.prototype=f.prototype;var jb=f.support={};jb.fastBind=U&&!P;f.templateSettings={escape:/<%-([\s\S]+?)%>/g,evaluate:/<%([\s\S]+?)%>/g,interpolate:rb,variable:"",imports:{_:f}};var K=Ra,ia=function(a){var g,h=[];if(!a||!I[typeof a])return h;for(g in a)E.call(a,g)&&h.push(g);return h},L=xa?function(a){return M(a)?xa(a):[]}:ia,Wa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},vb=Ya(Wa),Ca=function(a,g,h){var b,c=a,d=c;if(!c)return d;var e=arguments,m=0,l="number"==typeof h?2:
e.length;if(3<l&&"function"==typeof e[l-2])var k=f.createCallback(e[--l-1],e[l--],2);else 2<l&&"function"==typeof e[l-1]&&(k=e[--l]);for(;++m<l;)if((c=e[m])&&I[typeof c])for(var q=-1,s=I[typeof c]&&L(c),r=s?s.length:0;++q<r;)b=s[q],d[b]=k?k(d[b],c[b]):c[b];return d},Ta=function(a,g,h){var b,c=a,f=c;if(!c)return f;for(var d=arguments,e=0,m="number"==typeof h?2:d.length;++e<m;)if((c=d[e])&&I[typeof c])for(var l=-1,k=I[typeof c]&&L(c),q=k?k.length:0;++l<q;)b=k[l],"undefined"==typeof f[b]&&(f[b]=c[b]);
return f},W=function(a,g,h){var b;if(!a||!I[typeof a])return a;g=g&&"undefined"==typeof h?g:f.createCallback(g,h);for(b in a)if(!1===g(a[b],b,a))break;return a},B=function(a,g,h){if(!a||!I[typeof a])return a;g=g&&"undefined"==typeof h?g:f.createCallback(g,h);for(var b=-1,c=I[typeof a]&&L(a),d=c?c.length:0;++b<d&&(h=c[b],!1!==g(a[h],h,a)););return a},Da=function(a){if(!a||F.call(a)!=T)return!1;var g=a.valueOf,h="function"==typeof g&&(h=ka(g))&&ka(h);return h?a==h||ka(a)==h:Aa(a)},ia=X(function g(a,
b,c){for(var f=-1,d=a?a.length:0,e=[];++f<d;){var m=a[f];c&&(m=c(m,f,a));K(m)?va.apply(e,b?m:g(m)):e.push(m)}return e}),Ua=X(function(a,b,c){var f=-1,e=J(),m=a?a.length:0,l=[],s=!b&&m>=Ja&&e===d,p=c||s?v():l;if(s){var u=q(p);u?(e=k,p=u):(s=!1,p=c?p:(r(p),l))}for(;++f<m;){var u=a[f],y=c?c(u,f,a):u;if(b?!f||p[p.length-1]!==y:0>e(p,y))(c||s)&&p.push(y),l.push(u)}s?(r(p.array),w(p)):c&&r(p);return l});P&&(Va&&"function"==typeof wa)&&(lb=Na(wa,e));wa=8==Sa(sb+"08")?Sa:function(a,b){return Sa(ha(a)?a.replace(Eb,
""):a,b||0)};f.after=function(a,b){return 1>a?b():function(){if(1>--a)return b.apply(this,arguments)}};f.assign=Ca;f.at=function(a){for(var b=-1,c=aa.apply(H,D.call(arguments,1)),f=c.length,d=G(f);++b<f;)d[b]=a[c[b]];return d};f.bind=Na;f.bindAll=function(a){for(var b=1<arguments.length?aa.apply(H,D.call(arguments,1)):oa(a),c=-1,f=b.length;++c<f;){var d=b[c];a[d]=Na(a[d],a)}return a};f.bindKey=function(a,b){return u(a,b,D.call(arguments,2),y)};f.compact=function(a){for(var b=-1,c=a?a.length:0,f=[];++b<
c;){var d=a[b];d&&f.push(d)}return f};f.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length;c--;)b=[a[c].apply(this,b)];return b[0]}};f.countBy=function(a,b,c){var d={};b=f.createCallback(b,c);A(a,function(a,g,c){g=R(b(a,g,c));E.call(d,g)?d[g]++:d[g]=1});return d};f.createCallback=function(a,b,c){if(null==a)return Ma;var f=typeof a;if("function"!=f){if("object"!=f)return function(b){return b[a]};var d=L(a);return function(b){for(var h=d.length,c=!1;h--&&(c=$(b[d[h]],
a[d[h]],y)););return c}}return"undefined"==typeof b||la&&!la.test(Bb.call(a))?a:1===c?function(c){return a.call(b,c)}:2===c?function(c,f){return a.call(b,c,f)}:4===c?function(c,f,d,n){return a.call(b,c,f,d,n)}:function(c,f,d){return a.call(b,c,f,d)}};f.debounce=kb;f.defaults=Ta;f.defer=lb;f.delay=function(a,b){var c=D.call(arguments,2);return ua(function(){a.apply(m,c)},b)};f.difference=fb;f.filter=qa;f.flatten=ia;f.forEach=A;f.forIn=W;f.forOwn=B;f.functions=oa;f.groupBy=function(a,b,c){var d={};
b=f.createCallback(b,c);A(a,function(a,g,c){g=R(b(a,g,c));(E.call(d,g)?d[g]:d[g]=[]).push(a)});return d};f.initial=function(a,c,d){if(!a)return[];var e=0,m=a.length;if("number"!=typeof c&&null!=c){var l=m;for(c=f.createCallback(c,d);l--&&c(a[l],l,a);)e++}else e=null==c||d?1:c||e;return b(a,0,ra(O(0,m-e),m))};f.intersection=function(a){for(var b=arguments,c=b.length,f=-1,e=v(),m=-1,l=J(),s=a?a.length:0,p=[],u=v();++f<c;){var y=b[f];e[f]=l===d&&(y?y.length:0)>=Ja&&q(f?b[f]:u)}a:for(;++m<s;){var t=e[0],
y=a[m];if(0>(t?k(t,y):l(u,y))){f=c;for((t||u).push(y);--f;)if(t=e[f],0>(t?k(t,y):l(b[f],y)))continue a;p.push(y)}}for(;c--;)(t=e[c])&&w(t);r(e);r(u);return p};f.invert=Ya;f.invoke=function(a,b){var c=D.call(arguments,2),f=-1,d="function"==typeof b,e=a?a.length:0,m=G("number"==typeof e?e:0);A(a,function(a){m[++f]=(d?b:a[b]).apply(a,c)});return m};f.keys=L;f.map=Ga;f.max=cb;f.memoize=function(a,b){function c(){var f=c.cache,d=za+(b?b.apply(this,arguments):arguments[0]);return E.call(f,d)?f[d]:f[d]=
a.apply(this,arguments)}c.cache={};return c};f.merge=$a;f.min=function(a,b,c){var d=Infinity,e=d;if(!b&&K(a)){c=-1;for(var m=a.length;++c<m;){var k=a[c];k<e&&(e=k)}}else b=!b&&ha(a)?l:f.createCallback(b,c),A(a,function(a,g,c){g=b(a,g,c);g<d&&(d=g,e=a)});return e};f.omit=function(a,b,c){var d=J(),e="function"==typeof b,m={};if(e)b=f.createCallback(b,c);else var l=aa.apply(H,D.call(arguments,1));W(a,function(a,g,c){if(e?!b(a,g,c):0>d(l,g))m[g]=a});return m};f.once=function(a){var b,c;return function(){if(b)return c;
b=!0;c=a.apply(this,arguments);a=null;return c}};f.pairs=function(a){for(var b=-1,c=L(a),f=c.length,d=G(f);++b<f;){var e=c[b];d[b]=[e,a[e]]}return d};f.partial=function(a){return u(a,D.call(arguments,1))};f.partialRight=function(a){return u(a,D.call(arguments,1),null,y)};f.pick=function(a,b,c){var d={};if("function"!=typeof b)for(var e=-1,m=aa.apply(H,D.call(arguments,1)),l=M(a)?m.length:0;++e<l;){var k=m[e];k in a&&(d[k]=a[k])}else b=f.createCallback(b,c),W(a,function(a,c,g){b(a,c,g)&&(d[c]=a)});
return d};f.pluck=Ha;f.range=function(a,b,c){a=+a||0;c=+c||1;null==b&&(b=a,a=0);var d=-1;b=O(0,Ab((b-a)/c));for(var f=G(b);++d<b;)f[d]=a,a+=c;return f};f.reject=function(a,b,c){b=f.createCallback(b,c);return qa(a,function(a,c,g){return!b(a,c,g)})};f.rest=La;f.shuffle=function(a){var b=-1,c=a?a.length:0,d=G("number"==typeof c?c:0);A(a,function(a){var c=ob(pb()*(++b+1));d[b]=d[c];d[c]=a});return d};f.sortBy=function(a,b,c){var d=-1,e=a?a.length:0,m=G("number"==typeof e?e:0);b=f.createCallback(b,c);
A(a,function(a,c,g){var f=m[++d]=t();f.criteria=b(a,c,g);f.index=d;f.value=a});e=m.length;for(m.sort(p);e--;)a=m[e],m[e]=a.value,w(a);return m};f.tap=function(a,b){b(a);return a};f.throttle=function(a,b,c){var d=!0,f=!0;!1===c?d=!1:M(c)&&(d="leading"in c?c.leading:d,f="trailing"in c?c.trailing:f);c=t();c.leading=d;c.maxWait=b;c.trailing=f;a=kb(a,b,c);w(c);return a};f.times=function(a,b,c){a=-1<(a=+a)?a:0;var d=-1,e=G(a);for(b=f.createCallback(b,c,1);++d<a;)e[d]=b(d);return e};f.toArray=function(a){return a&&
"number"==typeof a.length?b(a):Ea(a)};f.transform=function(a,b,c,d){var e=K(a);b=f.createCallback(b,d,4);null==c&&(e?c=[]:(d=(d=a&&a.constructor)&&d.prototype,c=M(d)?na(d):{}));(e?A:B)(a,function(a,g,d){return b(c,a,g,d)});return c};f.union=function(a){K(a)||(arguments[0]=a?D.call(a):H);return Ua(aa.apply(H,arguments))};f.uniq=Ua;f.unzip=hb;f.values=Ea;f.where=qa;f.without=function(a){return fb(a,D.call(arguments,1))};f.wrap=function(a,b){return function(){var c=[a];va.apply(c,arguments);return b.apply(this,
c)}};f.zip=function(a){return a?hb(arguments):[]};f.zipObject=ib;f.collect=Ga;f.drop=La;f.each=A;f.extend=Ca;f.methods=oa;f.object=ib;f.select=qa;f.tail=La;f.unique=Ua;mb(f);f.chain=f;f.prototype.chain=function(){return this};f.clone=Ba;f.cloneDeep=function(a,b,c){return Ba(a,!0,b,c)};f.contains=ab;f.escape=function(a){return null==a?"":R(a).replace(Fb,ma)};f.every=bb;f.find=Fa;f.findIndex=function(a,b,c){var d=-1,e=a?a.length:0;for(b=f.createCallback(b,c);++d<e;)if(b(a[d],d,a))return d;return-1};
f.findKey=function(a,b,c){var d;b=f.createCallback(b,c);B(a,function(a,c,g){if(b(a,c,g))return d=c,!1});return d};f.has=function(a,b){return a?E.call(a,b):!1};f.identity=Ma;f.indexOf=Xa;f.isArguments=function(a){return F.call(a)==ga};f.isArray=K;f.isBoolean=function(a){return!0===a||!1===a||F.call(a)==ca};f.isDate=function(a){return a?"object"==typeof a&&F.call(a)==da:!1};f.isElement=function(a){return a?1===a.nodeType:!1};f.isEmpty=function(a){var b=!0;if(!a)return b;var c=F.call(a),d=a.length;if(c==
pa||(c==Z||c==ga)||c==T&&"number"==typeof d&&S(a.splice))return!d;B(a,function(){return b=!1});return b};f.isEqual=$;f.isFinite=function(a){return Cb(a)&&!Db(parseFloat(a))};f.isFunction=S;f.isNaN=function(a){return Za(a)&&a!=+a};f.isNull=function(a){return null===a};f.isNumber=Za;f.isObject=M;f.isPlainObject=Da;f.isRegExp=function(a){return a?"object"==typeof a&&F.call(a)==fa:!1};f.isString=ha;f.isUndefined=function(a){return"undefined"==typeof a};f.lastIndexOf=function(a,b,c){var d=a?a.length:0;
for("number"==typeof c&&(d=(0>c?O(0,d+c):ra(c,d-1))+1);d--;)if(a[d]===b)return d;return-1};f.mixin=mb;f.noConflict=function(){e._=zb;return this};f.parseInt=wa;f.random=function(a,b){null==a&&null==b&&(b=1);a=+a||0;null==b?(b=a,a=0):b=+b||0;var c=pb();return a%1||b%1?a+ra(c*(b-a+parseFloat("1e-"+((c+"").length-1))),b):a+ob(c*(b-a+1))};f.reduce=Ia;f.reduceRight=db;f.result=function(a,b){var c=a?a[b]:m;return S(c)?a[b]():c};f.runInContext=c;f.size=function(a){var b=a?a.length:0;return"number"==typeof b?
b:L(a).length};f.some=eb;f.sortedIndex=gb;f.template=function(a,b,c){var d=f.templateSettings;a||(a="");c=Ta({},c,d);var e=Ta({},c.imports,d.imports),d=L(e),e=Ea(e),l,k=0,q=c.interpolate||ya,s="__p += '",q=Pa((c.escape||ya).source+"|"+q.source+"|"+(q===rb?Gb:ya).source+"|"+(c.evaluate||ya).source+"|$","g");a.replace(q,function(b,c,d,f,h,e){d||(d=f);s+=a.slice(k,e).replace(Hb,C);c&&(s+="' +\n__e("+c+") +\n'");h&&(l=!0,s+="';\n"+h+";\n__p += '");d&&(s+="' +\n((__t = ("+d+")) == null ? '' : __t) +\n'");
k=e+b.length;return b});var s=s+"';\n",p=q=c.variable;p||(q="obj",s="with ("+q+") {\n"+s+"\n}\n");s=(l?s.replace(Ib,""):s).replace(Jb,"$1").replace(Kb,"$1;");s="function("+q+") {\n"+(p?"":q+" || ("+q+" = {});\n")+"var __t, __p = '', __e = _.escape"+(l?", __j = Array.prototype.join;\nfunction print() { __p += __j.call(arguments, '') }\n":";\n")+s+"return __p\n}";c="\n/*\n//@ sourceURL="+(c.sourceURL||"/lodash/template/source["+Lb++ +"]")+"\n*/";try{var r=Oa(d,"return "+s+c).apply(m,e)}catch(u){throw u.source=
s,u;}if(b)return r(b);r.source=s;return r};f.unescape=function(a){return null==a?"":R(a).replace(Mb,ub)};f.uniqueId=function(a){var b=++Nb;return R(null==a?"":a)+b};f.all=bb;f.any=eb;f.detect=Fa;f.findWhere=Fa;f.foldl=Ia;f.foldr=db;f.include=ab;f.inject=Ia;B(f,function(a,b){f.prototype[b]||(f.prototype[b]=function(){var b=[this.__wrapped__];va.apply(b,arguments);return a.apply(f,b)})});f.first=Ka;f.last=function(a,c,d){if(a){var e=0,m=a.length;if("number"!=typeof c&&null!=c){var l=m;for(c=f.createCallback(c,
d);l--&&c(a[l],l,a);)e++}else if(e=c,null==e||d)return a[m-1];return b(a,O(0,m-e))}};f.take=Ka;f.head=Ka;B(f,function(a,b){f.prototype[b]||(f.prototype[b]=function(b,c){var d=a(this.__wrapped__,b,c);return null==b||c&&"function"!=typeof b?d:new s(d)})});f.VERSION="1.3.1";f.prototype.toString=function(){return R(this.__wrapped__)};f.prototype.value=nb;f.prototype.valueOf=nb;A(["join","pop","shift"],function(a){var b=H[a];f.prototype[a]=function(){return b.apply(this.__wrapped__,arguments)}});A(["push",
"reverse","sort","unshift"],function(a){var b=H[a];f.prototype[a]=function(){b.apply(this.__wrapped__,arguments);return this}});A(["concat","slice","splice"],function(a){var b=H[a];f.prototype[a]=function(){return new s(b.apply(this.__wrapped__,arguments))}});return f}var m,s=[],u=[],Nb=0,y={},za=+new Date+"",Ja=75,ma=40,Ib=/\b__p \+= '';/g,Jb=/\b(__p \+=) '' \+/g,Kb=/(__e\(.*?\)|\b__t\)) \+\n'';/g,Mb=/&(?:amp|lt|gt|quot|#39);/g,Gb=/\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g,wb=/\w*$/,rb=/<%=([\s\S]+?)%>/g,
la=(la=/\bthis\b/)&&la.test(c)&&la,sb=" \t\x0B\f\u00a0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000",Eb=RegExp("^["+sb+"]*0+(?=.$)"),ya=/($^)/,Fb=/[&<>"']/g,Hb=/['\n\r\t\u2028\u2029\\]/g,xb="Array Boolean Date Function Math Number Object RegExp String _ attachEvent clearTimeout isFinite isNaN parseInt setImmediate setTimeout".split(" "),Lb=0,ga="[object Arguments]",pa="[object Array]",ca="[object Boolean]",da="[object Date]",
qb="[object Function]",ea="[object Number]",T="[object Object]",fa="[object RegExp]",Z="[object String]",N={};N[qb]=!1;N[ga]=N[pa]=N[ca]=N[da]=N[ea]=N[T]=N[fa]=N[Z]=!0;var I={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1},Aa={"\\":"\\","'":"'","\n":"n","\r":"r","\t":"t","\u2028":"u2028","\u2029":"u2029"},X=I[typeof exports]&&exports,Va=I[typeof module]&&module&&module.exports==X&&module,J=I[typeof global]&&global;!J||J.global!==J&&J.window!==J||(a=J);var V=c();"function"==
typeof define&&"object"==typeof define.amd&&define.amd?(a._=V,define(function(){return V})):X&&!X.nodeType?Va?(Va.exports=V)._=V:X._=V:a._=V})(this);!function(){function a(a){this.s=null!==a&&void 0!==a?"string"===typeof a?a:a.toString():a;this.orig=a;null!==a&&void 0!==a?this.__defineGetter__?this.__defineGetter__("length",function(){return this.s.length}):this.length=a.length:this.length=-1}function d(b){return new a(b)}function k(a,c){var d=[],e;for(e=0;e<a.length;e++)d.push(a[e]),c&&c.call(a,a[e],e);return d}var e={},l=String.prototype,p=a.prototype={between:function(b,c){var d=this.s,e=d.indexOf(b),l=d.indexOf(c),k=e+b.length;return new a(l>
e?d.slice(k,l):"")},camelize:function(){var b=this.trim().s.replace(/(\-|_|\s)+(.)?/g,function(a,b,d){return d?d.toUpperCase():""});return new a(b)},capitalize:function(){return new a(this.s.substr(0,1).toUpperCase()+this.s.substring(1).toLowerCase())},charAt:function(a){return this.s.charAt(a)},chompLeft:function(b){var c=this.s;return 0===c.indexOf(b)?(c=c.slice(b.length),new a(c)):this},chompRight:function(b){if(this.endsWith(b)){var c=this.s,c=c.slice(0,c.length-b.length);return new a(c)}return this},
collapseWhitespace:function(){var b=this.s.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"");return new a(b)},contains:function(a){return 0<=this.s.indexOf(a)},count:function(a){for(var c=0,d=this.s.indexOf(a);0<=d;)c+=1,d=this.s.indexOf(a,d+1);return c},dasherize:function(){var b=this.trim().s.replace(/[_\s]+/g,"-").replace(/([A-Z])/g,"-$1").replace(/-+/g,"-").toLowerCase();return new a(b)},decodeHtmlEntities:function(){var b=this.s,b=b.replace(/&#(\d+);?/g,function(a,b){return String.fromCharCode(b)}).replace(/&#[xX]([A-Fa-f0-9]+);?/g,
function(a,b){return String.fromCharCode(parseInt(b,16))}).replace(/&([^;\W]+;?)/g,function(a,b){var d=b.replace(/;$/,""),d=e[b]||b.match(/;$/)&&e[d];return"number"===typeof d?String.fromCharCode(d):"string"===typeof d?d:a});return new a(b)},endsWith:function(a){var c=this.s.length-a.length;return 0<=c&&this.s.indexOf(a,c)===c},escapeHTML:function(){return new a(this.s.replace(/[&<>"']/g,function(a){return"&"+r[a]+";"}))},ensureLeft:function(b){var c=this.s;return 0===c.indexOf(b)?this:new a(b+c)},
ensureRight:function(b){var c=this.s;return this.endsWith(b)?this:new a(c+b)},humanize:function(){if(null===this.s||void 0===this.s)return new a("");var b=this.underscore().replace(/_id$/,"").replace(/_/g," ").trim().capitalize();return new a(b)},isAlpha:function(){return!/[^a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isAlphaNumeric:function(){return!/[^0-9a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isEmpty:function(){return null===this.s||void 0===this.s?!0:/^[\s\xa0]*$/.test(this.s)},isLower:function(){return this.isAlpha()&&
this.s.toLowerCase()===this.s},isNumeric:function(){return!/[^0-9]/.test(this.s)},isUpper:function(){return this.isAlpha()&&this.s.toUpperCase()===this.s},left:function(b){return 0<=b?(b=this.s.substr(0,b),new a(b)):this.right(-b)},lines:function(){return this.replaceAll("\r\n","\n").s.split("\n")},pad:function(b,c){c=c||" ";if(this.s.length>=b)return new a(this.s);b-=this.s.length;var d=Array(Math.ceil(b/2)+1).join(c),e=Array(Math.floor(b/2)+1).join(c);return new a(d+this.s+e)},padLeft:function(b,
c){c=c||" ";return this.s.length>=b?new a(this.s):new a(Array(b-this.s.length+1).join(c)+this.s)},padRight:function(b,c){c=c||" ";return this.s.length>=b?new a(this.s):new a(this.s+Array(b-this.s.length+1).join(c))},parseCSV:function(a,c,d,e){a=a||",";d=d||"\\";"undefined"==typeof c&&(c='"');var l=0,k=[],q=[],p=this.s.length,r=!1;if("undefined"!==typeof e)var t=[];for(c||(r=!0);l<p;){var w=this.s.charAt(l);switch(w){case d:if(r&&(d!==c||this.s.charAt(l+1)===c)){l+=1;k.push(this.s.charAt(l));break}if(d!==
c)break;case c:r=!r;break;case a:r&&c?k.push(w):(q.push(k.join("")),k.length=0);break;case e:r?k.push(w):t&&(q.push(k.join("")),t.push(q),q=[],k.length=0);break;default:r&&k.push(w)}l+=1}q.push(k.join(""));return t?(t.push(q),t):q},replaceAll:function(b,c){var d=this.s.split(b).join(c);return new a(d)},right:function(b){return 0<=b?(b=this.s.substr(this.s.length-b,b),new a(b)):this.left(-b)},slugify:function(){var b=(new a(this.s.replace(/[^\w\s-]/g,"").toLowerCase())).dasherize().s;"-"===b.charAt(0)&&
(b=b.substr(1));return new a(b)},startsWith:function(a){return 0===this.s.lastIndexOf(a,0)},stripPunctuation:function(){return new a(this.s.replace(/[^\w\s]|_/g,"").replace(/\s+/g," "))},stripTags:function(){var b=this.s;k(0<arguments.length?arguments:[""],function(a){b=b.replace(RegExp("</?"+a+"[^<>]*>","gi"),"")});return new a(b)},template:function(b,c,e){var l=this.s;c=c||d.TMPL_OPEN;e=e||d.TMPL_CLOSE;(l.match(RegExp(c+"(.+?)"+e,"g"))||[]).forEach(function(a){var d=a.substring(c.length,a.length-
e.length);b[d]&&(l=l.replace(a,b[d]))});return new a(l)},times:function(b){return new a(Array(b+1).join(this.s))},toBoolean:function(){if("string"===typeof this.orig){var a=this.s.toLowerCase();return"true"===a||"yes"===a||"on"===a}return!0===this.orig||1===this.orig},toFloat:function(a){var c=parseFloat(this.s);return a?parseFloat(c.toFixed(a)):c},toInt:function(){return/^\s*-?0x/i.test(this.s)?parseInt(this.s,16):parseInt(this.s,10)},trim:function(){var b;b="undefined"===typeof l.trim?this.s.replace(/(^\s*|\s*$)/g,
""):this.s.trim();return new a(b)},trimLeft:function(){var b;b=l.trimLeft?this.s.trimLeft():this.s.replace(/(^\s*)/g,"");return new a(b)},trimRight:function(){var b;b=l.trimRight?this.s.trimRight():this.s.replace(/\s+$/,"");return new a(b)},truncate:function(b,c){var d=this.s;b=~~b;c=c||"...";if(d.length<=b)return new a(d);var e=d.slice(0,b+1).replace(/.(?=\W*\w*$)/g,function(a){return a.toUpperCase()!==a.toLowerCase()?"A":" "}),e=e.slice(e.length-2).match(/\w\w/)?e.replace(/\s*\S+$/,""):(new a(e.slice(0,
e.length-1))).trimRight().s;return(e+c).length>d.length?new a(d):new a(d.slice(0,e.length)+c)},toCSV:function(b,c){var d=",",e='"',l="\\",k=!0,q=!1,p=[];"object"===typeof b?(d=b.delimiter||d,d=b.separator||d,e=b.qualifier||e,k=!!b.encloseNumbers,l=b.escape||l,q=!!b.keys):"string"===typeof b&&(d=b);"string"===typeof c&&(e=c);null===c&&(e=null);if(this.orig instanceof Array)p=this.orig;else for(var r in this.orig)this.orig.hasOwnProperty(r)&&(q?p.push(r):p.push(this.orig[r]));l+=e;q=[];for(r=0;r<p.length;++r){var t=
null!==e&&""!==e;"number"==typeof p[r]&&(t&=k);t&&q.push(e);if(null!==p[r]&&void 0!==p[r]){var w=(new a(p[r])).replaceAll(e,l).s;q.push(w)}else q.push("");t&&q.push(e);d&&q.push(d)}q.length-=1;return new a(q.join(""))},toString:function(){return this.s},underscore:function(){var b=this.trim().s.replace(/([a-z\d])([A-Z]+)/g,"$1_$2").replace(/[-\s]+/g,"_").toLowerCase();(new a(this.s.charAt(0))).isUpper()&&(b="_"+b);return new a(b)},unescapeHTML:function(){return new a(this.s.replace(/\&([^;]+);/g,
function(a,c){var d;return c in t?t[c]:(d=c.match(/^#x([\da-fA-F]+)$/))?String.fromCharCode(parseInt(d[1],16)):(d=c.match(/^#(\d+)$/))?String.fromCharCode(~~d[1]):a}))},valueOf:function(){return this.s.valueOf()}},q=[],C=function(){var a;a=[];if(Object.getOwnPropertyNames)a=Object.getOwnPropertyNames(l),a.splice(a.indexOf("valueOf"),1),a.splice(a.indexOf("toString"),1);else{var c={},d;for(d in String.prototype)c[d]=d;for(d in Object.prototype)delete c[d];for(d in c)a.push(d)}c={};for(d=0;d<a.length;++d){var e=
a[d],k=l[e];try{var q=typeof k.apply("teststring",[]);c[e]=q}catch(r){}}return c}(),v;for(v in C)(function(b){var c=l[b];"function"==typeof c&&(p[b]||(p[b]="string"===C[b]?function(){return new a(c.apply(this,arguments))}:c))})(v);p.repeat=p.times;p.include=p.contains;p.toInteger=p.toInt;p.toBool=p.toBoolean;p.decodeHTMLEntities=p.decodeHtmlEntities;d.extendPrototype=function(){for(var a in p)(function(a){var b=p[a];l.hasOwnProperty(a)||(q.push(a),l[a]=function(){String.prototype.s=this;return b.apply(this,
arguments)})})(a)};d.restorePrototype=function(){for(var a=0;a<q.length;++a)delete String.prototype[q[a]];q.length=0};d.VERSION="1.5.0";d.TMPL_OPEN="{{";d.TMPL_CLOSE="}}";d.ENTITIES=e;"undefined"!==typeof module&&"undefined"!==typeof module.exports?module.exports=d:"function"===typeof define&&define.amd?define([],function(){return d}):window.S=d;var t={lt:"<",gt:">",quot:'"',apos:"'",amp:"&"},r={},w;for(w in t)r[t[w]]=w;e={amp:"&",gt:">",lt:"<",quot:'"',apos:"'",AElig:198,Aacute:193,Acirc:194,Agrave:192,
Aring:197,Atilde:195,Auml:196,Ccedil:199,ETH:208,Eacute:201,Ecirc:202,Egrave:200,Euml:203,Iacute:205,Icirc:206,Igrave:204,Iuml:207,Ntilde:209,Oacute:211,Ocirc:212,Ograve:210,Oslash:216,Otilde:213,Ouml:214,THORN:222,Uacute:218,Ucirc:219,Ugrave:217,Uuml:220,Yacute:221,aacute:225,acirc:226,aelig:230,agrave:224,aring:229,atilde:227,auml:228,ccedil:231,eacute:233,ecirc:234,egrave:232,eth:240,euml:235,iacute:237,icirc:238,igrave:236,iuml:239,ntilde:241,oacute:243,ocirc:244,ograve:242,oslash:248,otilde:245,
ouml:246,szlig:223,thorn:254,uacute:250,ucirc:251,ugrave:249,uuml:252,yacute:253,yuml:255,copy:169,reg:174,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,ordf:170,laquo:171,not:172,shy:173,macr:175,deg:176,plusmn:177,sup1:185,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,ordm:186,raquo:187,frac14:188,frac12:189,frac34:190,iquest:191,times:215,divide:247,"OElig;":338,"oelig;":339,"Scaron;":352,"scaron;":353,"Yuml;":376,"fnof;":402,"circ;":710,
"tilde;":732,"Alpha;":913,"Beta;":914,"Gamma;":915,"Delta;":916,"Epsilon;":917,"Zeta;":918,"Eta;":919,"Theta;":920,"Iota;":921,"Kappa;":922,"Lambda;":923,"Mu;":924,"Nu;":925,"Xi;":926,"Omicron;":927,"Pi;":928,"Rho;":929,"Sigma;":931,"Tau;":932,"Upsilon;":933,"Phi;":934,"Chi;":935,"Psi;":936,"Omega;":937,"alpha;":945,"beta;":946,"gamma;":947,"delta;":948,"epsilon;":949,"zeta;":950,"eta;":951,"theta;":952,"iota;":953,"kappa;":954,"lambda;":955,"mu;":956,"nu;":957,"xi;":958,"omicron;":959,"pi;":960,
"rho;":961,"sigmaf;":962,"sigma;":963,"tau;":964,"upsilon;":965,"phi;":966,"chi;":967,"psi;":968,"omega;":969,"thetasym;":977,"upsih;":978,"piv;":982,"ensp;":8194,"emsp;":8195,"thinsp;":8201,"zwnj;":8204,"zwj;":8205,"lrm;":8206,"rlm;":8207,"ndash;":8211,"mdash;":8212,"lsquo;":8216,"rsquo;":8217,"sbquo;":8218,"ldquo;":8220,"rdquo;":8221,"bdquo;":8222,"dagger;":8224,"Dagger;":8225,"bull;":8226,"hellip;":8230,"permil;":8240,"prime;":8242,"Prime;":8243,"lsaquo;":8249,"rsaquo;":8250,"oline;":8254,"frasl;":8260,
"euro;":8364,"image;":8465,"weierp;":8472,"real;":8476,"trade;":8482,"alefsym;":8501,"larr;":8592,"uarr;":8593,"rarr;":8594,"darr;":8595,"harr;":8596,"crarr;":8629,"lArr;":8656,"uArr;":8657,"rArr;":8658,"dArr;":8659,"hArr;":8660,"forall;":8704,"part;":8706,"exist;":8707,"empty;":8709,"nabla;":8711,"isin;":8712,"notin;":8713,"ni;":8715,"prod;":8719,"sum;":8721,"minus;":8722,"lowast;":8727,"radic;":8730,"prop;":8733,"infin;":8734,"ang;":8736,"and;":8743,"or;":8744,"cap;":8745,"cup;":8746,"int;":8747,
"there4;":8756,"sim;":8764,"cong;":8773,"asymp;":8776,"ne;":8800,"equiv;":8801,"le;":8804,"ge;":8805,"sub;":8834,"sup;":8835,"nsub;":8836,"sube;":8838,"supe;":8839,"oplus;":8853,"otimes;":8855,"perp;":8869,"sdot;":8901,"lceil;":8968,"rceil;":8969,"lfloor;":8970,"rfloor;":8971,"lang;":9001,"rang;":9002,"loz;":9674,"spades;":9824,"clubs;":9827,"hearts;":9829,"diams;":9830}}.call(this);(function(){this.H={Check:{},TennisScoreKeeper:{}}}).call(this);(function(a){function d(d){return d===a||null===d}function k(a){this.isBetweenInclusive=function(d,e){return a>=d&&a<=e};this.isBetweenExclusive=function(d,e){return a>d&&a<e}}function e(a,d){var k=typeof a,C=typeof d;if(null===a&&null===d)return!0;if(k!==C)return!1;if("object"!==k&&"object"!==C)return a==d;var k=!0,v;for(v in a)if("function"!==typeof a[v]&&(k=k&&e(a[v],d[v]),!k))return!1;return!0}this.notEmpty=function(d,e){if(d===a||null===d)throw Error("Parameter '"+e+"' cannot be null or undefined");
};this.condition=function(a,d){if(!a)throw Error(d||"An error occured");};this.isEmpty=d;this.isNotEmpty=function(a){return!d(a)};this.areSame=e;this.value=function(a){return new k(a)}}).call(this.H.Check);(function(a,d){function k(d,e){a.condition("15b6d1fc81a043c081242617308b4fdc"===e,"GameTieMode must not be instantiated. Use TieMode enum.");a.notEmpty(d,"pointByDifferenceFunc");a.condition("function"===typeof d,"pointByDifferenceFunc must be a function returning tennisPoint via point difference");this.PointByDifference=function(a){return d.call(null,a)}}function e(d){a.notEmpty(d,"label");this.label=d}function l(d,e,b,c){a.condition("82ee546ae51f4a77a048186fa13e98f1"===c,"PointType must not be instantiated. Use PointTypes enum.");
a.notEmpty(e,"label");a.notEmpty(b,"shotStyle");a.condition(d===t.PointWinner||d===t.PointLoser,"Point credit goes to winner or loser. Use pointCreditTypes enum");this.label=e;this.creditTo=d}var p={Love:{code:"0"},Fifteen:{code:"15"},Thirty:{code:"30"},Fourty:{code:"40"},Advantage:{code:"Ad"}},q={advantageWin:new k(function(d){a.condition(a.value(d).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return a.value(d).isBetweenInclusive(-1,0)?p.Fourty:1===d?p.Advantage:
p.Love},"15b6d1fc81a043c081242617308b4fdc"),singlePointWin:new k(function(d){a.condition(a.value(d).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return 0===d?p.Fourty:p.Love},"15b6d1fc81a043c081242617308b4fdc")},C={tiebreak:{code:"TB",minimumGamePoints:7},superTiebreak:{code:"STB",minimumGamePoints:10},gameDifference:{code:"GD",minimumGamePoints:4}},v={NormalPassing:new e("Normal/Passing"),Smash:new e("Smash"),Lob:new e("Lob"),Drop:new e("Drop")},t={PointWinner:0,
PointLoser:1};this.Model={Player:function(d){a.notEmpty(d,"name");this.name=d},MatchDefinition:function(d,e,b){a.notEmpty(d,"playerOne");a.notEmpty(e,"playerTwo");this.players=[d,e];this.gamesPerSet=6;this.setsCount=3;this.gameTieMode=q.advantageWin;this.lastSetTieMode=C.tiebreak;this.startingPlayer=b?e:d},TieMode:q,LastSetTieMode:C,Point:function(d,e,b){a.notEmpty(d,"forPlayer");a.notEmpty(e,"creditedTo");a.notEmpty(b,"type");this.player=d;this.creditedTo=e;this.timestamp=new Date;this.type=b},ShotStyles:v,
PointCreditTypes:t,PointTypes:{WinningShot:function(a){return new l(t.PointWinner,"Winning Shot",a,"82ee546ae51f4a77a048186fa13e98f1")},ForcedError:function(a){return new l(t.PointWinner,"Forced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},UnforcedError:function(a){return new l(t.PointLoser,"Unforced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},Ace:function(a){return new l(t.PointWinner,"Ace",a,"82ee546ae51f4a77a048186fa13e98f1")},DoubleFault:function(a){return new l(t.PointLoser,"Double Fault",
a,"82ee546ae51f4a77a048186fa13e98f1")}},PointType:l,TennisPoints:p}}).call(this.H.TennisScoreKeeper,this.H.Check);(function(a,d,k){function e(e){a.notEmpty(e,"player");this.Player=e;this.Game=d.TennisPoints.Love;this.Sets=this.Games=this.GamePoints=0}function l(d,e,l,k){a.notEmpty(d,"playerOneScoreProjection");a.notEmpty(e,"playerTwoScoreProjection");a.notEmpty(l,"setsPerMatch");a.notEmpty(k,"servingPlayer");var p=this,w=Math.ceil(l/2);this.PlayerOne=d;this.PlayerTwo=e;this.Winner=function(){return d.Sets===w?d:e.Sets===w?e:null};this.IsWon=function(){return null!==p.Winner()};this.ServingPlayer=function(){return k}}
var p=[d.TennisPoints.Love,d.TennisPoints.Fifteen,d.TennisPoints.Thirty,d.TennisPoints.Fourty];this.ScoreProjector=function(k){function C(b,c){b.GamePoints++;var e;e=b.Games===k.gamesPerSet&&c.Games===k.gamesPerSet;e=b.Sets===c.Sets&&b.Sets===Math.floor(k.setsCount/2)?e&&k.lastSetTieMode!==d.LastSetTieMode.gameDifference:e;e?(w=r,0!==(b.GamePoints+c.GamePoints)%2&&t(),2<=b.GamePoints-c.GamePoints&&b.GamePoints>=(b.Sets===c.Sets&&b.Sets===Math.floor(k.setsCount/2)?k.lastSetTieMode.minimumGamePoints:
7)&&(r=w===b.Player?c.Player:b.Player,v(b,c),b.Games=0,c.Games=0,b.Sets++)):3>=b.GamePoints?b.Game=p[b.GamePoints]:a.value(b.GamePoints-c.GamePoints).isBetweenInclusive(-1,1)?(b.Game=k.gameTieMode.PointByDifference(b.GamePoints-c.GamePoints),c.Game=k.gameTieMode.PointByDifference(c.GamePoints-b.GamePoints)):v(b,c)}function v(a,c){a.Game=d.TennisPoints.Love;c.Game=d.TennisPoints.Love;a.GamePoints=0;c.GamePoints=0;a.Games++;t();2<=a.Games-c.Games&&a.Games>=k.gamesPerSet&&(a.Games=0,c.Games=0,a.Sets++)}
function t(){r=r===k.players[0]?k.players[1]:k.players[0]}a.notEmpty(k,"gameDefinition");var r=k.startingPlayer,w=null;this.toTennisScore=function(b){a.notEmpty(b,"points");var c=new e(k.players[0]),d=new e(k.players[1]);r=k.startingPlayer;for(var p=0;p<b.length;p++)b[p].player===c.Player?C(c,d):C(d,c);return new l(c,d,k.setsCount,r)}}}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model);(function(a,d,k){function e(e){a.notEmpty(e,"players");a.condition(2===e.length,"The match must have exactly two players");this.pointFor=function(a,k){var l=a===e[0]?e[1]:e[0];return new d.Point(a,k.creditTo===d.PointCreditTypes.PointWinner?a:l,k)}}var l=this;this.Engine=function(d){a.notEmpty(d,"gameDefinition");var k=[],C=new e(d.players),v=[],t=new l.ScoreProjector(d),v=[d.players[0],d.players[1]];this.scorePointFor=function(a,d){var b=C.pointFor(a,d);k.push(b)};this.undoLatestPoint=function(){0!==
k.length&&k.pop()};this.players=v;this.points=k;this.tennisScore=function(){return t.toTennisScore(k)}};this.PointFactory=e}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model,this._);