var COMPILED=!0,goog=goog||{};goog.global=this;goog.define=function(a,b){var k=b;COMPILED||goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(k=goog.global.CLOSURE_DEFINES[a]);goog.exportPath_(a,k)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;
goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,k){a=a.split(".");k=k||goog.global;a[0]in k||!k.execScript||k.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&goog.isDef(b)?k[e]=b:k=k[e]?k[e]:k[e]={}};goog.getObjectByName=function(a,b){for(var k=a.split("."),e=b||goog.global,h;h=k.shift();)if(goog.isDefAndNotNull(e[h]))e=e[h];else return null;return e};
goog.globalize=function(a,b){var k=b||goog.global,e;for(e in a)k[e]=a[e]};goog.addDependency=function(a,b,k){if(!COMPILED){var e;a=a.replace(/\\/g,"/");for(var h=goog.dependencies_,p=0;e=b[p];p++)h.nameToPath[e]=a,a in h.pathToNames||(h.pathToNames[a]={}),h.pathToNames[a][e]=!0;for(e=0;b=k[e];e++)a in h.requires||(h.requires[a]={}),h.requires[a][b]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var k=a[b].src,e=k.lastIndexOf("?"),e=
-1==e?k.length:e;if("base.js"==k.substr(e-7,7)){goog.basePath=k.substr(0,e-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(h){if(!(h in e.written)){if(!(h in e.visited)&&(e.visited[h]=!0,h in e.requires))for(var n in e.requires[h])if(!goog.isProvided_(n))if(n in e.nameToPath)a(e.nameToPath[n]);else throw Error("Undefined nameToPath for "+n);h in k||(k[h]=!0,b.push(h))}}var b=[],k={},e=goog.dependencies_,h;for(h in goog.included_)e.written[h]||a(h);for(h=0;h<b.length;h++)if(b[h])goog.importScript_(goog.basePath+b[h]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var k=Object.prototype.toString.call(a);if("[object Window]"==k)return"object";if("[object Array]"==k||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==k||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},k;for(k in a)b[k]=goog.cloneObject(a[k]);return b}return a};goog.bindNative_=function(a,b,k){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,k){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var h=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(h,e);return a.apply(b,h)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,k){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var k=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,k);return a.apply(this,b)}};goog.mixin=function(a,b){for(var k in b)a[k]=b[k]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,k=b.createElement("script");k.type="text/javascript";k.defer=!1;k.appendChild(b.createTextNode(a));b.body.appendChild(k);
b.body.removeChild(k)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var k=function(a){return goog.cssNameMapping_[a]||a},e=function(a){a=a.split("-");for(var b=[],e=0;e<a.length;e++)b.push(k(a[e]));return b.join("-")},e=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?k:e:function(a){return a};return b?a+"-"+e(b):e(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var k=b||{},e;for(e in k){var h=(""+k[e]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),h)}return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,k){goog.exportPath_(a,b,k)};goog.exportProperty=function(a,b,k){a[b]=k};
goog.inherits=function(a,b){function k(){}k.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new k;a.prototype.constructor=a};
goog.base=function(a,b,k){var e=arguments.callee.caller;if(goog.DEBUG&&!e)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(e.superClass_)return e.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var h=Array.prototype.slice.call(arguments,2),p=!1,n=a.constructor;n;n=n.superClass_&&n.superClass_.constructor)if(n.prototype[b]===e)p=!0;else if(p)return n.prototype[b].apply(a,
h);if(a[b]===e)return a.constructor.prototype[b].apply(a,h);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};/*

 Lo-Dash 1.3.1 (Custom Build) <http://lodash.com/>
 Build: `lodash modern -o ./dist/lodash.js`
 Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>
 Based on Underscore.js 1.4.4 <http://underscorejs.org/>
 Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud Inc.
 Available under MIT license <http://lodash.com/license>
*/
(function(a){function b(a,d,c){c=(c||0)-1;for(var b=a.length;++c<b;)if(a[c]===d)return c;return-1}function k(a,d){var c=typeof d;a=a.cache;if("boolean"==c||null==d)return a[d];"number"!=c&&"string"!=c&&(c="object");var l="number"==c?d:Aa+d;a=a[c]||(a[c]={});return"object"==c?a[l]&&-1<b(a[l],d)?0:-1:a[l]?0:-1}function e(a){var d=this.cache,c=typeof a;if("boolean"==c||null==a)d[a]=!0;else{"number"!=c&&"string"!=c&&(c="object");var b="number"==c?a:Aa+a,l=d[c]||(d[c]={});"object"==c?(l[b]||(l[b]=[])).push(a)==
this.array.length&&(d[c]=!1):l[b]=!0}}function h(a){return a.charCodeAt(0)}function p(a,d){var c=a.index,b=d.index;a=a.criteria;d=d.criteria;if(a!==d){if(a>d||"undefined"==typeof a)return 1;if(a<d||"undefined"==typeof d)return-1}return c<b?-1:1}function n(a){var d=-1,c=a.length,b=r();b["false"]=b["null"]=b["true"]=b.undefined=!1;var l=r();l.array=a;l.cache=b;for(l.push=e;++d<c;)l.push(a[d]);return!1===b.object?(w(l),null):l}function C(a){return"\\"+Ba[a]}function t(){return x.pop()||[]}function r(){return z.pop()||
{array:null,cache:null,criteria:null,"false":!1,index:0,leading:!1,maxWait:0,"null":!1,number:null,object:null,push:null,string:null,trailing:!1,"true":!1,undefined:!1,value:null}}function q(a){a.length=0;x.length<na&&x.push(a)}function w(a){var d=a.cache;d&&w(d);a.array=a.cache=a.criteria=a.object=a.number=a.string=a.value=null;z.length<na&&z.push(a)}function c(a,d,c){d||(d=0);"undefined"==typeof c&&(c=a?a.length:0);var b=-1;c=c-d||0;for(var l=Array(0>c?0:c);++b<c;)l[b]=a[d+b];return l}function l(e){function d(a){return a&&
"object"==typeof a&&!K(a)&&E.call(a,"__wrapped__")?a:new x(a)}function x(a){this.__wrapped__=a}function z(a,f,g,m){function s(){var m=arguments,e=d?this:f;c||(a=f[b]);g.length&&(m=m.length?(m=D.call(m),l?m.concat(g):g.concat(m)):g);return this instanceof s?(e=N(a.prototype)?oa(a.prototype):{},m=a.apply(e,m),N(m)?m:e):a.apply(e,m)}var c=T(a),d=!g,b=f;if(d){var l=m;g=f}else if(!c){if(!m)throw new ub;f=a}return s}function na(a){return Xa[a]}function J(a,f,g){var m=(m=d.indexOf)===Ya?b:m;return m}function Y(a){return function(f,
g,m,s){"boolean"!=typeof g&&null!=g&&(m=(s=m)&&s[g]===f?v:g,g=!1);null!=m&&(m=d.createCallback(m,s));return a(f,g,m,s)}}function Ba(a){var f,g;if(!a||F.call(a)!=U||(f=a.constructor,T(f)&&!(f instanceof f)))return!1;X(a,function(f,a){g=a});return g===v||E.call(a,g)}function vb(a){return wb[a]}function Ca(a,f,g,m,s,M){var y=a;"boolean"!=typeof f&&null!=f&&(m=g,g=f,f=!1);if("function"==typeof g){g="undefined"==typeof m?g:d.createCallback(g,m,1);y=g(y);if("undefined"!=typeof y)return y;y=a}if(m=N(y)){var b=
F.call(y);if(!O[b])return y;var l=K(y)}if(!m||!f)return m?l?c(y):Da({},y):y;m=R[b];switch(b){case da:case ea:return new m(+y);case fa:case Z:return new m(y);case ga:return m(y.source,xb.exec(y))}b=!s;s||(s=t());M||(M=t());for(var e=s.length;e--;)if(s[e]==a)return M[e];y=l?m(y.length):{};l&&(E.call(a,"index")&&(y.index=a.index),E.call(a,"input")&&(y.input=a.input));s.push(a);M.push(y);(l?A:B)(a,function(a,m){y[m]=Ca(a,f,g,v,s,M)});b&&(q(s),q(M));return y}function pa(a){var f=[];X(a,function(a,m){T(a)&&
f.push(m)});return f.sort()}function Za(a){for(var f=-1,g=L(a),m=g.length,s={};++f<m;){var c=g[f];s[a[c]]=c}return s}function $(a,f,g,m,s,c){var b=g===aa;if("function"==typeof g&&!b){g=d.createCallback(g,m,2);var l=g(a,f);if("undefined"!=typeof l)return!!l}if(a===f)return 0!==a||1/a==1/f;var e=typeof a,u=typeof f;if(a===a&&(!a||"function"!=e&&"object"!=e)&&(!f||"function"!=u&&"object"!=u))return!1;if(null==a||null==f)return a===f;u=F.call(a);e=F.call(f);u==ha&&(u=U);e==ha&&(e=U);if(u!=e)return!1;
switch(u){case da:case ea:return+a==+f;case fa:return a!=+a?f!=+f:0==a?1/a==1/f:a==+f;case ga:case Z:return a==S(f)}e=u==qa;if(!e){if(E.call(a,"__wrapped__ ")||E.call(f,"__wrapped__"))return $(a.__wrapped__||a,f.__wrapped__||f,g,m,s,c);if(u!=U)return!1;var u=a.constructor,h=f.constructor;if(u!=h&&!(T(u)&&u instanceof u&&T(h)&&h instanceof h))return!1}h=!s;s||(s=t());c||(c=t());for(u=s.length;u--;)if(s[u]==a)return c[u]==f;var k=0,l=!0;s.push(a);c.push(f);if(e){u=a.length;k=f.length;l=k==a.length;
if(!l&&!b)return l;for(;k--;)if(e=u,h=f[k],b)for(;e--&&!(l=$(a[e],h,g,m,s,c)););else if(!(l=$(a[k],h,g,m,s,c)))break;return l}X(f,function(f,d,b){if(E.call(b,d))return k++,l=E.call(a,d)&&$(a[d],f,g,m,s,c)});l&&!b&&X(a,function(f,a,g){if(E.call(g,a))return l=-1<--k});h&&(q(s),q(c));return l}function T(a){return"function"==typeof a}function N(a){return!(!a||!I[typeof a])}function $a(a){return"number"==typeof a||F.call(a)==fa}function ia(a){return"string"==typeof a||F.call(a)==Z}function ab(a,f,g){var m=
arguments,s=0,c=2;if(!N(a))return a;if(g===aa)var b=m[3],l=m[4],e=m[5];else{var h=!0,l=t(),e=t();"number"!=typeof g&&(c=m.length);3<c&&"function"==typeof m[c-2]?b=d.createCallback(m[--c-1],m[c--],2):2<c&&"function"==typeof m[c-1]&&(b=m[--c])}for(;++s<c;)(K(m[s])?A:B)(m[s],function(f,g){var m,s,c=f,d=a[g];if(f&&((s=K(f))||Ea(f))){for(c=l.length;c--;)if(m=l[c]==f){d=e[c];break}if(!m){var M;b&&(c=b(d,f),M="undefined"!=typeof c)&&(d=c);M||(d=s?K(d)?d:[]:Ea(d)?d:{});l.push(f);e.push(d);M||(d=ab(d,f,aa,
b,l,e))}}else b&&(c=b(d,f),"undefined"==typeof c&&(c=f)),"undefined"!=typeof c&&(d=c);a[g]=d});h&&(q(l),q(e));return a}function Fa(a){for(var f=-1,g=L(a),m=g.length,c=G(m);++f<m;)c[f]=a[g[f]];return c}function bb(a,f,g){var m=-1,c=J(),d=a?a.length:0,b=!1;g=(0>g?P(0,d+g):g)||0;d&&"number"==typeof d?b=-1<(ia(a)?a.indexOf(f,g):c(a,f,g)):B(a,function(a){if(++m>=g)return!(b=a===f)});return b}function cb(a,f,g){var m=!0;f=d.createCallback(f,g);g=-1;var c=a?a.length:0;if("number"==typeof c)for(;++g<c&&(m=
!!f(a[g],g,a)););else B(a,function(a,g,c){return m=!!f(a,g,c)});return m}function ra(a,f,g){var m=[];f=d.createCallback(f,g);g=-1;var c=a?a.length:0;if("number"==typeof c)for(;++g<c;){var b=a[g];f(b,g,a)&&m.push(b)}else B(a,function(a,g,c){f(a,g,c)&&m.push(a)});return m}function Ga(a,f,g){f=d.createCallback(f,g);g=-1;var m=a?a.length:0;if("number"==typeof m)for(;++g<m;){var c=a[g];if(f(c,g,a))return c}else{var b;B(a,function(a,g,m){if(f(a,g,m))return b=a,!1});return b}}function A(a,f,g){var m=-1,
c=a?a.length:0;f=f&&"undefined"==typeof g?f:d.createCallback(f,g);if("number"==typeof c)for(;++m<c&&!1!==f(a[m],m,a););else B(a,f);return a}function Ha(a,f,g){var m=-1,c=a?a.length:0;f=d.createCallback(f,g);if("number"==typeof c)for(var b=G(c);++m<c;)b[m]=f(a[m],m,a);else b=[],B(a,function(a,g,c){b[++m]=f(a,g,c)});return b}function db(a,f,g){var m=-Infinity,c=m;if(!f&&K(a)){g=-1;for(var b=a.length;++g<b;){var l=a[g];l>c&&(c=l)}}else f=!f&&ia(a)?h:d.createCallback(f,g),A(a,function(a,g,d){g=f(a,g,
d);g>m&&(m=g,c=a)});return c}function Ia(a,f){var g=-1,m=a?a.length:0;if("number"==typeof m)for(var c=G(m);++g<m;)c[g]=a[g][f];return c||Ha(a,f)}function Ja(a,f,g,m){if(!a)return g;var c=3>arguments.length;f=d.createCallback(f,m,4);var b=-1,l=a.length;if("number"==typeof l)for(c&&(g=a[++b]);++b<l;)g=f(g,a[b],b,a);else B(a,function(a,m,d){g=c?(c=!1,a):f(g,a,m,d)});return g}function eb(a,f,g,m){var c=a?a.length:0,b=3>arguments.length;if("number"!=typeof c)var l=L(a),c=l.length;f=d.createCallback(f,
m,4);A(a,function(m,d,e){d=l?l[--c]:--c;g=b?(b=!1,a[d]):f(g,a[d],d,e)});return g}function fb(a,f,g){var c;f=d.createCallback(f,g);g=-1;var s=a?a.length:0;if("number"==typeof s)for(;++g<s&&!(c=f(a[g],g,a)););else B(a,function(a,g,d){return!(c=f(a,g,d))});return!!c}function gb(a){var f=-1,g=J(),c=a?a.length:0,d=ba.apply(H,D.call(arguments,1)),l=[],e=c>=Ka&&g===b;if(e){var h=n(d);h?(g=k,d=h):e=!1}for(;++f<c;)h=a[f],0>g(d,h)&&l.push(h);e&&w(d);return l}function La(a,f,g){if(a){var m=0,s=a.length;if("number"!=
typeof f&&null!=f){var b=-1;for(f=d.createCallback(f,g);++b<s&&f(a[b],b,a);)m++}else if(m=f,null==m||g)return a[0];return c(a,0,sa(P(0,m),s))}}function Ya(a,f,g){if("number"==typeof g){var c=a?a.length:0;g=0>g?P(0,c+g):g||0}else if(g)return g=hb(a,f),a[g]===f?g:-1;return a?b(a,f,g):-1}function Ma(a,f,g){if("number"!=typeof f&&null!=f){var m=0,s=-1,b=a?a.length:0;for(f=d.createCallback(f,g);++s<b&&f(a[s],s,a);)m++}else m=null==f||g?1:P(0,f);return c(a,m)}function hb(a,f,g,c){var s=0,b=a?a.length:s;
g=g?d.createCallback(g,c,1):Na;for(f=g(f);s<b;)c=s+b>>>1,g(a[c])<f?s=c+1:b=c;return s}function ib(a){for(var f=-1,g=a?db(Ia(a,"length")):0,c=G(0>g?0:g);++f<g;)c[f]=Ia(a,f);return c}function jb(a,f){for(var g=-1,c=a?a.length:0,d={};++g<c;){var b=a[g];f?d[b]=f[g]:d[b[0]]=b[1]}return d}function Oa(a,f){return kb.fastBind||V&&2<arguments.length?V.call.apply(V,arguments):z(a,f,D.call(arguments,2))}function lb(a,f,g){function c(){ta(n);ta(x);k=0;n=x=null}function d(){var f=p&&(!r||1<k);c();f&&(!1!==v&&
(q=new ua),e=a.apply(h,l))}function b(){c();if(p||v!==f)q=new ua,e=a.apply(h,l)}var l,e,h,k=0,q=0,v=!1,n=null,x=null,p=!0;f=P(0,f||0);if(!0===g)var r=!0,p=!1;else N(g)&&(r=g.leading,v="maxWait"in g&&P(f,g.maxWait||0),p="trailing"in g?g.trailing:p);return function(){l=arguments;h=this;k++;ta(x);if(!1===v)r&&2>k&&(e=a.apply(h,l));else{var g=new ua;n||r||(q=g);var c=v-(g-q);0>=c?(ta(n),n=null,q=g,e=a.apply(h,l)):n||(n=va(b,c))}f!==v&&(x=va(d,f));return e}}function mb(a){var f=D.call(arguments,1);return va(function(){a.apply(v,
f)},1)}function Na(a){return a}function nb(a){A(pa(a),function(f){var g=d[f]=a[f];d.prototype[f]=function(){var a=this.__wrapped__,f=[a];wa.apply(f,arguments);f=g.apply(d,f);return a&&"object"==typeof a&&a===f?this:new x(f)}})}function ob(){return this.__wrapped__}e=e?W.defaults(a.Object(),e,W.pick(a,yb)):a;var G=e.Array,ja=e.Boolean,ua=e.Date,Pa=e.Function,Q=e.Math,zb=e.Number,ka=e.Object,Qa=e.RegExp,S=e.String,ub=e.TypeError,H=[],Ra=ka.prototype,Ab=e._,ca=Qa("^"+S(Ra.valueOf).replace(/[.*+?^${}()|[\]\\]/g,
"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),Bb=Q.ceil,ta=e.clearTimeout,ba=H.concat,pb=Q.floor,Cb=Pa.prototype.toString,la=ca.test(la=ka.getPrototypeOf)&&la,E=Ra.hasOwnProperty,wa=H.push,xa=e.setImmediate,va=e.setTimeout,F=Ra.toString,V=ca.test(V=F.bind)&&V,oa=ca.test(oa=ka.create)&&oa,Sa=ca.test(Sa=G.isArray)&&Sa,Db=e.isFinite,Eb=e.isNaN,ya=ca.test(ya=ka.keys)&&ya,P=Q.max,sa=Q.min,Ta=e.parseInt,qb=Q.random,D=H.slice,Q=ca.test(e.attachEvent),Q=V&&!/\n|true/.test(V+Q),R={};R[qa]=G;R[da]=ja;R[ea]=
ua;R[rb]=Pa;R[U]=ka;R[fa]=zb;R[ga]=Qa;R[Z]=S;x.prototype=d.prototype;var kb=d.support={};kb.fastBind=V&&!Q;d.templateSettings={escape:/<%-([\s\S]+?)%>/g,evaluate:/<%([\s\S]+?)%>/g,interpolate:sb,variable:"",imports:{_:d}};var K=Sa,ja=function(a){var f,g=[];if(!a||!I[typeof a])return g;for(f in a)E.call(a,f)&&g.push(f);return g},L=ya?function(a){return N(a)?ya(a):[]}:ja,Xa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},wb=Za(Xa),Da=function(a,f,g){var c,b=a,l=b;if(!b)return l;var e=arguments,
h=0,k="number"==typeof g?2:e.length;if(3<k&&"function"==typeof e[k-2])var q=d.createCallback(e[--k-1],e[k--],2);else 2<k&&"function"==typeof e[k-1]&&(q=e[--k]);for(;++h<k;)if((b=e[h])&&I[typeof b])for(var v=-1,n=I[typeof b]&&L(b),x=n?n.length:0;++v<x;)c=n[v],l[c]=q?q(l[c],b[c]):b[c];return l},Ua=function(a,f,g){var c,d=a,b=d;if(!d)return b;for(var l=arguments,e=0,h="number"==typeof g?2:l.length;++e<h;)if((d=l[e])&&I[typeof d])for(var k=-1,q=I[typeof d]&&L(d),v=q?q.length:0;++k<v;)c=q[k],"undefined"==
typeof b[c]&&(b[c]=d[c]);return b},X=function(a,f,g){var c;if(!a||!I[typeof a])return a;f=f&&"undefined"==typeof g?f:d.createCallback(f,g);for(c in a)if(!1===f(a[c],c,a))break;return a},B=function(a,f,g){if(!a||!I[typeof a])return a;f=f&&"undefined"==typeof g?f:d.createCallback(f,g);for(var c=-1,b=I[typeof a]&&L(a),l=b?b.length:0;++c<l&&(g=b[c],!1!==f(a[g],g,a)););return a},Ea=function(a){if(!a||F.call(a)!=U)return!1;var f=a.valueOf,g="function"==typeof f&&(g=la(f))&&la(g);return g?a==g||la(a)==g:
Ba(a)},ja=Y(function f(a,c,d){for(var b=-1,l=a?a.length:0,e=[];++b<l;){var h=a[b];d&&(h=d(h,b,a));K(h)?wa.apply(e,c?h:f(h)):e.push(h)}return e}),Va=Y(function(a,g,c){var d=-1,l=J(),e=a?a.length:0,h=[],v=!g&&e>=Ka&&l===b,u=c||v?t():h;if(v){var x=n(u);x?(l=k,u=x):(v=!1,u=c?u:(q(u),h))}for(;++d<e;){var x=a[d],p=c?c(x,d,a):x;if(g?!d||u[u.length-1]!==p:0>l(u,p))(c||v)&&u.push(p),h.push(x)}v?(q(u.array),w(u)):c&&q(u);return h});Q&&(Wa&&"function"==typeof xa)&&(mb=Oa(xa,e));xa=8==Ta(tb+"08")?Ta:function(a,
g){return Ta(ia(a)?a.replace(Fb,""):a,g||0)};d.after=function(a,g){return 1>a?g():function(){if(1>--a)return g.apply(this,arguments)}};d.assign=Da;d.at=function(a){for(var g=-1,c=ba.apply(H,D.call(arguments,1)),d=c.length,b=G(d);++g<d;)b[g]=a[c[g]];return b};d.bind=Oa;d.bindAll=function(a){for(var g=1<arguments.length?ba.apply(H,D.call(arguments,1)):pa(a),c=-1,d=g.length;++c<d;){var b=g[c];a[b]=Oa(a[b],a)}return a};d.bindKey=function(a,g){return z(a,g,D.call(arguments,2),aa)};d.compact=function(a){for(var g=
-1,c=a?a.length:0,d=[];++g<c;){var b=a[g];b&&d.push(b)}return d};d.compose=function(){var a=arguments;return function(){for(var g=arguments,c=a.length;c--;)g=[a[c].apply(this,g)];return g[0]}};d.countBy=function(a,g,c){var b={};g=d.createCallback(g,c);A(a,function(a,f,c){f=S(g(a,f,c));E.call(b,f)?b[f]++:b[f]=1});return b};d.createCallback=function(a,c,d){if(null==a)return Na;var b=typeof a;if("function"!=b){if("object"!=b)return function(c){return c[a]};var l=L(a);return function(c){for(var g=l.length,
d=!1;g--&&(d=$(c[l[g]],a[l[g]],aa)););return d}}return"undefined"==typeof c||ma&&!ma.test(Cb.call(a))?a:1===d?function(d){return a.call(c,d)}:2===d?function(d,b){return a.call(c,d,b)}:4===d?function(d,b,m,l){return a.call(c,d,b,m,l)}:function(d,b,m){return a.call(c,d,b,m)}};d.debounce=lb;d.defaults=Ua;d.defer=mb;d.delay=function(a,c){var d=D.call(arguments,2);return va(function(){a.apply(v,d)},c)};d.difference=gb;d.filter=ra;d.flatten=ja;d.forEach=A;d.forIn=X;d.forOwn=B;d.functions=pa;d.groupBy=function(a,
c,b){var l={};c=d.createCallback(c,b);A(a,function(a,f,d){f=S(c(a,f,d));(E.call(l,f)?l[f]:l[f]=[]).push(a)});return l};d.initial=function(a,g,b){if(!a)return[];var l=0,e=a.length;if("number"!=typeof g&&null!=g){var h=e;for(g=d.createCallback(g,b);h--&&g(a[h],h,a);)l++}else l=null==g||b?1:g||l;return c(a,0,sa(P(0,e-l),e))};d.intersection=function(a){for(var c=arguments,d=c.length,l=-1,e=t(),h=-1,v=J(),x=a?a.length:0,u=[],p=t();++l<d;){var r=c[l];e[l]=v===b&&(r?r.length:0)>=Ka&&n(l?c[l]:p)}a:for(;++h<
x;){var z=e[0],r=a[h];if(0>(z?k(z,r):v(p,r))){l=d;for((z||p).push(r);--l;)if(z=e[l],0>(z?k(z,r):v(c[l],r)))continue a;u.push(r)}}for(;d--;)(z=e[d])&&w(z);q(e);q(p);return u};d.invert=Za;d.invoke=function(a,c){var d=D.call(arguments,2),b=-1,l="function"==typeof c,e=a?a.length:0,h=G("number"==typeof e?e:0);A(a,function(a){h[++b]=(l?c:a[c]).apply(a,d)});return h};d.keys=L;d.map=Ha;d.max=db;d.memoize=function(a,c){function d(){var b=d.cache,l=Aa+(c?c.apply(this,arguments):arguments[0]);return E.call(b,
l)?b[l]:b[l]=a.apply(this,arguments)}d.cache={};return d};d.merge=ab;d.min=function(a,c,b){var l=Infinity,e=l;if(!c&&K(a)){b=-1;for(var k=a.length;++b<k;){var v=a[b];v<e&&(e=v)}}else c=!c&&ia(a)?h:d.createCallback(c,b),A(a,function(a,f,d){f=c(a,f,d);f<l&&(l=f,e=a)});return e};d.omit=function(a,c,b){var l=J(),e="function"==typeof c,h={};if(e)c=d.createCallback(c,b);else var k=ba.apply(H,D.call(arguments,1));X(a,function(a,f,d){if(e?!c(a,f,d):0>l(k,f))h[f]=a});return h};d.once=function(a){var c,d;return function(){if(c)return d;
c=!0;d=a.apply(this,arguments);a=null;return d}};d.pairs=function(a){for(var c=-1,d=L(a),b=d.length,l=G(b);++c<b;){var e=d[c];l[c]=[e,a[e]]}return l};d.partial=function(a){return z(a,D.call(arguments,1))};d.partialRight=function(a){return z(a,D.call(arguments,1),null,aa)};d.pick=function(a,c,b){var l={};if("function"!=typeof c)for(var e=-1,h=ba.apply(H,D.call(arguments,1)),k=N(a)?h.length:0;++e<k;){var v=h[e];v in a&&(l[v]=a[v])}else c=d.createCallback(c,b),X(a,function(a,f,d){c(a,f,d)&&(l[f]=a)});
return l};d.pluck=Ia;d.range=function(a,c,d){a=+a||0;d=+d||1;null==c&&(c=a,a=0);var b=-1;c=P(0,Bb((c-a)/d));for(var l=G(c);++b<c;)l[b]=a,a+=d;return l};d.reject=function(a,c,b){c=d.createCallback(c,b);return ra(a,function(a,f,d){return!c(a,f,d)})};d.rest=Ma;d.shuffle=function(a){var c=-1,d=a?a.length:0,b=G("number"==typeof d?d:0);A(a,function(a){var f=pb(qb()*(++c+1));b[c]=b[f];b[f]=a});return b};d.sortBy=function(a,c,b){var l=-1,e=a?a.length:0,h=G("number"==typeof e?e:0);c=d.createCallback(c,b);
A(a,function(a,f,d){var b=h[++l]=r();b.criteria=c(a,f,d);b.index=l;b.value=a});e=h.length;for(h.sort(p);e--;)a=h[e],h[e]=a.value,w(a);return h};d.tap=function(a,c){c(a);return a};d.throttle=function(a,c,d){var b=!0,l=!0;!1===d?b=!1:N(d)&&(b="leading"in d?d.leading:b,l="trailing"in d?d.trailing:l);d=r();d.leading=b;d.maxWait=c;d.trailing=l;a=lb(a,c,d);w(d);return a};d.times=function(a,c,b){a=-1<(a=+a)?a:0;var l=-1,e=G(a);for(c=d.createCallback(c,b,1);++l<a;)e[l]=c(l);return e};d.toArray=function(a){return a&&
"number"==typeof a.length?c(a):Fa(a)};d.transform=function(a,c,b,l){var e=K(a);c=d.createCallback(c,l,4);null==b&&(e?b=[]:(l=(l=a&&a.constructor)&&l.prototype,b=N(l)?oa(l):{}));(e?A:B)(a,function(a,d,f){return c(b,a,d,f)});return b};d.union=function(a){K(a)||(arguments[0]=a?D.call(a):H);return Va(ba.apply(H,arguments))};d.uniq=Va;d.unzip=ib;d.values=Fa;d.where=ra;d.without=function(a){return gb(a,D.call(arguments,1))};d.wrap=function(a,c){return function(){var d=[a];wa.apply(d,arguments);return c.apply(this,
d)}};d.zip=function(a){return a?ib(arguments):[]};d.zipObject=jb;d.collect=Ha;d.drop=Ma;d.each=A;d.extend=Da;d.methods=pa;d.object=jb;d.select=ra;d.tail=Ma;d.unique=Va;nb(d);d.chain=d;d.prototype.chain=function(){return this};d.clone=Ca;d.cloneDeep=function(a,c,d){return Ca(a,!0,c,d)};d.contains=bb;d.escape=function(a){return null==a?"":S(a).replace(Gb,na)};d.every=cb;d.find=Ga;d.findIndex=function(a,c,b){var l=-1,e=a?a.length:0;for(c=d.createCallback(c,b);++l<e;)if(c(a[l],l,a))return l;return-1};
d.findKey=function(a,c,b){var l;c=d.createCallback(c,b);B(a,function(a,d,f){if(c(a,d,f))return l=d,!1});return l};d.has=function(a,c){return a?E.call(a,c):!1};d.identity=Na;d.indexOf=Ya;d.isArguments=function(a){return F.call(a)==ha};d.isArray=K;d.isBoolean=function(a){return!0===a||!1===a||F.call(a)==da};d.isDate=function(a){return a?"object"==typeof a&&F.call(a)==ea:!1};d.isElement=function(a){return a?1===a.nodeType:!1};d.isEmpty=function(a){var c=!0;if(!a)return c;var d=F.call(a),b=a.length;if(d==
qa||(d==Z||d==ha)||d==U&&"number"==typeof b&&T(a.splice))return!b;B(a,function(){return c=!1});return c};d.isEqual=$;d.isFinite=function(a){return Db(a)&&!Eb(parseFloat(a))};d.isFunction=T;d.isNaN=function(a){return $a(a)&&a!=+a};d.isNull=function(a){return null===a};d.isNumber=$a;d.isObject=N;d.isPlainObject=Ea;d.isRegExp=function(a){return a?"object"==typeof a&&F.call(a)==ga:!1};d.isString=ia;d.isUndefined=function(a){return"undefined"==typeof a};d.lastIndexOf=function(a,c,d){var b=a?a.length:0;
for("number"==typeof d&&(b=(0>d?P(0,b+d):sa(d,b-1))+1);b--;)if(a[b]===c)return b;return-1};d.mixin=nb;d.noConflict=function(){e._=Ab;return this};d.parseInt=xa;d.random=function(a,c){null==a&&null==c&&(c=1);a=+a||0;null==c?(c=a,a=0):c=+c||0;var d=qb();return a%1||c%1?a+sa(d*(c-a+parseFloat("1e-"+((d+"").length-1))),c):a+pb(d*(c-a+1))};d.reduce=Ja;d.reduceRight=eb;d.result=function(a,c){var d=a?a[c]:v;return T(d)?a[c]():d};d.runInContext=l;d.size=function(a){var c=a?a.length:0;return"number"==typeof c?
c:L(a).length};d.some=fb;d.sortedIndex=hb;d.template=function(a,c,b){var l=d.templateSettings;a||(a="");b=Ua({},b,l);var e=Ua({},b.imports,l.imports),l=L(e),e=Fa(e),h,k=0,q=b.interpolate||za,n="__p += '",q=Qa((b.escape||za).source+"|"+q.source+"|"+(q===sb?Hb:za).source+"|"+(b.evaluate||za).source+"|$","g");a.replace(q,function(c,d,b,l,g,e){b||(b=l);n+=a.slice(k,e).replace(Ib,C);d&&(n+="' +\n__e("+d+") +\n'");g&&(h=!0,n+="';\n"+g+";\n__p += '");b&&(n+="' +\n((__t = ("+b+")) == null ? '' : __t) +\n'");
k=e+c.length;return c});var n=n+"';\n",x=q=b.variable;x||(q="obj",n="with ("+q+") {\n"+n+"\n}\n");n=(h?n.replace(Jb,""):n).replace(Kb,"$1").replace(Lb,"$1;");n="function("+q+") {\n"+(x?"":q+" || ("+q+" = {});\n")+"var __t, __p = '', __e = _.escape"+(h?", __j = Array.prototype.join;\nfunction print() { __p += __j.call(arguments, '') }\n":";\n")+n+"return __p\n}";b="\n/*\n//@ sourceURL="+(b.sourceURL||"/lodash/template/source["+Mb++ +"]")+"\n*/";try{var p=Pa(l,"return "+n+b).apply(v,e)}catch(r){throw r.source=
n,r;}if(c)return p(c);p.source=n;return p};d.unescape=function(a){return null==a?"":S(a).replace(Nb,vb)};d.uniqueId=function(a){var c=++Ob;return S(null==a?"":a)+c};d.all=cb;d.any=fb;d.detect=Ga;d.findWhere=Ga;d.foldl=Ja;d.foldr=eb;d.include=bb;d.inject=Ja;B(d,function(a,c){d.prototype[c]||(d.prototype[c]=function(){var c=[this.__wrapped__];wa.apply(c,arguments);return a.apply(d,c)})});d.first=La;d.last=function(a,b,l){if(a){var e=0,h=a.length;if("number"!=typeof b&&null!=b){var k=h;for(b=d.createCallback(b,
l);k--&&b(a[k],k,a);)e++}else if(e=b,null==e||l)return a[h-1];return c(a,P(0,h-e))}};d.take=La;d.head=La;B(d,function(a,c){d.prototype[c]||(d.prototype[c]=function(c,d){var b=a(this.__wrapped__,c,d);return null==c||d&&"function"!=typeof c?b:new x(b)})});d.VERSION="1.3.1";d.prototype.toString=function(){return S(this.__wrapped__)};d.prototype.value=ob;d.prototype.valueOf=ob;A(["join","pop","shift"],function(a){var c=H[a];d.prototype[a]=function(){return c.apply(this.__wrapped__,arguments)}});A(["push",
"reverse","sort","unshift"],function(a){var c=H[a];d.prototype[a]=function(){c.apply(this.__wrapped__,arguments);return this}});A(["concat","slice","splice"],function(a){var c=H[a];d.prototype[a]=function(){return new x(c.apply(this.__wrapped__,arguments))}});return d}var v,x=[],z=[],Ob=0,aa={},Aa=+new Date+"",Ka=75,na=40,Jb=/\b__p \+= '';/g,Kb=/\b(__p \+=) '' \+/g,Lb=/(__e\(.*?\)|\b__t\)) \+\n'';/g,Nb=/&(?:amp|lt|gt|quot|#39);/g,Hb=/\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g,xb=/\w*$/,sb=/<%=([\s\S]+?)%>/g,
ma=(ma=/\bthis\b/)&&ma.test(l)&&ma,tb=" \t\x0B\f\u00a0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000",Fb=RegExp("^["+tb+"]*0+(?=.$)"),za=/($^)/,Gb=/[&<>"']/g,Ib=/['\n\r\t\u2028\u2029\\]/g,yb="Array Boolean Date Function Math Number Object RegExp String _ attachEvent clearTimeout isFinite isNaN parseInt setImmediate setTimeout".split(" "),Mb=0,ha="[object Arguments]",qa="[object Array]",da="[object Boolean]",ea="[object Date]",
rb="[object Function]",fa="[object Number]",U="[object Object]",ga="[object RegExp]",Z="[object String]",O={};O[rb]=!1;O[ha]=O[qa]=O[da]=O[ea]=O[fa]=O[U]=O[ga]=O[Z]=!0;var I={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1},Ba={"\\":"\\","'":"'","\n":"n","\r":"r","\t":"t","\u2028":"u2028","\u2029":"u2029"},Y=I[typeof exports]&&exports,Wa=I[typeof module]&&module&&module.exports==Y&&module,J=I[typeof global]&&global;!J||J.global!==J&&J.window!==J||(a=J);var W=l();"function"==
typeof define&&"object"==typeof define.amd&&define.amd?(a._=W,define(function(){return W})):Y&&!Y.nodeType?Wa?(Wa.exports=W)._=W:Y._=W:a._=W})(this);!function(){function a(a){this.s=null!==a&&void 0!==a?"string"===typeof a?a:a.toString():a;this.orig=a;null!==a&&void 0!==a?this.__defineGetter__?this.__defineGetter__("length",function(){return this.s.length}):this.length=a.length:this.length=-1}function b(c){return new a(c)}function k(a,b){var e=[],h;for(h=0;h<a.length;h++)e.push(a[h]),b&&b.call(a,a[h],h);return e}var e={},h=String.prototype,p=a.prototype={between:function(c,b){var e=this.s,h=e.indexOf(c),k=e.indexOf(b),q=h+c.length;return new a(k>
h?e.slice(q,k):"")},camelize:function(){var c=this.trim().s.replace(/(\-|_|\s)+(.)?/g,function(a,c,b){return b?b.toUpperCase():""});return new a(c)},capitalize:function(){return new a(this.s.substr(0,1).toUpperCase()+this.s.substring(1).toLowerCase())},charAt:function(a){return this.s.charAt(a)},chompLeft:function(c){var b=this.s;return 0===b.indexOf(c)?(b=b.slice(c.length),new a(b)):this},chompRight:function(c){if(this.endsWith(c)){var b=this.s,b=b.slice(0,b.length-c.length);return new a(b)}return this},
collapseWhitespace:function(){var c=this.s.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"");return new a(c)},contains:function(a){return 0<=this.s.indexOf(a)},count:function(a){for(var b=0,e=this.s.indexOf(a);0<=e;)b+=1,e=this.s.indexOf(a,e+1);return b},dasherize:function(){var c=this.trim().s.replace(/[_\s]+/g,"-").replace(/([A-Z])/g,"-$1").replace(/-+/g,"-").toLowerCase();return new a(c)},decodeHtmlEntities:function(){var c=this.s,c=c.replace(/&#(\d+);?/g,function(a,c){return String.fromCharCode(c)}).replace(/&#[xX]([A-Fa-f0-9]+);?/g,
function(a,c){return String.fromCharCode(parseInt(c,16))}).replace(/&([^;\W]+;?)/g,function(a,c){var b=c.replace(/;$/,""),b=e[c]||c.match(/;$/)&&e[b];return"number"===typeof b?String.fromCharCode(b):"string"===typeof b?b:a});return new a(c)},endsWith:function(a){var b=this.s.length-a.length;return 0<=b&&this.s.indexOf(a,b)===b},escapeHTML:function(){return new a(this.s.replace(/[&<>"']/g,function(a){return"&"+q[a]+";"}))},ensureLeft:function(c){var b=this.s;return 0===b.indexOf(c)?this:new a(c+b)},
ensureRight:function(c){var b=this.s;return this.endsWith(c)?this:new a(b+c)},humanize:function(){if(null===this.s||void 0===this.s)return new a("");var c=this.underscore().replace(/_id$/,"").replace(/_/g," ").trim().capitalize();return new a(c)},isAlpha:function(){return!/[^a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isAlphaNumeric:function(){return!/[^0-9a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isEmpty:function(){return null===this.s||void 0===this.s?!0:/^[\s\xa0]*$/.test(this.s)},isLower:function(){return this.isAlpha()&&
this.s.toLowerCase()===this.s},isNumeric:function(){return!/[^0-9]/.test(this.s)},isUpper:function(){return this.isAlpha()&&this.s.toUpperCase()===this.s},left:function(c){return 0<=c?(c=this.s.substr(0,c),new a(c)):this.right(-c)},lines:function(){return this.replaceAll("\r\n","\n").s.split("\n")},pad:function(c,b){b=b||" ";if(this.s.length>=c)return new a(this.s);c-=this.s.length;var e=Array(Math.ceil(c/2)+1).join(b),h=Array(Math.floor(c/2)+1).join(b);return new a(e+this.s+h)},padLeft:function(c,
b){b=b||" ";return this.s.length>=c?new a(this.s):new a(Array(c-this.s.length+1).join(b)+this.s)},padRight:function(c,b){b=b||" ";return this.s.length>=c?new a(this.s):new a(this.s+Array(c-this.s.length+1).join(b))},parseCSV:function(a,b,e,h){a=a||",";e=e||"\\";"undefined"==typeof b&&(b='"');var k=0,q=[],n=[],p=this.s.length,r=!1;if("undefined"!==typeof h)var w=[];for(b||(r=!0);k<p;){var t=this.s.charAt(k);switch(t){case e:if(r&&(e!==b||this.s.charAt(k+1)===b)){k+=1;q.push(this.s.charAt(k));break}if(e!==
b)break;case b:r=!r;break;case a:r&&b?q.push(t):(n.push(q.join("")),q.length=0);break;case h:r?q.push(t):w&&(n.push(q.join("")),w.push(n),n=[],q.length=0);break;default:r&&q.push(t)}k+=1}n.push(q.join(""));return w?(w.push(n),w):n},replaceAll:function(c,b){var e=this.s.split(c).join(b);return new a(e)},right:function(c){return 0<=c?(c=this.s.substr(this.s.length-c,c),new a(c)):this.left(-c)},slugify:function(){var c=(new a(this.s.replace(/[^\w\s-]/g,"").toLowerCase())).dasherize().s;"-"===c.charAt(0)&&
(c=c.substr(1));return new a(c)},startsWith:function(a){return 0===this.s.lastIndexOf(a,0)},stripPunctuation:function(){return new a(this.s.replace(/[^\w\s]|_/g,"").replace(/\s+/g," "))},stripTags:function(){var c=this.s;k(0<arguments.length?arguments:[""],function(a){c=c.replace(RegExp("</?"+a+"[^<>]*>","gi"),"")});return new a(c)},template:function(c,e,h){var k=this.s;e=e||b.TMPL_OPEN;h=h||b.TMPL_CLOSE;(k.match(RegExp(e+"(.+?)"+h,"g"))||[]).forEach(function(a){var b=a.substring(e.length,a.length-
h.length);c[b]&&(k=k.replace(a,c[b]))});return new a(k)},times:function(c){return new a(Array(c+1).join(this.s))},toBoolean:function(){if("string"===typeof this.orig){var a=this.s.toLowerCase();return"true"===a||"yes"===a||"on"===a}return!0===this.orig||1===this.orig},toFloat:function(a){var b=parseFloat(this.s);return a?parseFloat(b.toFixed(a)):b},toInt:function(){return/^\s*-?0x/i.test(this.s)?parseInt(this.s,16):parseInt(this.s,10)},trim:function(){var c;c="undefined"===typeof h.trim?this.s.replace(/(^\s*|\s*$)/g,
""):this.s.trim();return new a(c)},trimLeft:function(){var c;c=h.trimLeft?this.s.trimLeft():this.s.replace(/(^\s*)/g,"");return new a(c)},trimRight:function(){var c;c=h.trimRight?this.s.trimRight():this.s.replace(/\s+$/,"");return new a(c)},truncate:function(c,b){var e=this.s;c=~~c;b=b||"...";if(e.length<=c)return new a(e);var h=e.slice(0,c+1).replace(/.(?=\W*\w*$)/g,function(a){return a.toUpperCase()!==a.toLowerCase()?"A":" "}),h=h.slice(h.length-2).match(/\w\w/)?h.replace(/\s*\S+$/,""):(new a(h.slice(0,
h.length-1))).trimRight().s;return(h+b).length>e.length?new a(e):new a(e.slice(0,h.length)+b)},toCSV:function(c,b){var e=",",h='"',k="\\",q=!0,n=!1,r=[];"object"===typeof c?(e=c.delimiter||e,e=c.separator||e,h=c.qualifier||h,q=!!c.encloseNumbers,k=c.escape||k,n=!!c.keys):"string"===typeof c&&(e=c);"string"===typeof b&&(h=b);null===b&&(h=null);if(this.orig instanceof Array)r=this.orig;else for(var p in this.orig)this.orig.hasOwnProperty(p)&&(n?r.push(p):r.push(this.orig[p]));k+=h;n=[];for(p=0;p<r.length;++p){var w=
null!==h&&""!==h;"number"==typeof r[p]&&(w&=q);w&&n.push(h);if(null!==r[p]&&void 0!==r[p]){var t=(new a(r[p])).replaceAll(h,k).s;n.push(t)}else n.push("");w&&n.push(h);e&&n.push(e)}n.length-=1;return new a(n.join(""))},toString:function(){return this.s},underscore:function(){var c=this.trim().s.replace(/([a-z\d])([A-Z]+)/g,"$1_$2").replace(/[-\s]+/g,"_").toLowerCase();(new a(this.s.charAt(0))).isUpper()&&(c="_"+c);return new a(c)},unescapeHTML:function(){return new a(this.s.replace(/\&([^;]+);/g,
function(a,b){var e;return b in r?r[b]:(e=b.match(/^#x([\da-fA-F]+)$/))?String.fromCharCode(parseInt(e[1],16)):(e=b.match(/^#(\d+)$/))?String.fromCharCode(~~e[1]):a}))},valueOf:function(){return this.s.valueOf()}},n=[],C=function(){var a;a=[];if(Object.getOwnPropertyNames)a=Object.getOwnPropertyNames(h),a.splice(a.indexOf("valueOf"),1),a.splice(a.indexOf("toString"),1);else{var b={},e;for(e in String.prototype)b[e]=e;for(e in Object.prototype)delete b[e];for(e in b)a.push(e)}b={};for(e=0;e<a.length;++e){var k=
a[e],n=h[k];try{var q=typeof n.apply("teststring",[]);b[k]=q}catch(r){}}return b}(),t;for(t in C)(function(c){var b=h[c];"function"==typeof b&&(p[c]||(p[c]="string"===C[c]?function(){return new a(b.apply(this,arguments))}:b))})(t);p.repeat=p.times;p.include=p.contains;p.toInteger=p.toInt;p.toBool=p.toBoolean;p.decodeHTMLEntities=p.decodeHtmlEntities;b.extendPrototype=function(){for(var a in p)(function(a){var c=p[a];h.hasOwnProperty(a)||(n.push(a),h[a]=function(){String.prototype.s=this;return c.apply(this,
arguments)})})(a)};b.restorePrototype=function(){for(var a=0;a<n.length;++a)delete String.prototype[n[a]];n.length=0};b.VERSION="1.5.0";b.TMPL_OPEN="{{";b.TMPL_CLOSE="}}";b.ENTITIES=e;"undefined"!==typeof module&&"undefined"!==typeof module.exports?module.exports=b:"function"===typeof define&&define.amd?define([],function(){return b}):window.S=b;var r={lt:"<",gt:">",quot:'"',apos:"'",amp:"&"},q={},w;for(w in r)q[r[w]]=w;e={amp:"&",gt:">",lt:"<",quot:'"',apos:"'",AElig:198,Aacute:193,Acirc:194,Agrave:192,
Aring:197,Atilde:195,Auml:196,Ccedil:199,ETH:208,Eacute:201,Ecirc:202,Egrave:200,Euml:203,Iacute:205,Icirc:206,Igrave:204,Iuml:207,Ntilde:209,Oacute:211,Ocirc:212,Ograve:210,Oslash:216,Otilde:213,Ouml:214,THORN:222,Uacute:218,Ucirc:219,Ugrave:217,Uuml:220,Yacute:221,aacute:225,acirc:226,aelig:230,agrave:224,aring:229,atilde:227,auml:228,ccedil:231,eacute:233,ecirc:234,egrave:232,eth:240,euml:235,iacute:237,icirc:238,igrave:236,iuml:239,ntilde:241,oacute:243,ocirc:244,ograve:242,oslash:248,otilde:245,
ouml:246,szlig:223,thorn:254,uacute:250,ucirc:251,ugrave:249,uuml:252,yacute:253,yuml:255,copy:169,reg:174,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,ordf:170,laquo:171,not:172,shy:173,macr:175,deg:176,plusmn:177,sup1:185,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,ordm:186,raquo:187,frac14:188,frac12:189,frac34:190,iquest:191,times:215,divide:247,"OElig;":338,"oelig;":339,"Scaron;":352,"scaron;":353,"Yuml;":376,"fnof;":402,"circ;":710,
"tilde;":732,"Alpha;":913,"Beta;":914,"Gamma;":915,"Delta;":916,"Epsilon;":917,"Zeta;":918,"Eta;":919,"Theta;":920,"Iota;":921,"Kappa;":922,"Lambda;":923,"Mu;":924,"Nu;":925,"Xi;":926,"Omicron;":927,"Pi;":928,"Rho;":929,"Sigma;":931,"Tau;":932,"Upsilon;":933,"Phi;":934,"Chi;":935,"Psi;":936,"Omega;":937,"alpha;":945,"beta;":946,"gamma;":947,"delta;":948,"epsilon;":949,"zeta;":950,"eta;":951,"theta;":952,"iota;":953,"kappa;":954,"lambda;":955,"mu;":956,"nu;":957,"xi;":958,"omicron;":959,"pi;":960,
"rho;":961,"sigmaf;":962,"sigma;":963,"tau;":964,"upsilon;":965,"phi;":966,"chi;":967,"psi;":968,"omega;":969,"thetasym;":977,"upsih;":978,"piv;":982,"ensp;":8194,"emsp;":8195,"thinsp;":8201,"zwnj;":8204,"zwj;":8205,"lrm;":8206,"rlm;":8207,"ndash;":8211,"mdash;":8212,"lsquo;":8216,"rsquo;":8217,"sbquo;":8218,"ldquo;":8220,"rdquo;":8221,"bdquo;":8222,"dagger;":8224,"Dagger;":8225,"bull;":8226,"hellip;":8230,"permil;":8240,"prime;":8242,"Prime;":8243,"lsaquo;":8249,"rsaquo;":8250,"oline;":8254,"frasl;":8260,
"euro;":8364,"image;":8465,"weierp;":8472,"real;":8476,"trade;":8482,"alefsym;":8501,"larr;":8592,"uarr;":8593,"rarr;":8594,"darr;":8595,"harr;":8596,"crarr;":8629,"lArr;":8656,"uArr;":8657,"rArr;":8658,"dArr;":8659,"hArr;":8660,"forall;":8704,"part;":8706,"exist;":8707,"empty;":8709,"nabla;":8711,"isin;":8712,"notin;":8713,"ni;":8715,"prod;":8719,"sum;":8721,"minus;":8722,"lowast;":8727,"radic;":8730,"prop;":8733,"infin;":8734,"ang;":8736,"and;":8743,"or;":8744,"cap;":8745,"cup;":8746,"int;":8747,
"there4;":8756,"sim;":8764,"cong;":8773,"asymp;":8776,"ne;":8800,"equiv;":8801,"le;":8804,"ge;":8805,"sub;":8834,"sup;":8835,"nsub;":8836,"sube;":8838,"supe;":8839,"oplus;":8853,"otimes;":8855,"perp;":8869,"sdot;":8901,"lceil;":8968,"rceil;":8969,"lfloor;":8970,"rfloor;":8971,"lang;":9001,"rang;":9002,"loz;":9674,"spades;":9824,"clubs;":9827,"hearts;":9829,"diams;":9830}}.call(this);(function(){this.H={Check:{},TennisScoreKeeper:{}}}).call(this);(function(a){function b(b){return b===a||null===b}function k(a){this.isBetweenInclusive=function(b,e){return a>=b&&a<=e};this.isBetweenExclusive=function(b,e){return a>b&&a<e}}function e(a,b){var k=typeof a,C=typeof b;if(null===a&&null===b)return!0;if(k!==C)return!1;if("object"!==k&&"object"!==C)return a==b;var k=!0,t;for(t in a)if("function"!==typeof a[t]&&(k=k&&e(a[t],b[t]),!k))return!1;return!0}this.notEmpty=function(b,e){if(b===a||null===b)throw Error("Parameter '"+e+"' cannot be null or undefined");
};this.condition=function(a,b){if(!a)throw Error(b||"An error occured");};this.isEmpty=b;this.isNotEmpty=function(a){return!b(a)};this.areSame=e;this.value=function(a){return new k(a)}}).call(this.H.Check);(function(a,b){function k(b,e){a.condition("15b6d1fc81a043c081242617308b4fdc"===e,"GameTieMode must not be instantiated. Use TieMode enum.");a.notEmpty(b,"pointByDifferenceFunc");a.condition("function"===typeof b,"pointByDifferenceFunc must be a function returning tennisPoint via point difference");this.PointByDifference=function(a){return b.call(null,a)}}function e(b){a.notEmpty(b,"label");this.label=b}function h(b,e,c,h){a.condition("82ee546ae51f4a77a048186fa13e98f1"===h,"PointType must not be instantiated. Use PointTypes enum.");
a.notEmpty(e,"label");a.notEmpty(c,"shotStyle");a.condition(b===r.PointWinner||b===r.PointLoser,"Point credit goes to winner or loser. Use pointCreditTypes enum");this.label=e;this.creditTo=b}var p={Love:{code:"0"},Fifteen:{code:"15"},Thirty:{code:"30"},Fourty:{code:"40"},Advantage:{code:"Ad"}},n={advantageWin:new k(function(b){a.condition(a.value(b).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return a.value(b).isBetweenInclusive(-1,0)?p.Fourty:1===b?p.Advantage:
p.Love},"15b6d1fc81a043c081242617308b4fdc"),singlePointWin:new k(function(b){a.condition(a.value(b).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return 0===b?p.Fourty:p.Love},"15b6d1fc81a043c081242617308b4fdc")},C={tiebreak:{code:"TB",minimumGamePoints:7},superTiebreak:{code:"STB",minimumGamePoints:10},gameDifference:{code:"GD",minimumGamePoints:4}},t={NormalPassing:new e("Normal/Passing"),Smash:new e("Smash"),Lob:new e("Lob"),Drop:new e("Drop")},r={PointWinner:0,
PointLoser:1};this.Model={Player:function(b){a.notEmpty(b,"name");this.name=b},MatchDefinition:function(b,e,c){a.notEmpty(b,"playerOne");a.notEmpty(e,"playerTwo");this.players=[b,e];this.gamesPerSet=6;this.setsCount=3;this.gameTieMode=n.advantageWin;this.lastSetTieMode=C.tiebreak;this.startingPlayer=c?e:b},TieMode:n,LastSetTieMode:C,Point:function(b,e,c){a.notEmpty(b,"forPlayer");a.notEmpty(e,"creditedTo");a.notEmpty(c,"type");this.player=b;this.creditedTo=e;this.timestamp=new Date;this.type=c},ShotStyles:t,
PointCreditTypes:r,PointTypes:{WinningShot:function(a){return new h(r.PointWinner,"Winning Shot",a,"82ee546ae51f4a77a048186fa13e98f1")},ForcedError:function(a){return new h(r.PointWinner,"Forced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},UnforcedError:function(a){return new h(r.PointLoser,"Unforced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},Ace:function(a){return new h(r.PointWinner,"Ace",a,"82ee546ae51f4a77a048186fa13e98f1")},DoubleFault:function(a){return new h(r.PointLoser,"Double Fault",
a,"82ee546ae51f4a77a048186fa13e98f1")}},PointType:h,TennisPoints:p}}).call(this.H.TennisScoreKeeper,this.H.Check);(function(a,b,k){function e(e){a.notEmpty(e,"player");this.Player=e;this.Game=b.TennisPoints.Love;this.Sets=this.Games=this.GamePoints=0}function h(b,e,h){a.notEmpty(b,"playerOneScoreProjection");a.notEmpty(e,"playerTwoScoreProjection");a.notEmpty(h,"setsPerMatch");var k=this,q=Math.ceil(h/2);this.PlayerOne=b;this.PlayerTwo=e;this.Winner=function(){return b.Sets===q?b:e.Sets===q?e:null};this.IsWon=function(){return null!==k.Winner()}}var p=[b.TennisPoints.Love,b.TennisPoints.Fifteen,b.TennisPoints.Thirty,
b.TennisPoints.Fourty];this.ScoreProjector=function(k){function C(e,h){e.GamePoints++;var w;w=e.Games===k.gamesPerSet&&h.Games===k.gamesPerSet;w=e.Sets===h.Sets&&e.Sets===Math.floor(k.setsCount/2)?w&&k.lastSetTieMode!==b.LastSetTieMode.gameDifference:w;w?2<=e.GamePoints-h.GamePoints&&e.GamePoints>=(e.Sets===h.Sets&&e.Sets===Math.floor(k.setsCount/2)?k.lastSetTieMode.minimumGamePoints:7)&&(t(e,h),e.Games=0,h.Games=0,e.Sets++):3>=e.GamePoints?e.Game=p[e.GamePoints]:a.value(e.GamePoints-h.GamePoints).isBetweenInclusive(-1,
1)?(e.Game=k.gameTieMode.PointByDifference(e.GamePoints-h.GamePoints),h.Game=k.gameTieMode.PointByDifference(h.GamePoints-e.GamePoints)):t(e,h)}function t(a,e){a.Game=b.TennisPoints.Love;e.Game=b.TennisPoints.Love;a.GamePoints=0;e.GamePoints=0;a.Games++;2<=a.Games-e.Games&&a.Games>=k.gamesPerSet&&(a.Games=0,e.Games=0,a.Sets++)}a.notEmpty(k,"gameDefinition");this.toTennisScore=function(b){a.notEmpty(b,"points");for(var p=new e(k.players[0]),t=new e(k.players[1]),c=0;c<b.length;c++)b[c].player===p.Player?
C(p,t):C(t,p);return new h(p,t,k.setsCount)}}}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model);(function(a,b,k){function e(e){a.notEmpty(e,"players");a.condition(2===e.length,"The match must have exactly two players");this.pointFor=function(a,h){var k=a===e[0]?e[1]:e[0];return new b.Point(a,h.creditTo===b.PointCreditTypes.PointWinner?a:k,h)}}var h=this;this.Engine=function(b){a.notEmpty(b,"gameDefinition");var k=[],C=new e(b.players),t=[],r=new h.ScoreProjector(b),t=[b.players[0],b.players[1]];this.scorePointFor=function(a,b){var c=C.pointFor(a,b);k.push(c)};this.undoLatestPoint=function(){0!==
k.length&&k.pop()};this.players=t;this.points=k;this.tennisScore=function(){return r.toTennisScore(k)}};this.PointFactory=e}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model,this._);