var COMPILED=!0,goog=goog||{};goog.global=this;goog.define=function(a,d){var k=d;COMPILED||goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(k=goog.global.CLOSURE_DEFINES[a]);goog.exportPath_(a,k)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;
goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var d=a;(d=d.substring(0,d.lastIndexOf(".")))&&!goog.getObjectByName(d);)goog.implicitNamespaces_[d]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,d,k){a=a.split(".");k=k||goog.global;a[0]in k||!k.execScript||k.execScript("var "+a[0]);for(var f;a.length&&(f=a.shift());)!a.length&&goog.isDef(d)?k[f]=d:k=k[f]?k[f]:k[f]={}};goog.getObjectByName=function(a,d){for(var k=a.split("."),f=d||goog.global,m;m=k.shift();)if(goog.isDefAndNotNull(f[m]))f=f[m];else return null;return f};
goog.globalize=function(a,d){var k=d||goog.global,f;for(f in a)k[f]=a[f]};goog.addDependency=function(a,d,k){if(!COMPILED){var f;a=a.replace(/\\/g,"/");for(var m=goog.dependencies_,p=0;f=d[p];p++)m.nameToPath[f]=a,a in m.pathToNames||(m.pathToNames[a]={}),m.pathToNames[a][f]=!0;for(f=0;d=k[f];f++)a in m.requires||(m.requires[a]={}),m.requires[a][d]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var d=goog.getPathFromDeps_(a);if(d){goog.included_[d]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,d){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),d=a.length-1;0<=d;--d){var k=a[d].src,f=k.lastIndexOf("?"),f=
-1==f?k.length:f;if("base.js"==k.substr(f-7,7)){goog.basePath=k.substr(0,f-7);break}}},goog.importScript_=function(a){var d=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&d(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var d=goog.global.document;if("complete"==d.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}d.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(m){if(!(m in f.written)){if(!(m in f.visited)&&(f.visited[m]=!0,m in f.requires))for(var q in f.requires[m])if(!goog.isProvided_(q))if(q in f.nameToPath)a(f.nameToPath[q]);else throw Error("Undefined nameToPath for "+q);m in k||(k[m]=!0,d.push(m))}}var d=[],k={},f=goog.dependencies_,m;for(m in goog.included_)f.written[m]||a(m);for(m=0;m<d.length;m++)if(d[m])goog.importScript_(goog.basePath+d[m]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var d=typeof a;if("object"==d)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return d;var k=Object.prototype.toString.call(a);if("[object Window]"==k)return"object";if("[object Array]"==k||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==k||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==d&&"undefined"==typeof a.call)return"object";return d};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var d=goog.typeOf(a);return"array"==d||"object"==d&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var d=typeof a;return"object"==d&&null!=a||"function"==d};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(d){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var d=goog.typeOf(a);if("object"==d||"array"==d){if(a.clone)return a.clone();var d="array"==d?[]:{},k;for(k in a)d[k]=goog.cloneObject(a[k]);return d}return a};goog.bindNative_=function(a,d,k){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,d,k){if(!a)throw Error();if(2<arguments.length){var f=Array.prototype.slice.call(arguments,2);return function(){var m=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(m,f);return a.apply(d,m)}}return function(){return a.apply(d,arguments)}};goog.bind=function(a,d,k){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,d){var k=Array.prototype.slice.call(arguments,1);return function(){var d=Array.prototype.slice.call(arguments);d.unshift.apply(d,k);return a.apply(this,d)}};goog.mixin=function(a,d){for(var k in d)a[k]=d[k]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var d=goog.global.document,k=d.createElement("script");k.type="text/javascript";k.defer=!1;k.appendChild(d.createTextNode(a));d.body.appendChild(k);
d.body.removeChild(k)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,d){var k=function(a){return goog.cssNameMapping_[a]||a},f=function(a){a=a.split("-");for(var d=[],q=0;q<a.length;q++)d.push(k(a[q]));return d.join("-")},f=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?k:f:function(a){return a};return d?a+"-"+f(d):f(a)};goog.setCssNameMapping=function(a,d){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=d};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,d){var k=d||{},f;for(f in k){var m=(""+k[f]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+f+"\\}","gi"),m)}return a};goog.getMsgWithFallback=function(a,d){return a};goog.exportSymbol=function(a,d,k){goog.exportPath_(a,d,k)};goog.exportProperty=function(a,d,k){a[d]=k};
goog.inherits=function(a,d){function k(){}k.prototype=d.prototype;a.superClass_=d.prototype;a.prototype=new k;a.prototype.constructor=a};
goog.base=function(a,d,k){var f=arguments.callee.caller;if(goog.DEBUG&&!f)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(f.superClass_)return f.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var m=Array.prototype.slice.call(arguments,2),p=!1,q=a.constructor;q;q=q.superClass_&&q.superClass_.constructor)if(q.prototype[d]===f)p=!0;else if(p)return q.prototype[d].apply(a,
m);if(a[d]===f)return a.constructor.prototype[d].apply(a,m);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};/*

 Lo-Dash 1.3.1 (Custom Build) <http://lodash.com/>
 Build: `lodash modern -o ./dist/lodash.js`
 Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>
 Based on Underscore.js 1.4.4 <http://underscorejs.org/>
 Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud Inc.
 Available under MIT license <http://lodash.com/license>
*/
(function(a){function d(a,b,d){d=(d||0)-1;for(var c=a.length;++d<c;)if(a[d]===b)return d;return-1}function k(a,b){var c=typeof b;a=a.cache;if("boolean"==c||null==b)return a[b];"number"!=c&&"string"!=c&&(c="object");var l="number"==c?b:Aa+b;a=a[c]||(a[c]={});return"object"==c?a[l]&&-1<d(a[l],b)?0:-1:a[l]?0:-1}function f(a){var b=this.cache,c=typeof a;if("boolean"==c||null==a)b[a]=!0;else{"number"!=c&&"string"!=c&&(c="object");var d="number"==c?a:Aa+a,l=b[c]||(b[c]={});"object"==c?(l[d]||(l[d]=[])).push(a)==
this.array.length&&(b[c]=!1):l[d]=!0}}function m(a){return a.charCodeAt(0)}function p(a,b){var c=a.index,d=b.index;a=a.criteria;b=b.criteria;if(a!==b){if(a>b||"undefined"==typeof a)return 1;if(a<b||"undefined"==typeof b)return-1}return c<d?-1:1}function q(a){var b=-1,c=a.length,d=A();d["false"]=d["null"]=d["true"]=d.undefined=!1;var l=A();l.array=a;l.cache=d;for(l.push=f;++b<c;)l.push(a[b]);return!1===d.object?(t(l),null):l}function v(a){return"\\"+Ba[a]}function w(){return r.pop()||[]}function A(){return x.pop()||
{array:null,cache:null,criteria:null,"false":!1,index:0,leading:!1,maxWait:0,"null":!1,number:null,object:null,push:null,string:null,trailing:!1,"true":!1,undefined:!1,value:null}}function s(a){a.length=0;r.length<na&&r.push(a)}function t(a){var b=a.cache;b&&t(b);a.array=a.cache=a.criteria=a.object=a.number=a.string=a.value=null;x.length<na&&x.push(a)}function b(a,b,c){b||(b=0);"undefined"==typeof c&&(c=a?a.length:0);var d=-1;c=c-b||0;for(var l=Array(0>c?0:c);++d<c;)l[d]=a[b+d];return l}function c(f){function e(a){return a&&
"object"==typeof a&&!K(a)&&E.call(a,"__wrapped__")?a:new r(a)}function r(a){this.__wrapped__=a}function x(a,g,h,n){function b(){var n=arguments,l=e?this:g;Q||(a=g[c]);h.length&&(n=n.length?(n=D.call(n),d?n.concat(h):h.concat(n)):h);return this instanceof b?(l=M(a.prototype)?oa(a.prototype):{},n=a.apply(l,n),M(n)?n:l):a.apply(l,n)}var Q=T(a),e=!h,c=g;if(e){var d=n;h=g}else if(!Q){if(!n)throw new ub;g=a}return b}function na(a){return Xa[a]}function J(a,g,h){var n=(n=e.indexOf)===Ya?d:n;return n}function Y(a){return function(g,
h,n,b){"boolean"!=typeof h&&null!=h&&(n=(b=n)&&b[h]===g?l:h,h=!1);null!=n&&(n=e.createCallback(n,b));return a(g,h,n,b)}}function Ba(a){var g,h;if(!a||F.call(a)!=U||(g=a.constructor,T(g)&&!(g instanceof g)))return!1;X(a,function(g,a){h=a});return h===l||E.call(a,h)}function vb(a){return wb[a]}function Ca(a,g,h,n,z,Q){var c=a;"boolean"!=typeof g&&null!=g&&(n=h,h=g,g=!1);if("function"==typeof h){h="undefined"==typeof n?h:e.createCallback(h,n,1);c=h(c);if("undefined"!=typeof c)return c;c=a}if(n=M(c)){var d=
F.call(c);if(!N[d])return c;var y=K(c)}if(!n||!g)return n?y?b(c):Da({},c):c;n=R[d];switch(d){case da:case ea:return new n(+c);case fa:case Z:return new n(c);case ga:return n(c.source,xb.exec(c))}d=!z;z||(z=w());Q||(Q=w());for(var u=z.length;u--;)if(z[u]==a)return Q[u];c=y?n(c.length):{};y&&(E.call(a,"index")&&(c.index=a.index),E.call(a,"input")&&(c.input=a.input));z.push(a);Q.push(c);(y?B:C)(a,function(a,n){c[n]=Ca(a,g,h,l,z,Q)});d&&(s(z),s(Q));return c}function pa(a){var g=[];X(a,function(a,n){T(a)&&
g.push(n)});return g.sort()}function Za(a){for(var g=-1,h=L(a),n=h.length,b={};++g<n;){var c=h[g];b[a[c]]=c}return b}function $(a,g,h,n,b,c){var d=h===aa;if("function"==typeof h&&!d){h=e.createCallback(h,n,2);var l=h(a,g);if("undefined"!=typeof l)return!!l}if(a===g)return 0!==a||1/a==1/g;var y=typeof a,u=typeof g;if(a===a&&(!a||"function"!=y&&"object"!=y)&&(!g||"function"!=u&&"object"!=u))return!1;if(null==a||null==g)return a===g;u=F.call(a);y=F.call(g);u==ha&&(u=U);y==ha&&(y=U);if(u!=y)return!1;
switch(u){case da:case ea:return+a==+g;case fa:return a!=+a?g!=+g:0==a?1/a==1/g:a==+g;case ga:case Z:return a==S(g)}y=u==qa;if(!y){if(E.call(a,"__wrapped__ ")||E.call(g,"__wrapped__"))return $(a.__wrapped__||a,g.__wrapped__||g,h,n,b,c);if(u!=U)return!1;var u=a.constructor,f=g.constructor;if(u!=f&&!(T(u)&&u instanceof u&&T(f)&&f instanceof f))return!1}f=!b;b||(b=w());c||(c=w());for(u=b.length;u--;)if(b[u]==a)return c[u]==g;var m=0,l=!0;b.push(a);c.push(g);if(y){u=a.length;m=g.length;l=m==a.length;
if(!l&&!d)return l;for(;m--;)if(y=u,f=g[m],d)for(;y--&&!(l=$(a[y],f,h,n,b,c)););else if(!(l=$(a[m],f,h,n,b,c)))break;return l}X(g,function(g,e,d){if(E.call(d,e))return m++,l=E.call(a,e)&&$(a[e],g,h,n,b,c)});l&&!d&&X(a,function(g,a,h){if(E.call(h,a))return l=-1<--m});f&&(s(b),s(c));return l}function T(a){return"function"==typeof a}function M(a){return!(!a||!I[typeof a])}function $a(a){return"number"==typeof a||F.call(a)==fa}function ia(a){return"string"==typeof a||F.call(a)==Z}function ab(a,g,h){var n=
arguments,b=0,c=2;if(!M(a))return a;if(h===aa)var d=n[3],l=n[4],y=n[5];else{var f=!0,l=w(),y=w();"number"!=typeof h&&(c=n.length);3<c&&"function"==typeof n[c-2]?d=e.createCallback(n[--c-1],n[c--],2):2<c&&"function"==typeof n[c-1]&&(d=n[--c])}for(;++b<c;)(K(n[b])?B:C)(n[b],function(g,h){var n,b,z=g,c=a[h];if(g&&((b=K(g))||Ea(g))){for(z=l.length;z--;)if(n=l[z]==g){c=y[z];break}if(!n){var e;d&&(z=d(c,g),e="undefined"!=typeof z)&&(c=z);e||(c=b?K(c)?c:[]:Ea(c)?c:{});l.push(g);y.push(c);e||(c=ab(c,g,aa,
d,l,y))}}else d&&(z=d(c,g),"undefined"==typeof z&&(z=g)),"undefined"!=typeof z&&(c=z);a[h]=c});f&&(s(l),s(y));return a}function Fa(a){for(var g=-1,h=L(a),n=h.length,b=G(n);++g<n;)b[g]=a[h[g]];return b}function bb(a,g,h){var n=-1,b=J(),c=a?a.length:0,e=!1;h=(0>h?O(0,c+h):h)||0;c&&"number"==typeof c?e=-1<(ia(a)?a.indexOf(g,h):b(a,g,h)):C(a,function(a){if(++n>=h)return!(e=a===g)});return e}function cb(a,g,h){var n=!0;g=e.createCallback(g,h);h=-1;var b=a?a.length:0;if("number"==typeof b)for(;++h<b&&(n=
!!g(a[h],h,a)););else C(a,function(a,h,b){return n=!!g(a,h,b)});return n}function ra(a,g,h){var n=[];g=e.createCallback(g,h);h=-1;var b=a?a.length:0;if("number"==typeof b)for(;++h<b;){var c=a[h];g(c,h,a)&&n.push(c)}else C(a,function(a,h,b){g(a,h,b)&&n.push(a)});return n}function Ga(a,g,h){g=e.createCallback(g,h);h=-1;var b=a?a.length:0;if("number"==typeof b)for(;++h<b;){var c=a[h];if(g(c,h,a))return c}else{var d;C(a,function(a,h,b){if(g(a,h,b))return d=a,!1});return d}}function B(a,g,h){var b=-1,
c=a?a.length:0;g=g&&"undefined"==typeof h?g:e.createCallback(g,h);if("number"==typeof c)for(;++b<c&&!1!==g(a[b],b,a););else C(a,g);return a}function Ha(a,g,h){var b=-1,c=a?a.length:0;g=e.createCallback(g,h);if("number"==typeof c)for(var d=G(c);++b<c;)d[b]=g(a[b],b,a);else d=[],C(a,function(a,h,c){d[++b]=g(a,h,c)});return d}function db(a,g,h){var b=-Infinity,c=b;if(!g&&K(a)){h=-1;for(var d=a.length;++h<d;){var l=a[h];l>c&&(c=l)}}else g=!g&&ia(a)?m:e.createCallback(g,h),B(a,function(a,h,e){h=g(a,h,
e);h>b&&(b=h,c=a)});return c}function Ia(a,g){var h=-1,b=a?a.length:0;if("number"==typeof b)for(var c=G(b);++h<b;)c[h]=a[h][g];return c||Ha(a,g)}function Ja(a,g,h,b){if(!a)return h;var c=3>arguments.length;g=e.createCallback(g,b,4);var d=-1,l=a.length;if("number"==typeof l)for(c&&(h=a[++d]);++d<l;)h=g(h,a[d],d,a);else C(a,function(a,b,n){h=c?(c=!1,a):g(h,a,b,n)});return h}function eb(a,g,h,b){var c=a?a.length:0,d=3>arguments.length;if("number"!=typeof c)var l=L(a),c=l.length;g=e.createCallback(g,
b,4);B(a,function(b,n,e){n=l?l[--c]:--c;h=d?(d=!1,a[n]):g(h,a[n],n,e)});return h}function fb(a,g,h){var b;g=e.createCallback(g,h);h=-1;var c=a?a.length:0;if("number"==typeof c)for(;++h<c&&!(b=g(a[h],h,a)););else C(a,function(a,h,c){return!(b=g(a,h,c))});return!!b}function gb(a){var g=-1,h=J(),b=a?a.length:0,c=ba.apply(H,D.call(arguments,1)),e=[],l=b>=Ka&&h===d;if(l){var f=q(c);f?(h=k,c=f):l=!1}for(;++g<b;)f=a[g],0>h(c,f)&&e.push(f);l&&t(c);return e}function La(a,g,h){if(a){var c=0,d=a.length;if("number"!=
typeof g&&null!=g){var l=-1;for(g=e.createCallback(g,h);++l<d&&g(a[l],l,a);)c++}else if(c=g,null==c||h)return a[0];return b(a,0,sa(O(0,c),d))}}function Ya(a,g,h){if("number"==typeof h){var b=a?a.length:0;h=0>h?O(0,b+h):h||0}else if(h)return h=hb(a,g),a[h]===g?h:-1;return a?d(a,g,h):-1}function Ma(a,g,h){if("number"!=typeof g&&null!=g){var c=0,d=-1,l=a?a.length:0;for(g=e.createCallback(g,h);++d<l&&g(a[d],d,a);)c++}else c=null==g||h?1:O(0,g);return b(a,c)}function hb(a,g,h,b){var c=0,d=a?a.length:c;
h=h?e.createCallback(h,b,1):Na;for(g=h(g);c<d;)b=c+d>>>1,h(a[b])<g?c=b+1:d=b;return c}function ib(a){for(var g=-1,h=a?db(Ia(a,"length")):0,b=G(0>h?0:h);++g<h;)b[g]=Ia(a,g);return b}function jb(a,g){for(var h=-1,b=a?a.length:0,c={};++h<b;){var d=a[h];g?c[d]=g[h]:c[d[0]]=d[1]}return c}function Oa(a,g){return kb.fastBind||V&&2<arguments.length?V.call.apply(V,arguments):x(a,g,D.call(arguments,2))}function lb(a,g,h){function b(){ta(r);ta(t);m=0;r=t=null}function c(){var g=p&&(!s||1<m);b();g&&(!1!==q&&
(k=new ua),l=a.apply(f,e))}function d(){b();if(p||q!==g)k=new ua,l=a.apply(f,e)}var e,l,f,m=0,k=0,q=!1,r=null,t=null,p=!0;g=O(0,g||0);if(!0===h)var s=!0,p=!1;else M(h)&&(s=h.leading,q="maxWait"in h&&O(g,h.maxWait||0),p="trailing"in h?h.trailing:p);return function(){e=arguments;f=this;m++;ta(t);if(!1===q)s&&2>m&&(l=a.apply(f,e));else{var h=new ua;r||s||(k=h);var b=q-(h-k);0>=b?(ta(r),r=null,k=h,l=a.apply(f,e)):r||(r=va(d,b))}g!==q&&(t=va(c,g));return l}}function mb(a){var g=D.call(arguments,1);return va(function(){a.apply(l,
g)},1)}function Na(a){return a}function nb(a){B(pa(a),function(g){var h=e[g]=a[g];e.prototype[g]=function(){var a=this.__wrapped__,g=[a];wa.apply(g,arguments);g=h.apply(e,g);return a&&"object"==typeof a&&a===g?this:new r(g)}})}function ob(){return this.__wrapped__}f=f?W.defaults(a.Object(),f,W.pick(a,yb)):a;var G=f.Array,ja=f.Boolean,ua=f.Date,Pa=f.Function,P=f.Math,zb=f.Number,ka=f.Object,Qa=f.RegExp,S=f.String,ub=f.TypeError,H=[],Ra=ka.prototype,Ab=f._,ca=Qa("^"+S(Ra.valueOf).replace(/[.*+?^${}()|[\]\\]/g,
"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),Bb=P.ceil,ta=f.clearTimeout,ba=H.concat,pb=P.floor,Cb=Pa.prototype.toString,la=ca.test(la=ka.getPrototypeOf)&&la,E=Ra.hasOwnProperty,wa=H.push,xa=f.setImmediate,va=f.setTimeout,F=Ra.toString,V=ca.test(V=F.bind)&&V,oa=ca.test(oa=ka.create)&&oa,Sa=ca.test(Sa=G.isArray)&&Sa,Db=f.isFinite,Eb=f.isNaN,ya=ca.test(ya=ka.keys)&&ya,O=P.max,sa=P.min,Ta=f.parseInt,qb=P.random,D=H.slice,P=ca.test(f.attachEvent),P=V&&!/\n|true/.test(V+P),R={};R[qa]=G;R[da]=ja;R[ea]=
ua;R[rb]=Pa;R[U]=ka;R[fa]=zb;R[ga]=Qa;R[Z]=S;r.prototype=e.prototype;var kb=e.support={};kb.fastBind=V&&!P;e.templateSettings={escape:/<%-([\s\S]+?)%>/g,evaluate:/<%([\s\S]+?)%>/g,interpolate:sb,variable:"",imports:{_:e}};var K=Sa,ja=function(a){var g,h=[];if(!a||!I[typeof a])return h;for(g in a)E.call(a,g)&&h.push(g);return h},L=ya?function(a){return M(a)?ya(a):[]}:ja,Xa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},wb=Za(Xa),Da=function(a,g,h){var b,c=a,d=c;if(!c)return d;var l=arguments,
f=0,m="number"==typeof h?2:l.length;if(3<m&&"function"==typeof l[m-2])var u=e.createCallback(l[--m-1],l[m--],2);else 2<m&&"function"==typeof l[m-1]&&(u=l[--m]);for(;++f<m;)if((c=l[f])&&I[typeof c])for(var k=-1,q=I[typeof c]&&L(c),r=q?q.length:0;++k<r;)b=q[k],d[b]=u?u(d[b],c[b]):c[b];return d},Ua=function(a,g,h){var b,c=a,d=c;if(!c)return d;for(var e=arguments,l=0,f="number"==typeof h?2:e.length;++l<f;)if((c=e[l])&&I[typeof c])for(var m=-1,q=I[typeof c]&&L(c),k=q?q.length:0;++m<k;)b=q[m],"undefined"==
typeof d[b]&&(d[b]=c[b]);return d},X=function(a,g,h){var b;if(!a||!I[typeof a])return a;g=g&&"undefined"==typeof h?g:e.createCallback(g,h);for(b in a)if(!1===g(a[b],b,a))break;return a},C=function(a,g,h){if(!a||!I[typeof a])return a;g=g&&"undefined"==typeof h?g:e.createCallback(g,h);for(var b=-1,c=I[typeof a]&&L(a),d=c?c.length:0;++b<d&&(h=c[b],!1!==g(a[h],h,a)););return a},Ea=function(a){if(!a||F.call(a)!=U)return!1;var g=a.valueOf,h="function"==typeof g&&(h=la(g))&&la(h);return h?a==h||la(a)==h:
Ba(a)},ja=Y(function g(a,b,c){for(var d=-1,e=a?a.length:0,l=[];++d<e;){var f=a[d];c&&(f=c(f,d,a));K(f)?wa.apply(l,b?f:g(f)):l.push(f)}return l}),Va=Y(function(a,b,c){var e=-1,l=J(),f=a?a.length:0,m=[],r=!b&&f>=Ka&&l===d,u=c||r?w():m;if(r){var p=q(u);p?(l=k,u=p):(r=!1,u=c?u:(s(u),m))}for(;++e<f;){var p=a[e],x=c?c(p,e,a):p;if(b?!e||u[u.length-1]!==x:0>l(u,x))(c||r)&&u.push(x),m.push(p)}r?(s(u.array),t(u)):c&&s(u);return m});P&&(Wa&&"function"==typeof xa)&&(mb=Oa(xa,f));xa=8==Ta(tb+"08")?Ta:function(a,
b){return Ta(ia(a)?a.replace(Fb,""):a,b||0)};e.after=function(a,b){return 1>a?b():function(){if(1>--a)return b.apply(this,arguments)}};e.assign=Da;e.at=function(a){for(var b=-1,c=ba.apply(H,D.call(arguments,1)),d=c.length,e=G(d);++b<d;)e[b]=a[c[b]];return e};e.bind=Oa;e.bindAll=function(a){for(var b=1<arguments.length?ba.apply(H,D.call(arguments,1)):pa(a),c=-1,d=b.length;++c<d;){var e=b[c];a[e]=Oa(a[e],a)}return a};e.bindKey=function(a,b){return x(a,b,D.call(arguments,2),aa)};e.compact=function(a){for(var b=
-1,c=a?a.length:0,d=[];++b<c;){var e=a[b];e&&d.push(e)}return d};e.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length;c--;)b=[a[c].apply(this,b)];return b[0]}};e.countBy=function(a,b,c){var d={};b=e.createCallback(b,c);B(a,function(a,g,c){g=S(b(a,g,c));E.call(d,g)?d[g]++:d[g]=1});return d};e.createCallback=function(a,b,c){if(null==a)return Na;var d=typeof a;if("function"!=d){if("object"!=d)return function(b){return b[a]};var e=L(a);return function(b){for(var c=e.length,
h=!1;c--&&(h=$(b[e[c]],a[e[c]],aa)););return h}}return"undefined"==typeof b||ma&&!ma.test(Cb.call(a))?a:1===c?function(c){return a.call(b,c)}:2===c?function(c,d){return a.call(b,c,d)}:4===c?function(c,d,e,n){return a.call(b,c,d,e,n)}:function(c,d,e){return a.call(b,c,d,e)}};e.debounce=lb;e.defaults=Ua;e.defer=mb;e.delay=function(a,b){var c=D.call(arguments,2);return va(function(){a.apply(l,c)},b)};e.difference=gb;e.filter=ra;e.flatten=ja;e.forEach=B;e.forIn=X;e.forOwn=C;e.functions=pa;e.groupBy=function(a,
b,c){var d={};b=e.createCallback(b,c);B(a,function(a,g,c){g=S(b(a,g,c));(E.call(d,g)?d[g]:d[g]=[]).push(a)});return d};e.initial=function(a,c,d){if(!a)return[];var l=0,f=a.length;if("number"!=typeof c&&null!=c){var m=f;for(c=e.createCallback(c,d);m--&&c(a[m],m,a);)l++}else l=null==c||d?1:c||l;return b(a,0,sa(O(0,f-l),f))};e.intersection=function(a){for(var b=arguments,c=b.length,e=-1,l=w(),f=-1,m=J(),r=a?a.length:0,u=[],p=w();++e<c;){var x=b[e];l[e]=m===d&&(x?x.length:0)>=Ka&&q(e?b[e]:p)}a:for(;++f<
r;){var v=l[0],x=a[f];if(0>(v?k(v,x):m(p,x))){e=c;for((v||p).push(x);--e;)if(v=l[e],0>(v?k(v,x):m(b[e],x)))continue a;u.push(x)}}for(;c--;)(v=l[c])&&t(v);s(l);s(p);return u};e.invert=Za;e.invoke=function(a,b){var c=D.call(arguments,2),d=-1,e="function"==typeof b,l=a?a.length:0,f=G("number"==typeof l?l:0);B(a,function(a){f[++d]=(e?b:a[b]).apply(a,c)});return f};e.keys=L;e.map=Ha;e.max=db;e.memoize=function(a,b){function c(){var d=c.cache,e=Aa+(b?b.apply(this,arguments):arguments[0]);return E.call(d,
e)?d[e]:d[e]=a.apply(this,arguments)}c.cache={};return c};e.merge=ab;e.min=function(a,b,c){var d=Infinity,l=d;if(!b&&K(a)){c=-1;for(var f=a.length;++c<f;){var q=a[c];q<l&&(l=q)}}else b=!b&&ia(a)?m:e.createCallback(b,c),B(a,function(a,g,c){g=b(a,g,c);g<d&&(d=g,l=a)});return l};e.omit=function(a,b,c){var d=J(),l="function"==typeof b,f={};if(l)b=e.createCallback(b,c);else var m=ba.apply(H,D.call(arguments,1));X(a,function(a,g,c){if(l?!b(a,g,c):0>d(m,g))f[g]=a});return f};e.once=function(a){var b,c;return function(){if(b)return c;
b=!0;c=a.apply(this,arguments);a=null;return c}};e.pairs=function(a){for(var b=-1,c=L(a),d=c.length,e=G(d);++b<d;){var l=c[b];e[b]=[l,a[l]]}return e};e.partial=function(a){return x(a,D.call(arguments,1))};e.partialRight=function(a){return x(a,D.call(arguments,1),null,aa)};e.pick=function(a,b,c){var d={};if("function"!=typeof b)for(var l=-1,f=ba.apply(H,D.call(arguments,1)),m=M(a)?f.length:0;++l<m;){var q=f[l];q in a&&(d[q]=a[q])}else b=e.createCallback(b,c),X(a,function(a,c,g){b(a,c,g)&&(d[c]=a)});
return d};e.pluck=Ia;e.range=function(a,b,c){a=+a||0;c=+c||1;null==b&&(b=a,a=0);var d=-1;b=O(0,Bb((b-a)/c));for(var e=G(b);++d<b;)e[d]=a,a+=c;return e};e.reject=function(a,b,c){b=e.createCallback(b,c);return ra(a,function(a,c,g){return!b(a,c,g)})};e.rest=Ma;e.shuffle=function(a){var b=-1,c=a?a.length:0,d=G("number"==typeof c?c:0);B(a,function(a){var c=pb(qb()*(++b+1));d[b]=d[c];d[c]=a});return d};e.sortBy=function(a,b,c){var d=-1,l=a?a.length:0,f=G("number"==typeof l?l:0);b=e.createCallback(b,c);
B(a,function(a,c,g){var e=f[++d]=A();e.criteria=b(a,c,g);e.index=d;e.value=a});l=f.length;for(f.sort(p);l--;)a=f[l],f[l]=a.value,t(a);return f};e.tap=function(a,b){b(a);return a};e.throttle=function(a,b,c){var d=!0,e=!0;!1===c?d=!1:M(c)&&(d="leading"in c?c.leading:d,e="trailing"in c?c.trailing:e);c=A();c.leading=d;c.maxWait=b;c.trailing=e;a=lb(a,b,c);t(c);return a};e.times=function(a,b,c){a=-1<(a=+a)?a:0;var d=-1,l=G(a);for(b=e.createCallback(b,c,1);++d<a;)l[d]=b(d);return l};e.toArray=function(a){return a&&
"number"==typeof a.length?b(a):Fa(a)};e.transform=function(a,b,c,d){var l=K(a);b=e.createCallback(b,d,4);null==c&&(l?c=[]:(d=(d=a&&a.constructor)&&d.prototype,c=M(d)?oa(d):{}));(l?B:C)(a,function(a,g,d){return b(c,a,g,d)});return c};e.union=function(a){K(a)||(arguments[0]=a?D.call(a):H);return Va(ba.apply(H,arguments))};e.uniq=Va;e.unzip=ib;e.values=Fa;e.where=ra;e.without=function(a){return gb(a,D.call(arguments,1))};e.wrap=function(a,b){return function(){var c=[a];wa.apply(c,arguments);return b.apply(this,
c)}};e.zip=function(a){return a?ib(arguments):[]};e.zipObject=jb;e.collect=Ha;e.drop=Ma;e.each=B;e.extend=Da;e.methods=pa;e.object=jb;e.select=ra;e.tail=Ma;e.unique=Va;nb(e);e.chain=e;e.prototype.chain=function(){return this};e.clone=Ca;e.cloneDeep=function(a,b,c){return Ca(a,!0,b,c)};e.contains=bb;e.escape=function(a){return null==a?"":S(a).replace(Gb,na)};e.every=cb;e.find=Ga;e.findIndex=function(a,b,c){var d=-1,l=a?a.length:0;for(b=e.createCallback(b,c);++d<l;)if(b(a[d],d,a))return d;return-1};
e.findKey=function(a,b,c){var d;b=e.createCallback(b,c);C(a,function(a,c,g){if(b(a,c,g))return d=c,!1});return d};e.has=function(a,b){return a?E.call(a,b):!1};e.identity=Na;e.indexOf=Ya;e.isArguments=function(a){return F.call(a)==ha};e.isArray=K;e.isBoolean=function(a){return!0===a||!1===a||F.call(a)==da};e.isDate=function(a){return a?"object"==typeof a&&F.call(a)==ea:!1};e.isElement=function(a){return a?1===a.nodeType:!1};e.isEmpty=function(a){var b=!0;if(!a)return b;var c=F.call(a),d=a.length;if(c==
qa||(c==Z||c==ha)||c==U&&"number"==typeof d&&T(a.splice))return!d;C(a,function(){return b=!1});return b};e.isEqual=$;e.isFinite=function(a){return Db(a)&&!Eb(parseFloat(a))};e.isFunction=T;e.isNaN=function(a){return $a(a)&&a!=+a};e.isNull=function(a){return null===a};e.isNumber=$a;e.isObject=M;e.isPlainObject=Ea;e.isRegExp=function(a){return a?"object"==typeof a&&F.call(a)==ga:!1};e.isString=ia;e.isUndefined=function(a){return"undefined"==typeof a};e.lastIndexOf=function(a,b,c){var d=a?a.length:0;
for("number"==typeof c&&(d=(0>c?O(0,d+c):sa(c,d-1))+1);d--;)if(a[d]===b)return d;return-1};e.mixin=nb;e.noConflict=function(){f._=Ab;return this};e.parseInt=xa;e.random=function(a,b){null==a&&null==b&&(b=1);a=+a||0;null==b?(b=a,a=0):b=+b||0;var c=qb();return a%1||b%1?a+sa(c*(b-a+parseFloat("1e-"+((c+"").length-1))),b):a+pb(c*(b-a+1))};e.reduce=Ja;e.reduceRight=eb;e.result=function(a,b){var c=a?a[b]:l;return T(c)?a[b]():c};e.runInContext=c;e.size=function(a){var b=a?a.length:0;return"number"==typeof b?
b:L(a).length};e.some=fb;e.sortedIndex=hb;e.template=function(a,b,c){var d=e.templateSettings;a||(a="");c=Ua({},c,d);var f=Ua({},c.imports,d.imports),d=L(f),f=Fa(f),m,q=0,k=c.interpolate||za,r="__p += '",k=Qa((c.escape||za).source+"|"+k.source+"|"+(k===sb?Hb:za).source+"|"+(c.evaluate||za).source+"|$","g");a.replace(k,function(b,c,d,e,l,h){d||(d=e);r+=a.slice(q,h).replace(Ib,v);c&&(r+="' +\n__e("+c+") +\n'");l&&(m=!0,r+="';\n"+l+";\n__p += '");d&&(r+="' +\n((__t = ("+d+")) == null ? '' : __t) +\n'");
q=h+b.length;return b});var r=r+"';\n",p=k=c.variable;p||(k="obj",r="with ("+k+") {\n"+r+"\n}\n");r=(m?r.replace(Jb,""):r).replace(Kb,"$1").replace(Lb,"$1;");r="function("+k+") {\n"+(p?"":k+" || ("+k+" = {});\n")+"var __t, __p = '', __e = _.escape"+(m?", __j = Array.prototype.join;\nfunction print() { __p += __j.call(arguments, '') }\n":";\n")+r+"return __p\n}";c="\n/*\n//@ sourceURL="+(c.sourceURL||"/lodash/template/source["+Mb++ +"]")+"\n*/";try{var t=Pa(d,"return "+r+c).apply(l,f)}catch(x){throw x.source=
r,x;}if(b)return t(b);t.source=r;return t};e.unescape=function(a){return null==a?"":S(a).replace(Nb,vb)};e.uniqueId=function(a){var b=++Ob;return S(null==a?"":a)+b};e.all=cb;e.any=fb;e.detect=Ga;e.findWhere=Ga;e.foldl=Ja;e.foldr=eb;e.include=bb;e.inject=Ja;C(e,function(a,b){e.prototype[b]||(e.prototype[b]=function(){var b=[this.__wrapped__];wa.apply(b,arguments);return a.apply(e,b)})});e.first=La;e.last=function(a,c,d){if(a){var l=0,f=a.length;if("number"!=typeof c&&null!=c){var m=f;for(c=e.createCallback(c,
d);m--&&c(a[m],m,a);)l++}else if(l=c,null==l||d)return a[f-1];return b(a,O(0,f-l))}};e.take=La;e.head=La;C(e,function(a,b){e.prototype[b]||(e.prototype[b]=function(b,c){var d=a(this.__wrapped__,b,c);return null==b||c&&"function"!=typeof b?d:new r(d)})});e.VERSION="1.3.1";e.prototype.toString=function(){return S(this.__wrapped__)};e.prototype.value=ob;e.prototype.valueOf=ob;B(["join","pop","shift"],function(a){var b=H[a];e.prototype[a]=function(){return b.apply(this.__wrapped__,arguments)}});B(["push",
"reverse","sort","unshift"],function(a){var b=H[a];e.prototype[a]=function(){b.apply(this.__wrapped__,arguments);return this}});B(["concat","slice","splice"],function(a){var b=H[a];e.prototype[a]=function(){return new r(b.apply(this.__wrapped__,arguments))}});return e}var l,r=[],x=[],Ob=0,aa={},Aa=+new Date+"",Ka=75,na=40,Jb=/\b__p \+= '';/g,Kb=/\b(__p \+=) '' \+/g,Lb=/(__e\(.*?\)|\b__t\)) \+\n'';/g,Nb=/&(?:amp|lt|gt|quot|#39);/g,Hb=/\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g,xb=/\w*$/,sb=/<%=([\s\S]+?)%>/g,
ma=(ma=/\bthis\b/)&&ma.test(c)&&ma,tb=" \t\x0B\f\u00a0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000",Fb=RegExp("^["+tb+"]*0+(?=.$)"),za=/($^)/,Gb=/[&<>"']/g,Ib=/['\n\r\t\u2028\u2029\\]/g,yb="Array Boolean Date Function Math Number Object RegExp String _ attachEvent clearTimeout isFinite isNaN parseInt setImmediate setTimeout".split(" "),Mb=0,ha="[object Arguments]",qa="[object Array]",da="[object Boolean]",ea="[object Date]",
rb="[object Function]",fa="[object Number]",U="[object Object]",ga="[object RegExp]",Z="[object String]",N={};N[rb]=!1;N[ha]=N[qa]=N[da]=N[ea]=N[fa]=N[U]=N[ga]=N[Z]=!0;var I={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1},Ba={"\\":"\\","'":"'","\n":"n","\r":"r","\t":"t","\u2028":"u2028","\u2029":"u2029"},Y=I[typeof exports]&&exports,Wa=I[typeof module]&&module&&module.exports==Y&&module,J=I[typeof global]&&global;!J||J.global!==J&&J.window!==J||(a=J);var W=c();"function"==
typeof define&&"object"==typeof define.amd&&define.amd?(a._=W,define(function(){return W})):Y&&!Y.nodeType?Wa?(Wa.exports=W)._=W:Y._=W:a._=W})(this);!function(){function a(a){this.s=null!==a&&void 0!==a?"string"===typeof a?a:a.toString():a;this.orig=a;null!==a&&void 0!==a?this.__defineGetter__?this.__defineGetter__("length",function(){return this.s.length}):this.length=a.length:this.length=-1}function d(b){return new a(b)}function k(a,c){var d=[],f;for(f=0;f<a.length;f++)d.push(a[f]),c&&c.call(a,a[f],f);return d}var f={},m=String.prototype,p=a.prototype={between:function(b,c){var d=this.s,f=d.indexOf(b),m=d.indexOf(c),q=f+b.length;return new a(m>
f?d.slice(q,m):"")},camelize:function(){var b=this.trim().s.replace(/(\-|_|\s)+(.)?/g,function(a,b,d){return d?d.toUpperCase():""});return new a(b)},capitalize:function(){return new a(this.s.substr(0,1).toUpperCase()+this.s.substring(1).toLowerCase())},charAt:function(a){return this.s.charAt(a)},chompLeft:function(b){var c=this.s;return 0===c.indexOf(b)?(c=c.slice(b.length),new a(c)):this},chompRight:function(b){if(this.endsWith(b)){var c=this.s,c=c.slice(0,c.length-b.length);return new a(c)}return this},
collapseWhitespace:function(){var b=this.s.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"");return new a(b)},contains:function(a){return 0<=this.s.indexOf(a)},count:function(a){for(var c=0,d=this.s.indexOf(a);0<=d;)c+=1,d=this.s.indexOf(a,d+1);return c},dasherize:function(){var b=this.trim().s.replace(/[_\s]+/g,"-").replace(/([A-Z])/g,"-$1").replace(/-+/g,"-").toLowerCase();return new a(b)},decodeHtmlEntities:function(){var b=this.s,b=b.replace(/&#(\d+);?/g,function(a,b){return String.fromCharCode(b)}).replace(/&#[xX]([A-Fa-f0-9]+);?/g,
function(a,b){return String.fromCharCode(parseInt(b,16))}).replace(/&([^;\W]+;?)/g,function(a,b){var d=b.replace(/;$/,""),d=f[b]||b.match(/;$/)&&f[d];return"number"===typeof d?String.fromCharCode(d):"string"===typeof d?d:a});return new a(b)},endsWith:function(a){var c=this.s.length-a.length;return 0<=c&&this.s.indexOf(a,c)===c},escapeHTML:function(){return new a(this.s.replace(/[&<>"']/g,function(a){return"&"+s[a]+";"}))},ensureLeft:function(b){var c=this.s;return 0===c.indexOf(b)?this:new a(b+c)},
ensureRight:function(b){var c=this.s;return this.endsWith(b)?this:new a(c+b)},humanize:function(){if(null===this.s||void 0===this.s)return new a("");var b=this.underscore().replace(/_id$/,"").replace(/_/g," ").trim().capitalize();return new a(b)},isAlpha:function(){return!/[^a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isAlphaNumeric:function(){return!/[^0-9a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isEmpty:function(){return null===this.s||void 0===this.s?!0:/^[\s\xa0]*$/.test(this.s)},isLower:function(){return this.isAlpha()&&
this.s.toLowerCase()===this.s},isNumeric:function(){return!/[^0-9]/.test(this.s)},isUpper:function(){return this.isAlpha()&&this.s.toUpperCase()===this.s},left:function(b){return 0<=b?(b=this.s.substr(0,b),new a(b)):this.right(-b)},lines:function(){return this.replaceAll("\r\n","\n").s.split("\n")},pad:function(b,c){c=c||" ";if(this.s.length>=b)return new a(this.s);b-=this.s.length;var d=Array(Math.ceil(b/2)+1).join(c),f=Array(Math.floor(b/2)+1).join(c);return new a(d+this.s+f)},padLeft:function(b,
c){c=c||" ";return this.s.length>=b?new a(this.s):new a(Array(b-this.s.length+1).join(c)+this.s)},padRight:function(b,c){c=c||" ";return this.s.length>=b?new a(this.s):new a(this.s+Array(b-this.s.length+1).join(c))},parseCSV:function(a,c,d,f){a=a||",";d=d||"\\";"undefined"==typeof c&&(c='"');var m=0,q=[],k=[],p=this.s.length,t=!1;if("undefined"!==typeof f)var s=[];for(c||(t=!0);m<p;){var v=this.s.charAt(m);switch(v){case d:if(t&&(d!==c||this.s.charAt(m+1)===c)){m+=1;q.push(this.s.charAt(m));break}if(d!==
c)break;case c:t=!t;break;case a:t&&c?q.push(v):(k.push(q.join("")),q.length=0);break;case f:t?q.push(v):s&&(k.push(q.join("")),s.push(k),k=[],q.length=0);break;default:t&&q.push(v)}m+=1}k.push(q.join(""));return s?(s.push(k),s):k},replaceAll:function(b,c){var d=this.s.split(b).join(c);return new a(d)},right:function(b){return 0<=b?(b=this.s.substr(this.s.length-b,b),new a(b)):this.left(-b)},slugify:function(){var b=(new a(this.s.replace(/[^\w\s-]/g,"").toLowerCase())).dasherize().s;"-"===b.charAt(0)&&
(b=b.substr(1));return new a(b)},startsWith:function(a){return 0===this.s.lastIndexOf(a,0)},stripPunctuation:function(){return new a(this.s.replace(/[^\w\s]|_/g,"").replace(/\s+/g," "))},stripTags:function(){var b=this.s;k(0<arguments.length?arguments:[""],function(a){b=b.replace(RegExp("</?"+a+"[^<>]*>","gi"),"")});return new a(b)},template:function(b,c,l){var f=this.s;c=c||d.TMPL_OPEN;l=l||d.TMPL_CLOSE;(f.match(RegExp(c+"(.+?)"+l,"g"))||[]).forEach(function(a){var d=a.substring(c.length,a.length-
l.length);b[d]&&(f=f.replace(a,b[d]))});return new a(f)},times:function(b){return new a(Array(b+1).join(this.s))},toBoolean:function(){if("string"===typeof this.orig){var a=this.s.toLowerCase();return"true"===a||"yes"===a||"on"===a}return!0===this.orig||1===this.orig},toFloat:function(a){var c=parseFloat(this.s);return a?parseFloat(c.toFixed(a)):c},toInt:function(){return/^\s*-?0x/i.test(this.s)?parseInt(this.s,16):parseInt(this.s,10)},trim:function(){var b;b="undefined"===typeof m.trim?this.s.replace(/(^\s*|\s*$)/g,
""):this.s.trim();return new a(b)},trimLeft:function(){var b;b=m.trimLeft?this.s.trimLeft():this.s.replace(/(^\s*)/g,"");return new a(b)},trimRight:function(){var b;b=m.trimRight?this.s.trimRight():this.s.replace(/\s+$/,"");return new a(b)},truncate:function(b,c){var d=this.s;b=~~b;c=c||"...";if(d.length<=b)return new a(d);var f=d.slice(0,b+1).replace(/.(?=\W*\w*$)/g,function(a){return a.toUpperCase()!==a.toLowerCase()?"A":" "}),f=f.slice(f.length-2).match(/\w\w/)?f.replace(/\s*\S+$/,""):(new a(f.slice(0,
f.length-1))).trimRight().s;return(f+c).length>d.length?new a(d):new a(d.slice(0,f.length)+c)},toCSV:function(b,c){var d=",",f='"',m="\\",q=!0,k=!1,p=[];"object"===typeof b?(d=b.delimiter||d,d=b.separator||d,f=b.qualifier||f,q=!!b.encloseNumbers,m=b.escape||m,k=!!b.keys):"string"===typeof b&&(d=b);"string"===typeof c&&(f=c);null===c&&(f=null);if(this.orig instanceof Array)p=this.orig;else for(var t in this.orig)this.orig.hasOwnProperty(t)&&(k?p.push(t):p.push(this.orig[t]));m+=f;k=[];for(t=0;t<p.length;++t){var s=
null!==f&&""!==f;"number"==typeof p[t]&&(s&=q);s&&k.push(f);if(null!==p[t]&&void 0!==p[t]){var v=(new a(p[t])).replaceAll(f,m).s;k.push(v)}else k.push("");s&&k.push(f);d&&k.push(d)}k.length-=1;return new a(k.join(""))},toString:function(){return this.s},underscore:function(){var b=this.trim().s.replace(/([a-z\d])([A-Z]+)/g,"$1_$2").replace(/[-\s]+/g,"_").toLowerCase();(new a(this.s.charAt(0))).isUpper()&&(b="_"+b);return new a(b)},unescapeHTML:function(){return new a(this.s.replace(/\&([^;]+);/g,
function(a,c){var d;return c in A?A[c]:(d=c.match(/^#x([\da-fA-F]+)$/))?String.fromCharCode(parseInt(d[1],16)):(d=c.match(/^#(\d+)$/))?String.fromCharCode(~~d[1]):a}))},valueOf:function(){return this.s.valueOf()}},q=[],v=function(){var a;a=[];if(Object.getOwnPropertyNames)a=Object.getOwnPropertyNames(m),a.splice(a.indexOf("valueOf"),1),a.splice(a.indexOf("toString"),1);else{var c={},d;for(d in String.prototype)c[d]=d;for(d in Object.prototype)delete c[d];for(d in c)a.push(d)}c={};for(d=0;d<a.length;++d){var f=
a[d],k=m[f];try{var q=typeof k.apply("teststring",[]);c[f]=q}catch(p){}}return c}(),w;for(w in v)(function(b){var c=m[b];"function"==typeof c&&(p[b]||(p[b]="string"===v[b]?function(){return new a(c.apply(this,arguments))}:c))})(w);p.repeat=p.times;p.include=p.contains;p.toInteger=p.toInt;p.toBool=p.toBoolean;p.decodeHTMLEntities=p.decodeHtmlEntities;d.extendPrototype=function(){for(var a in p)(function(a){var b=p[a];m.hasOwnProperty(a)||(q.push(a),m[a]=function(){String.prototype.s=this;return b.apply(this,
arguments)})})(a)};d.restorePrototype=function(){for(var a=0;a<q.length;++a)delete String.prototype[q[a]];q.length=0};d.VERSION="1.5.0";d.TMPL_OPEN="{{";d.TMPL_CLOSE="}}";d.ENTITIES=f;"undefined"!==typeof module&&"undefined"!==typeof module.exports?module.exports=d:"function"===typeof define&&define.amd?define([],function(){return d}):window.S=d;var A={lt:"<",gt:">",quot:'"',apos:"'",amp:"&"},s={},t;for(t in A)s[A[t]]=t;f={amp:"&",gt:">",lt:"<",quot:'"',apos:"'",AElig:198,Aacute:193,Acirc:194,Agrave:192,
Aring:197,Atilde:195,Auml:196,Ccedil:199,ETH:208,Eacute:201,Ecirc:202,Egrave:200,Euml:203,Iacute:205,Icirc:206,Igrave:204,Iuml:207,Ntilde:209,Oacute:211,Ocirc:212,Ograve:210,Oslash:216,Otilde:213,Ouml:214,THORN:222,Uacute:218,Ucirc:219,Ugrave:217,Uuml:220,Yacute:221,aacute:225,acirc:226,aelig:230,agrave:224,aring:229,atilde:227,auml:228,ccedil:231,eacute:233,ecirc:234,egrave:232,eth:240,euml:235,iacute:237,icirc:238,igrave:236,iuml:239,ntilde:241,oacute:243,ocirc:244,ograve:242,oslash:248,otilde:245,
ouml:246,szlig:223,thorn:254,uacute:250,ucirc:251,ugrave:249,uuml:252,yacute:253,yuml:255,copy:169,reg:174,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,ordf:170,laquo:171,not:172,shy:173,macr:175,deg:176,plusmn:177,sup1:185,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,ordm:186,raquo:187,frac14:188,frac12:189,frac34:190,iquest:191,times:215,divide:247,"OElig;":338,"oelig;":339,"Scaron;":352,"scaron;":353,"Yuml;":376,"fnof;":402,"circ;":710,
"tilde;":732,"Alpha;":913,"Beta;":914,"Gamma;":915,"Delta;":916,"Epsilon;":917,"Zeta;":918,"Eta;":919,"Theta;":920,"Iota;":921,"Kappa;":922,"Lambda;":923,"Mu;":924,"Nu;":925,"Xi;":926,"Omicron;":927,"Pi;":928,"Rho;":929,"Sigma;":931,"Tau;":932,"Upsilon;":933,"Phi;":934,"Chi;":935,"Psi;":936,"Omega;":937,"alpha;":945,"beta;":946,"gamma;":947,"delta;":948,"epsilon;":949,"zeta;":950,"eta;":951,"theta;":952,"iota;":953,"kappa;":954,"lambda;":955,"mu;":956,"nu;":957,"xi;":958,"omicron;":959,"pi;":960,
"rho;":961,"sigmaf;":962,"sigma;":963,"tau;":964,"upsilon;":965,"phi;":966,"chi;":967,"psi;":968,"omega;":969,"thetasym;":977,"upsih;":978,"piv;":982,"ensp;":8194,"emsp;":8195,"thinsp;":8201,"zwnj;":8204,"zwj;":8205,"lrm;":8206,"rlm;":8207,"ndash;":8211,"mdash;":8212,"lsquo;":8216,"rsquo;":8217,"sbquo;":8218,"ldquo;":8220,"rdquo;":8221,"bdquo;":8222,"dagger;":8224,"Dagger;":8225,"bull;":8226,"hellip;":8230,"permil;":8240,"prime;":8242,"Prime;":8243,"lsaquo;":8249,"rsaquo;":8250,"oline;":8254,"frasl;":8260,
"euro;":8364,"image;":8465,"weierp;":8472,"real;":8476,"trade;":8482,"alefsym;":8501,"larr;":8592,"uarr;":8593,"rarr;":8594,"darr;":8595,"harr;":8596,"crarr;":8629,"lArr;":8656,"uArr;":8657,"rArr;":8658,"dArr;":8659,"hArr;":8660,"forall;":8704,"part;":8706,"exist;":8707,"empty;":8709,"nabla;":8711,"isin;":8712,"notin;":8713,"ni;":8715,"prod;":8719,"sum;":8721,"minus;":8722,"lowast;":8727,"radic;":8730,"prop;":8733,"infin;":8734,"ang;":8736,"and;":8743,"or;":8744,"cap;":8745,"cup;":8746,"int;":8747,
"there4;":8756,"sim;":8764,"cong;":8773,"asymp;":8776,"ne;":8800,"equiv;":8801,"le;":8804,"ge;":8805,"sub;":8834,"sup;":8835,"nsub;":8836,"sube;":8838,"supe;":8839,"oplus;":8853,"otimes;":8855,"perp;":8869,"sdot;":8901,"lceil;":8968,"rceil;":8969,"lfloor;":8970,"rfloor;":8971,"lang;":9001,"rang;":9002,"loz;":9674,"spades;":9824,"clubs;":9827,"hearts;":9829,"diams;":9830}}.call(this);(function(){this.H={Check:{},TennisScoreKeeper:{}}}).call(this);(function(a){function d(d){return d===a||null===d}function k(a){this.isBetweenInclusive=function(d,f){return a>=d&&a<=f};this.isBetweenExclusive=function(d,f){return a>d&&a<f}}function f(a,d){var k=typeof a,v=typeof d;if(null===a&&null===d)return!0;if(k!==v)return!1;if("object"!==k&&"object"!==v)return a==d;var k=!0,w;for(w in a)if("function"!==typeof a[w]&&(k=k&&f(a[w],d[w]),!k))return!1;return!0}this.notEmpty=function(d,f){if(d===a||null===d)throw Error("Parameter '"+f+"' cannot be null or undefined");
};this.condition=function(a,d){if(!a)throw Error(d||"An error occured");};this.isEmpty=d;this.isNotEmpty=function(a){return!d(a)};this.areSame=f;this.value=function(a){return new k(a)}}).call(this.H.Check);(function(a,d,k){function f(d,b){a.condition("15b6d1fc81a043c081242617308b4fdc"===b,"GameTieMode must not be instantiated. Use TieMode enum.");a.notEmpty(d,"id");a.notEmpty(b,"pointByDifferenceFunc");a.condition("function"===typeof b,"pointByDifferenceFunc must be a function returning tennisPoint via point difference");this.PointByDifference=function(a){return b.call(null,a)};this.id=d}function m(d){a.notEmpty(d,"label");this.label=d;this.id=q(d)}function p(d,b,c,f){a.condition("82ee546ae51f4a77a048186fa13e98f1"===
f,"PointType must not be instantiated. Use PointTypes enum.");a.notEmpty(b,"label");a.notEmpty(c,"shotStyle");a.condition(d===s.PointWinner||d===s.PointLoser,"Point credit goes to winner or loser. Use pointCreditTypes enum");this.label=b;this.creditTo=d;this.id=q(b)}function q(a){return d(a).trim().replaceAll(" ","").replaceAll("/","-").s}var v={Love:{id:"Love",code:"0"},Fifteen:{id:"Fifteen",code:"15"},Thirty:{id:"Thirty",code:"30"},Fourty:{id:"Fourty",code:"40"},Advantage:{id:"Advantage",code:"Ad"}},
w={advantageWin:new f("AdvantageWin",function(d){a.condition(a.value(d).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return a.value(d).isBetweenInclusive(-1,0)?v.Fourty:1===d?v.Advantage:v.Love},"15b6d1fc81a043c081242617308b4fdc"),singlePointWin:new f("SinglePointWin",function(d){a.condition(a.value(d).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return 0===d?v.Fourty:v.Love},"15b6d1fc81a043c081242617308b4fdc")},A={tiebreak:{id:"TieBreak",
minimumGamePoints:7},superTiebreak:{id:"SuperTieBreak",minimumGamePoints:10},gameDifference:{id:"GameDifference",minimumGamePoints:4}};k={NormalPassing:new m("Normal/Passing"),Smash:new m("Smash"),Lob:new m("Lob"),Drop:new m("Drop")};var s={PointWinner:0,PointLoser:1};this.Model={Player:function(d){a.notEmpty(d,"name");this.name=d;this.id=q(d)},MatchDefinition:function(d,b,c){a.notEmpty(d,"playerOne");a.notEmpty(b,"playerTwo");this.players=[d,b];this.gamesPerSet=6;this.setsCount=3;this.gameTieMode=
w.advantageWin;this.lastSetTieMode=A.tiebreak;this.startingPlayer=c?b:d},TieMode:w,LastSetTieMode:A,Point:function(d,b,c,f){a.notEmpty(d,"forPlayer");a.notEmpty(b,"creditedTo");a.notEmpty(c,"type");this.player=d;this.creditedTo=b;this.timestamp=new Date;this.type=c;this.isOnSecondServe=f},ShotStyles:k,PointCreditTypes:s,PointTypes:{WinningShot:function(a){return new p(s.PointWinner,"Winning Shot",a,"82ee546ae51f4a77a048186fa13e98f1")},ForcedError:function(a){return new p(s.PointWinner,"Forced Error",
a,"82ee546ae51f4a77a048186fa13e98f1")},UnforcedError:function(a){return new p(s.PointLoser,"Unforced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},Ace:function(a){return new p(s.PointWinner,"Ace",a,"82ee546ae51f4a77a048186fa13e98f1")},DoubleFault:function(a){return new p(s.PointLoser,"Double Fault",a,"82ee546ae51f4a77a048186fa13e98f1")}},PointType:p,TennisPoints:v}}).call(this.H.TennisScoreKeeper,this.H.Check,this.S);(function(a,d,k){function f(f){a.notEmpty(f,"player");this.Player=f;this.Game=d.TennisPoints.Love;this.Sets=this.Games=this.GamePoints=0}function m(d,f,k,m){a.notEmpty(d,"playerOneScoreProjection");a.notEmpty(f,"playerTwoScoreProjection");a.notEmpty(k,"setsPerMatch");a.notEmpty(m,"servingPlayer");var p=this,t=Math.ceil(k/2);this.PlayerOne=d;this.PlayerTwo=f;this.Winner=function(){return d.Sets===t?d:f.Sets===t?f:null};this.IsWon=function(){return null!==p.Winner()};this.ServingPlayer=function(){return m}}
var p=[d.TennisPoints.Love,d.TennisPoints.Fifteen,d.TennisPoints.Thirty,d.TennisPoints.Fourty];this.ScoreProjector=function(k){function v(b,c){b.GamePoints++;var f;f=b.Games===k.gamesPerSet&&c.Games===k.gamesPerSet;f=b.Sets===c.Sets&&b.Sets===Math.floor(k.setsCount/2)?f&&k.lastSetTieMode!==d.LastSetTieMode.gameDifference:f;f?(t=s,0!==(b.GamePoints+c.GamePoints)%2&&A(),2<=b.GamePoints-c.GamePoints&&b.GamePoints>=(b.Sets===c.Sets&&b.Sets===Math.floor(k.setsCount/2)?k.lastSetTieMode.minimumGamePoints:
7)&&(s=t===b.Player?c.Player:b.Player,w(b,c),b.Games=0,c.Games=0,b.Sets++)):3>=b.GamePoints?b.Game=p[b.GamePoints]:a.value(b.GamePoints-c.GamePoints).isBetweenInclusive(-1,1)?(f=b.GamePoints-c.GamePoints,b.Game=k.gameTieMode.PointByDifference(f),c.Game=k.gameTieMode.PointByDifference(-f),0<f&&(b.Game==d.TennisPoints.Love&&c.Game==d.TennisPoints.Love)&&w(b,c)):w(b,c)}function w(a,c){a.Game=d.TennisPoints.Love;c.Game=d.TennisPoints.Love;a.GamePoints=0;c.GamePoints=0;a.Games++;A();2<=a.Games-c.Games&&
a.Games>=k.gamesPerSet&&(a.Games=0,c.Games=0,a.Sets++)}function A(){s=s===k.players[0]?k.players[1]:k.players[0]}a.notEmpty(k,"gameDefinition");var s=k.startingPlayer,t=null;this.toTennisScore=function(b){a.notEmpty(b,"points");var c=new f(k.players[0]),d=new f(k.players[1]);s=k.startingPlayer;for(var p=0;p<b.length;p++)b[p].player===c.Player?v(c,d):v(d,c);return new m(c,d,k.setsCount,s)}}}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model);(function(a,d,k){function f(f){a.notEmpty(f,"players");a.condition(2===f.length,"The match must have exactly two players");this.pointFor=function(a,k,m){var A=a===f[0]?f[1]:f[0];return new d.Point(a,k.creditTo===d.PointCreditTypes.PointWinner?a:A,k,!0===m?!0:!1)}}var m=this;this.Engine=function(d){a.notEmpty(d,"gameDefinition");var k=[],v=new f(d.players),w=[],A=new m.ScoreProjector(d),w=[d.players[0],d.players[1]];this.scorePointFor=function(a,d,b){a=v.pointFor(a,d,b);k.push(a)};this.undoLatestPoint=
function(){0!==k.length&&k.pop()};this.players=w;this.points=k;this.tennisScore=function(){return A.toTennisScore(k)}};this.PointFactory=f}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model,this._);