var COMPILED=!0,goog=goog||{};goog.global=this;goog.define=function(a,b){var l=b;COMPILED||goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(l=goog.global.CLOSURE_DEFINES[a]);goog.exportPath_(a,l)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;
goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,l){a=a.split(".");l=l||goog.global;a[0]in l||!l.execScript||l.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?l[d]=b:l=l[d]?l[d]:l[d]={}};goog.getObjectByName=function(a,b){for(var l=a.split("."),d=b||goog.global,g;g=l.shift();)if(goog.isDefAndNotNull(d[g]))d=d[g];else return null;return d};
goog.globalize=function(a,b){var l=b||goog.global,d;for(d in a)l[d]=a[d]};goog.addDependency=function(a,b,l){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var g=goog.dependencies_,q=0;d=b[q];q++)g.nameToPath[d]=a,a in g.pathToNames||(g.pathToNames[a]={}),g.pathToNames[a][d]=!0;for(d=0;b=l[d];d++)a in g.requires||(g.requires[a]={}),g.requires[a][b]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var l=a[b].src,d=l.lastIndexOf("?"),d=
-1==d?l.length:d;if("base.js"==l.substr(d-7,7)){goog.basePath=l.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(g){if(!(g in d.written)){if(!(g in d.visited)&&(d.visited[g]=!0,g in d.requires))for(var n in d.requires[g])if(!goog.isProvided_(n))if(n in d.nameToPath)a(d.nameToPath[n]);else throw Error("Undefined nameToPath for "+n);g in l||(l[g]=!0,b.push(g))}}var b=[],l={},d=goog.dependencies_,g;for(g in goog.included_)d.written[g]||a(g);for(g=0;g<b.length;g++)if(b[g])goog.importScript_(goog.basePath+b[g]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var l=Object.prototype.toString.call(a);if("[object Window]"==l)return"object";if("[object Array]"==l||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==l||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},l;for(l in a)b[l]=goog.cloneObject(a[l]);return b}return a};goog.bindNative_=function(a,b,l){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,l){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var g=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(g,d);return a.apply(b,g)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,l){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var l=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,l);return a.apply(this,b)}};goog.mixin=function(a,b){for(var l in b)a[l]=b[l]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,l=b.createElement("script");l.type="text/javascript";l.defer=!1;l.appendChild(b.createTextNode(a));b.body.appendChild(l);
b.body.removeChild(l)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var l=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],n=0;n<a.length;n++)b.push(l(a[n]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?l:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var l=b||{},d;for(d in l){var g=(""+l[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),g)}return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,l){goog.exportPath_(a,b,l)};goog.exportProperty=function(a,b,l){a[b]=l};
goog.inherits=function(a,b){function l(){}l.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new l;a.prototype.constructor=a};
goog.base=function(a,b,l){var d=arguments.callee.caller;if(goog.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var g=Array.prototype.slice.call(arguments,2),q=!1,n=a.constructor;n;n=n.superClass_&&n.superClass_.constructor)if(n.prototype[b]===d)q=!0;else if(q)return n.prototype[b].apply(a,
g);if(a[b]===d)return a.constructor.prototype[b].apply(a,g);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};/*

 Lo-Dash 1.3.1 (Custom Build) <http://lodash.com/>
 Build: `lodash modern -o ./dist/lodash.js`
 Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>
 Based on Underscore.js 1.4.4 <http://underscorejs.org/>
 Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud Inc.
 Available under MIT license <http://lodash.com/license>
*/
(function(a){function b(a,c,b){b=(b||0)-1;for(var f=a.length;++b<f;)if(a[b]===c)return b;return-1}function l(a,c){var f=typeof c;a=a.cache;if("boolean"==f||null==c)return a[c];"number"!=f&&"string"!=f&&(f="object");var g="number"==f?c:$+c;a=a[f]||(a[f]={});return"object"==f?a[g]&&-1<b(a[g],c)?0:-1:a[g]?0:-1}function d(a){var c=this.cache,b=typeof a;if("boolean"==b||null==a)c[a]=!0;else{"number"!=b&&"string"!=b&&(b="object");var f="number"==b?a:$+a,g=c[b]||(c[b]={});"object"==b?(g[f]||(g[f]=[])).push(a)==
this.array.length&&(c[b]=!1):g[f]=!0}}function g(a){return a.charCodeAt(0)}function q(a,c){var b=a.index,f=c.index;a=a.criteria;c=c.criteria;if(a!==c){if(a>c||"undefined"==typeof a)return 1;if(a<c||"undefined"==typeof c)return-1}return b<f?-1:1}function n(a){var c=-1,b=a.length,f=v();f["false"]=f["null"]=f["true"]=f.undefined=!1;var g=v();g.array=a;g.cache=f;for(g.push=d;++c<b;)g.push(a[c]);return!1===f.object?(p(g),null):g}function A(a){return"\\"+Ca[a]}function u(){return s.pop()||[]}function v(){return z.pop()||
{array:null,cache:null,criteria:null,"false":!1,index:0,leading:!1,maxWait:0,"null":!1,number:null,object:null,push:null,string:null,trailing:!1,"true":!1,undefined:!1,value:null}}function w(a){a.length=0;s.length<x&&s.push(a)}function p(a){var c=a.cache;c&&p(c);a.array=a.cache=a.criteria=a.object=a.number=a.string=a.value=null;z.length<x&&z.push(a)}function c(a,c,b){c||(c=0);"undefined"==typeof b&&(b=a?a.length:0);var f=-1;b=b-c||0;for(var g=Array(0>b?0:b);++f<b;)g[f]=a[c+f];return g}function f(d){function e(a){return a&&
"object"==typeof a&&!L(a)&&F.call(a,"__wrapped__")?a:new s(a)}function s(a){this.__wrapped__=a}function x(a,h,k,m){function y(){var m=arguments,g=e?this:h;c||(a=h[b]);k.length&&(m=m.length?(m=E.call(m),f?m.concat(k):k.concat(m)):k);return this instanceof y?(g=N(a.prototype)?pa(a.prototype):{},m=a.apply(g,m),N(m)?m:g):a.apply(g,m)}var c=U(a),e=!k,b=h;if(e){var f=m;k=h}else if(!c){if(!m)throw new ub;h=a}return y}function z(a){return Xa[a]}function K(a,h,k){var m=(m=e.indexOf)===Ya?b:m;return m}function Z(a){return function(h,
k,m,c){"boolean"!=typeof k&&null!=k&&(m=(c=m)&&c[k]===h?r:k,k=!1);null!=m&&(m=e.createCallback(m,c));return a(h,k,m,c)}}function Ca(a){var h,k;if(!a||G.call(a)!=V||(h=a.constructor,U(h)&&!(h instanceof h)))return!1;Y(a,function(h,a){k=a});return k===r||F.call(a,k)}function vb(a){return wb[a]}function Da(a,h,k,m,y,aa){var b=a;"boolean"!=typeof h&&null!=h&&(m=k,k=h,h=!1);if("function"==typeof k){k="undefined"==typeof m?k:e.createCallback(k,m,1);b=k(b);if("undefined"!=typeof b)return b;b=a}if(m=N(b)){var f=
G.call(b);if(!O[f])return b;var g=L(b)}if(!m||!h)return m?g?c(b):Ea({},b):b;m=R[f];switch(f){case fa:case ga:return new m(+b);case ha:case ba:return new m(b);case ia:return m(b.source,xb.exec(b))}f=!y;y||(y=u());aa||(aa=u());for(var d=y.length;d--;)if(y[d]==a)return aa[d];b=g?m(b.length):{};g&&(F.call(a,"index")&&(b.index=a.index),F.call(a,"input")&&(b.input=a.input));y.push(a);aa.push(b);(g?C:D)(a,function(a,m){b[m]=Da(a,h,k,r,y,aa)});f&&(w(y),w(aa));return b}function qa(a){var h=[];Y(a,function(a,
m){U(a)&&h.push(m)});return h.sort()}function Za(a){for(var h=-1,k=M(a),m=k.length,c={};++h<m;){var b=k[h];c[a[b]]=b}return c}function ca(a,h,k,m,c,b){var f=k===S;if("function"==typeof k&&!f){k=e.createCallback(k,m,2);var g=k(a,h);if("undefined"!=typeof g)return!!g}if(a===h)return 0!==a||1/a==1/h;var d=typeof a,B=typeof h;if(a===a&&(!a||"function"!=d&&"object"!=d)&&(!h||"function"!=B&&"object"!=B))return!1;if(null==a||null==h)return a===h;B=G.call(a);d=G.call(h);B==ja&&(B=V);d==ja&&(d=V);if(B!=d)return!1;
switch(B){case fa:case ga:return+a==+h;case ha:return a!=+a?h!=+h:0==a?1/a==1/h:a==+h;case ia:case ba:return a==T(h)}d=B==ra;if(!d){if(F.call(a,"__wrapped__ ")||F.call(h,"__wrapped__"))return ca(a.__wrapped__||a,h.__wrapped__||h,k,m,c,b);if(B!=V)return!1;var B=a.constructor,r=h.constructor;if(B!=r&&!(U(B)&&B instanceof B&&U(r)&&r instanceof r))return!1}r=!c;c||(c=u());b||(b=u());for(B=c.length;B--;)if(c[B]==a)return b[B]==h;var p=0,g=!0;c.push(a);b.push(h);if(d){B=a.length;p=h.length;g=p==a.length;
if(!g&&!f)return g;for(;p--;)if(d=B,r=h[p],f)for(;d--&&!(g=ca(a[d],r,k,m,c,b)););else if(!(g=ca(a[p],r,k,m,c,b)))break;return g}Y(h,function(h,e,f){if(F.call(f,e))return p++,g=F.call(a,e)&&ca(a[e],h,k,m,c,b)});g&&!f&&Y(a,function(h,a,k){if(F.call(k,a))return g=-1<--p});r&&(w(c),w(b));return g}function U(a){return"function"==typeof a}function N(a){return!(!a||!J[typeof a])}function $a(a){return"number"==typeof a||G.call(a)==ha}function ka(a){return"string"==typeof a||G.call(a)==ba}function ab(a,h,
k){var m=arguments,c=0,b=2;if(!N(a))return a;if(k===S)var f=m[3],g=m[4],d=m[5];else{var r=!0,g=u(),d=u();"number"!=typeof k&&(b=m.length);3<b&&"function"==typeof m[b-2]?f=e.createCallback(m[--b-1],m[b--],2):2<b&&"function"==typeof m[b-1]&&(f=m[--b])}for(;++c<b;)(L(m[c])?C:D)(m[c],function(h,k){var m,c,y=h,b=a[k];if(h&&((c=L(h))||Fa(h))){for(y=g.length;y--;)if(m=g[y]==h){b=d[y];break}if(!m){var e;f&&(y=f(b,h),e="undefined"!=typeof y)&&(b=y);e||(b=c?L(b)?b:[]:Fa(b)?b:{});g.push(h);d.push(b);e||(b=ab(b,
h,S,f,g,d))}}else f&&(y=f(b,h),"undefined"==typeof y&&(y=h)),"undefined"!=typeof y&&(b=y);a[k]=b});r&&(w(g),w(d));return a}function Ga(a){for(var h=-1,k=M(a),m=k.length,c=H(m);++h<m;)c[h]=a[k[h]];return c}function bb(a,h,k){var m=-1,c=K(),b=a?a.length:0,e=!1;k=(0>k?P(0,b+k):k)||0;b&&"number"==typeof b?e=-1<(ka(a)?a.indexOf(h,k):c(a,h,k)):D(a,function(a){if(++m>=k)return!(e=a===h)});return e}function cb(a,h,k){var m=!0;h=e.createCallback(h,k);k=-1;var c=a?a.length:0;if("number"==typeof c)for(;++k<
c&&(m=!!h(a[k],k,a)););else D(a,function(a,k,c){return m=!!h(a,k,c)});return m}function sa(a,h,k){var m=[];h=e.createCallback(h,k);k=-1;var c=a?a.length:0;if("number"==typeof c)for(;++k<c;){var b=a[k];h(b,k,a)&&m.push(b)}else D(a,function(a,k,c){h(a,k,c)&&m.push(a)});return m}function Ha(a,h,k){h=e.createCallback(h,k);k=-1;var m=a?a.length:0;if("number"==typeof m)for(;++k<m;){var c=a[k];if(h(c,k,a))return c}else{var b;D(a,function(a,k,c){if(h(a,k,c))return b=a,!1});return b}}function C(a,h,k){var c=
-1,b=a?a.length:0;h=h&&"undefined"==typeof k?h:e.createCallback(h,k);if("number"==typeof b)for(;++c<b&&!1!==h(a[c],c,a););else D(a,h);return a}function Ia(a,h,k){var c=-1,b=a?a.length:0;h=e.createCallback(h,k);if("number"==typeof b)for(var f=H(b);++c<b;)f[c]=h(a[c],c,a);else f=[],D(a,function(a,k,b){f[++c]=h(a,k,b)});return f}function db(a,h,k){var c=-Infinity,b=c;if(!h&&L(a)){k=-1;for(var f=a.length;++k<f;){var d=a[k];d>b&&(b=d)}}else h=!h&&ka(a)?g:e.createCallback(h,k),C(a,function(a,k,e){k=h(a,
k,e);k>c&&(c=k,b=a)});return b}function Ja(a,h){var k=-1,c=a?a.length:0;if("number"==typeof c)for(var b=H(c);++k<c;)b[k]=a[k][h];return b||Ia(a,h)}function Ka(a,h,k,c){if(!a)return k;var b=3>arguments.length;h=e.createCallback(h,c,4);var f=-1,g=a.length;if("number"==typeof g)for(b&&(k=a[++f]);++f<g;)k=h(k,a[f],f,a);else D(a,function(a,c,m){k=b?(b=!1,a):h(k,a,c,m)});return k}function eb(a,h,k,c){var b=a?a.length:0,f=3>arguments.length;if("number"!=typeof b)var g=M(a),b=g.length;h=e.createCallback(h,
c,4);C(a,function(c,m,e){m=g?g[--b]:--b;k=f?(f=!1,a[m]):h(k,a[m],m,e)});return k}function fb(a,h,k){var c;h=e.createCallback(h,k);k=-1;var b=a?a.length:0;if("number"==typeof b)for(;++k<b&&!(c=h(a[k],k,a)););else D(a,function(a,k,b){return!(c=h(a,k,b))});return!!c}function gb(a){var h=-1,k=K(),c=a?a.length:0,e=da.apply(I,E.call(arguments,1)),f=[],g=c>=t&&k===b;if(g){var d=n(e);d?(k=l,e=d):g=!1}for(;++h<c;)d=a[h],0>k(e,d)&&f.push(d);g&&p(e);return f}function La(a,h,k){if(a){var m=0,b=a.length;if("number"!=
typeof h&&null!=h){var f=-1;for(h=e.createCallback(h,k);++f<b&&h(a[f],f,a);)m++}else if(m=h,null==m||k)return a[0];return c(a,0,ta(P(0,m),b))}}function Ya(a,h,k){if("number"==typeof k){var c=a?a.length:0;k=0>k?P(0,c+k):k||0}else if(k)return k=hb(a,h),a[k]===h?k:-1;return a?b(a,h,k):-1}function Ma(a,h,k){if("number"!=typeof h&&null!=h){var m=0,b=-1,f=a?a.length:0;for(h=e.createCallback(h,k);++b<f&&h(a[b],b,a);)m++}else m=null==h||k?1:P(0,h);return c(a,m)}function hb(a,h,k,c){var b=0,f=a?a.length:b;
k=k?e.createCallback(k,c,1):Na;for(h=k(h);b<f;)c=b+f>>>1,k(a[c])<h?b=c+1:f=c;return b}function ib(a){for(var h=-1,k=a?db(Ja(a,"length")):0,c=H(0>k?0:k);++h<k;)c[h]=Ja(a,h);return c}function jb(a,h){for(var k=-1,c=a?a.length:0,b={};++k<c;){var e=a[k];h?b[e]=h[k]:b[e[0]]=e[1]}return b}function Oa(a,h){return kb.fastBind||W&&2<arguments.length?W.call.apply(W,arguments):x(a,h,E.call(arguments,2))}function lb(a,h,k){function c(){ua(l);ua(t);r=0;l=t=null}function b(){var h=s&&(!q||1<r);c();h&&(!1!==n&&
(p=new va),g=a.apply(d,f))}function e(){c();if(s||n!==h)p=new va,g=a.apply(d,f)}var f,g,d,r=0,p=0,n=!1,l=null,t=null,s=!0;h=P(0,h||0);if(!0===k)var q=!0,s=!1;else N(k)&&(q=k.leading,n="maxWait"in k&&P(h,k.maxWait||0),s="trailing"in k?k.trailing:s);return function(){f=arguments;d=this;r++;ua(t);if(!1===n)q&&2>r&&(g=a.apply(d,f));else{var k=new va;l||q||(p=k);var c=n-(k-p);0>=c?(ua(l),l=null,p=k,g=a.apply(d,f)):l||(l=wa(e,c))}h!==n&&(t=wa(b,h));return g}}function mb(a){var h=E.call(arguments,1);return wa(function(){a.apply(r,
h)},1)}function Na(a){return a}function nb(a){C(qa(a),function(h){var k=e[h]=a[h];e.prototype[h]=function(){var a=this.__wrapped__,h=[a];xa.apply(h,arguments);h=k.apply(e,h);return a&&"object"==typeof a&&a===h?this:new s(h)}})}function ob(){return this.__wrapped__}d=d?X.defaults(a.Object(),d,X.pick(a,yb)):a;var H=d.Array,la=d.Boolean,va=d.Date,Pa=d.Function,Q=d.Math,zb=d.Number,ma=d.Object,Qa=d.RegExp,T=d.String,ub=d.TypeError,I=[],Ra=ma.prototype,Ab=d._,ea=Qa("^"+T(Ra.valueOf).replace(/[.*+?^${}()|[\]\\]/g,
"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),Bb=Q.ceil,ua=d.clearTimeout,da=I.concat,pb=Q.floor,Cb=Pa.prototype.toString,na=ea.test(na=ma.getPrototypeOf)&&na,F=Ra.hasOwnProperty,xa=I.push,ya=d.setImmediate,wa=d.setTimeout,G=Ra.toString,W=ea.test(W=G.bind)&&W,pa=ea.test(pa=ma.create)&&pa,Sa=ea.test(Sa=H.isArray)&&Sa,Db=d.isFinite,Eb=d.isNaN,za=ea.test(za=ma.keys)&&za,P=Q.max,ta=Q.min,Ta=d.parseInt,qb=Q.random,E=I.slice,Q=ea.test(d.attachEvent),Q=W&&!/\n|true/.test(W+Q),R={};R[ra]=H;R[fa]=la;R[ga]=
va;R[rb]=Pa;R[V]=ma;R[ha]=zb;R[ia]=Qa;R[ba]=T;s.prototype=e.prototype;var kb=e.support={};kb.fastBind=W&&!Q;e.templateSettings={escape:/<%-([\s\S]+?)%>/g,evaluate:/<%([\s\S]+?)%>/g,interpolate:sb,variable:"",imports:{_:e}};var L=Sa,la=function(a){var h,k=[];if(!a||!J[typeof a])return k;for(h in a)F.call(a,h)&&k.push(h);return k},M=za?function(a){return N(a)?za(a):[]}:la,Xa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},wb=Za(Xa),Ea=function(a,h,k){var c,b=a,f=b;if(!b)return f;var g=
arguments,d=0,r="number"==typeof k?2:g.length;if(3<r&&"function"==typeof g[r-2])var p=e.createCallback(g[--r-1],g[r--],2);else 2<r&&"function"==typeof g[r-1]&&(p=g[--r]);for(;++d<r;)if((b=g[d])&&J[typeof b])for(var l=-1,n=J[typeof b]&&M(b),t=n?n.length:0;++l<t;)c=n[l],f[c]=p?p(f[c],b[c]):b[c];return f},Ua=function(a,h,k){var c,b=a,f=b;if(!b)return f;for(var e=arguments,g=0,d="number"==typeof k?2:e.length;++g<d;)if((b=e[g])&&J[typeof b])for(var r=-1,p=J[typeof b]&&M(b),n=p?p.length:0;++r<n;)c=p[r],
"undefined"==typeof f[c]&&(f[c]=b[c]);return f},Y=function(a,h,k){var c;if(!a||!J[typeof a])return a;h=h&&"undefined"==typeof k?h:e.createCallback(h,k);for(c in a)if(!1===h(a[c],c,a))break;return a},D=function(a,h,k){if(!a||!J[typeof a])return a;h=h&&"undefined"==typeof k?h:e.createCallback(h,k);for(var c=-1,b=J[typeof a]&&M(a),f=b?b.length:0;++c<f&&(k=b[c],!1!==h(a[k],k,a)););return a},Fa=function(a){if(!a||G.call(a)!=V)return!1;var h=a.valueOf,k="function"==typeof h&&(k=na(h))&&na(k);return k?a==
k||na(a)==k:Ca(a)},la=Z(function h(a,c,b){for(var f=-1,e=a?a.length:0,g=[];++f<e;){var d=a[f];b&&(d=b(d,f,a));L(d)?xa.apply(g,c?d:h(d)):g.push(d)}return g}),Va=Z(function(a,c,m){var f=-1,e=K(),g=a?a.length:0,d=[],r=!c&&g>=t&&e===b,s=m||r?u():d;if(r){var q=n(s);q?(e=l,s=q):(r=!1,s=m?s:(w(s),d))}for(;++f<g;){var q=a[f],x=m?m(q,f,a):q;if(c?!f||s[s.length-1]!==x:0>e(s,x))(m||r)&&s.push(x),d.push(q)}r?(w(s.array),p(s)):m&&w(s);return d});Q&&(Wa&&"function"==typeof ya)&&(mb=Oa(ya,d));ya=8==Ta(tb+"08")?
Ta:function(a,c){return Ta(ka(a)?a.replace(Fb,""):a,c||0)};e.after=function(a,c){return 1>a?c():function(){if(1>--a)return c.apply(this,arguments)}};e.assign=Ea;e.at=function(a){for(var c=-1,b=da.apply(I,E.call(arguments,1)),f=b.length,e=H(f);++c<f;)e[c]=a[b[c]];return e};e.bind=Oa;e.bindAll=function(a){for(var c=1<arguments.length?da.apply(I,E.call(arguments,1)):qa(a),b=-1,f=c.length;++b<f;){var e=c[b];a[e]=Oa(a[e],a)}return a};e.bindKey=function(a,c){return x(a,c,E.call(arguments,2),S)};e.compact=
function(a){for(var c=-1,b=a?a.length:0,f=[];++c<b;){var e=a[c];e&&f.push(e)}return f};e.compose=function(){var a=arguments;return function(){for(var c=arguments,b=a.length;b--;)c=[a[b].apply(this,c)];return c[0]}};e.countBy=function(a,c,b){var f={};c=e.createCallback(c,b);C(a,function(a,h,b){h=T(c(a,h,b));F.call(f,h)?f[h]++:f[h]=1});return f};e.createCallback=function(a,c,b){if(null==a)return Na;var f=typeof a;if("function"!=f){if("object"!=f)return function(c){return c[a]};var e=M(a);return function(c){for(var k=
e.length,b=!1;k--&&(b=ca(c[e[k]],a[e[k]],S)););return b}}return"undefined"==typeof c||oa&&!oa.test(Cb.call(a))?a:1===b?function(b){return a.call(c,b)}:2===b?function(b,f){return a.call(c,b,f)}:4===b?function(b,f,e,m){return a.call(c,b,f,e,m)}:function(b,f,e){return a.call(c,b,f,e)}};e.debounce=lb;e.defaults=Ua;e.defer=mb;e.delay=function(a,c){var b=E.call(arguments,2);return wa(function(){a.apply(r,b)},c)};e.difference=gb;e.filter=sa;e.flatten=la;e.forEach=C;e.forIn=Y;e.forOwn=D;e.functions=qa;e.groupBy=
function(a,c,b){var f={};c=e.createCallback(c,b);C(a,function(a,h,b){h=T(c(a,h,b));(F.call(f,h)?f[h]:f[h]=[]).push(a)});return f};e.initial=function(a,b,f){if(!a)return[];var g=0,d=a.length;if("number"!=typeof b&&null!=b){var r=d;for(b=e.createCallback(b,f);r--&&b(a[r],r,a);)g++}else g=null==b||f?1:b||g;return c(a,0,ta(P(0,d-g),d))};e.intersection=function(a){for(var c=arguments,f=c.length,e=-1,g=u(),d=-1,r=K(),s=a?a.length:0,q=[],x=u();++e<f;){var z=c[e];g[e]=r===b&&(z?z.length:0)>=t&&n(e?c[e]:x)}a:for(;++d<
s;){var v=g[0],z=a[d];if(0>(v?l(v,z):r(x,z))){e=f;for((v||x).push(z);--e;)if(v=g[e],0>(v?l(v,z):r(c[e],z)))continue a;q.push(z)}}for(;f--;)(v=g[f])&&p(v);w(g);w(x);return q};e.invert=Za;e.invoke=function(a,c){var b=E.call(arguments,2),f=-1,e="function"==typeof c,g=a?a.length:0,d=H("number"==typeof g?g:0);C(a,function(a){d[++f]=(e?c:a[c]).apply(a,b)});return d};e.keys=M;e.map=Ia;e.max=db;e.memoize=function(a,c){function b(){var f=b.cache,e=$+(c?c.apply(this,arguments):arguments[0]);return F.call(f,
e)?f[e]:f[e]=a.apply(this,arguments)}b.cache={};return b};e.merge=ab;e.min=function(a,c,b){var f=Infinity,d=f;if(!c&&L(a)){b=-1;for(var r=a.length;++b<r;){var p=a[b];p<d&&(d=p)}}else c=!c&&ka(a)?g:e.createCallback(c,b),C(a,function(a,h,b){h=c(a,h,b);h<f&&(f=h,d=a)});return d};e.omit=function(a,c,b){var f=K(),g="function"==typeof c,d={};if(g)c=e.createCallback(c,b);else var r=da.apply(I,E.call(arguments,1));Y(a,function(a,h,b){if(g?!c(a,h,b):0>f(r,h))d[h]=a});return d};e.once=function(a){var c,b;return function(){if(c)return b;
c=!0;b=a.apply(this,arguments);a=null;return b}};e.pairs=function(a){for(var c=-1,b=M(a),f=b.length,e=H(f);++c<f;){var g=b[c];e[c]=[g,a[g]]}return e};e.partial=function(a){return x(a,E.call(arguments,1))};e.partialRight=function(a){return x(a,E.call(arguments,1),null,S)};e.pick=function(a,c,b){var f={};if("function"!=typeof c)for(var g=-1,d=da.apply(I,E.call(arguments,1)),r=N(a)?d.length:0;++g<r;){var p=d[g];p in a&&(f[p]=a[p])}else c=e.createCallback(c,b),Y(a,function(a,h,b){c(a,h,b)&&(f[h]=a)});
return f};e.pluck=Ja;e.range=function(a,c,b){a=+a||0;b=+b||1;null==c&&(c=a,a=0);var f=-1;c=P(0,Bb((c-a)/b));for(var e=H(c);++f<c;)e[f]=a,a+=b;return e};e.reject=function(a,c,b){c=e.createCallback(c,b);return sa(a,function(a,b,h){return!c(a,b,h)})};e.rest=Ma;e.shuffle=function(a){var c=-1,b=a?a.length:0,f=H("number"==typeof b?b:0);C(a,function(a){var b=pb(qb()*(++c+1));f[c]=f[b];f[b]=a});return f};e.sortBy=function(a,c,b){var f=-1,g=a?a.length:0,d=H("number"==typeof g?g:0);c=e.createCallback(c,b);
C(a,function(a,b,h){var e=d[++f]=v();e.criteria=c(a,b,h);e.index=f;e.value=a});g=d.length;for(d.sort(q);g--;)a=d[g],d[g]=a.value,p(a);return d};e.tap=function(a,c){c(a);return a};e.throttle=function(a,c,b){var f=!0,e=!0;!1===b?f=!1:N(b)&&(f="leading"in b?b.leading:f,e="trailing"in b?b.trailing:e);b=v();b.leading=f;b.maxWait=c;b.trailing=e;a=lb(a,c,b);p(b);return a};e.times=function(a,c,b){a=-1<(a=+a)?a:0;var f=-1,g=H(a);for(c=e.createCallback(c,b,1);++f<a;)g[f]=c(f);return g};e.toArray=function(a){return a&&
"number"==typeof a.length?c(a):Ga(a)};e.transform=function(a,c,b,f){var g=L(a);c=e.createCallback(c,f,4);null==b&&(g?b=[]:(f=(f=a&&a.constructor)&&f.prototype,b=N(f)?pa(f):{}));(g?C:D)(a,function(a,h,f){return c(b,a,h,f)});return b};e.union=function(a){L(a)||(arguments[0]=a?E.call(a):I);return Va(da.apply(I,arguments))};e.uniq=Va;e.unzip=ib;e.values=Ga;e.where=sa;e.without=function(a){return gb(a,E.call(arguments,1))};e.wrap=function(a,c){return function(){var b=[a];xa.apply(b,arguments);return c.apply(this,
b)}};e.zip=function(a){return a?ib(arguments):[]};e.zipObject=jb;e.collect=Ia;e.drop=Ma;e.each=C;e.extend=Ea;e.methods=qa;e.object=jb;e.select=sa;e.tail=Ma;e.unique=Va;nb(e);e.chain=e;e.prototype.chain=function(){return this};e.clone=Da;e.cloneDeep=function(a,c,b){return Da(a,!0,c,b)};e.contains=bb;e.escape=function(a){return null==a?"":T(a).replace(Gb,z)};e.every=cb;e.find=Ha;e.findIndex=function(a,c,b){var f=-1,g=a?a.length:0;for(c=e.createCallback(c,b);++f<g;)if(c(a[f],f,a))return f;return-1};
e.findKey=function(a,c,b){var f;c=e.createCallback(c,b);D(a,function(a,b,h){if(c(a,b,h))return f=b,!1});return f};e.has=function(a,c){return a?F.call(a,c):!1};e.identity=Na;e.indexOf=Ya;e.isArguments=function(a){return G.call(a)==ja};e.isArray=L;e.isBoolean=function(a){return!0===a||!1===a||G.call(a)==fa};e.isDate=function(a){return a?"object"==typeof a&&G.call(a)==ga:!1};e.isElement=function(a){return a?1===a.nodeType:!1};e.isEmpty=function(a){var c=!0;if(!a)return c;var b=G.call(a),f=a.length;if(b==
ra||(b==ba||b==ja)||b==V&&"number"==typeof f&&U(a.splice))return!f;D(a,function(){return c=!1});return c};e.isEqual=ca;e.isFinite=function(a){return Db(a)&&!Eb(parseFloat(a))};e.isFunction=U;e.isNaN=function(a){return $a(a)&&a!=+a};e.isNull=function(a){return null===a};e.isNumber=$a;e.isObject=N;e.isPlainObject=Fa;e.isRegExp=function(a){return a?"object"==typeof a&&G.call(a)==ia:!1};e.isString=ka;e.isUndefined=function(a){return"undefined"==typeof a};e.lastIndexOf=function(a,c,b){var f=a?a.length:
0;for("number"==typeof b&&(f=(0>b?P(0,f+b):ta(b,f-1))+1);f--;)if(a[f]===c)return f;return-1};e.mixin=nb;e.noConflict=function(){d._=Ab;return this};e.parseInt=ya;e.random=function(a,c){null==a&&null==c&&(c=1);a=+a||0;null==c?(c=a,a=0):c=+c||0;var b=qb();return a%1||c%1?a+ta(b*(c-a+parseFloat("1e-"+((b+"").length-1))),c):a+pb(b*(c-a+1))};e.reduce=Ka;e.reduceRight=eb;e.result=function(a,c){var b=a?a[c]:r;return U(b)?a[c]():b};e.runInContext=f;e.size=function(a){var c=a?a.length:0;return"number"==typeof c?
c:M(a).length};e.some=fb;e.sortedIndex=hb;e.template=function(a,c,b){var f=e.templateSettings;a||(a="");b=Ua({},b,f);var g=Ua({},b.imports,f.imports),f=M(g),g=Ga(g),d,p=0,n=b.interpolate||Aa,l="__p += '",n=Qa((b.escape||Aa).source+"|"+n.source+"|"+(n===sb?Hb:Aa).source+"|"+(b.evaluate||Aa).source+"|$","g");a.replace(n,function(c,b,f,e,k,g){f||(f=e);l+=a.slice(p,g).replace(Ib,A);b&&(l+="' +\n__e("+b+") +\n'");k&&(d=!0,l+="';\n"+k+";\n__p += '");f&&(l+="' +\n((__t = ("+f+")) == null ? '' : __t) +\n'");
p=g+c.length;return c});var l=l+"';\n",s=n=b.variable;s||(n="obj",l="with ("+n+") {\n"+l+"\n}\n");l=(d?l.replace(Jb,""):l).replace(Kb,"$1").replace(Lb,"$1;");l="function("+n+") {\n"+(s?"":n+" || ("+n+" = {});\n")+"var __t, __p = '', __e = _.escape"+(d?", __j = Array.prototype.join;\nfunction print() { __p += __j.call(arguments, '') }\n":";\n")+l+"return __p\n}";b="\n/*\n//@ sourceURL="+(b.sourceURL||"/lodash/template/source["+Mb++ +"]")+"\n*/";try{var t=Pa(f,"return "+l+b).apply(r,g)}catch(q){throw q.source=
l,q;}if(c)return t(c);t.source=l;return t};e.unescape=function(a){return null==a?"":T(a).replace(Nb,vb)};e.uniqueId=function(a){var c=++Ba;return T(null==a?"":a)+c};e.all=cb;e.any=fb;e.detect=Ha;e.findWhere=Ha;e.foldl=Ka;e.foldr=eb;e.include=bb;e.inject=Ka;D(e,function(a,c){e.prototype[c]||(e.prototype[c]=function(){var c=[this.__wrapped__];xa.apply(c,arguments);return a.apply(e,c)})});e.first=La;e.last=function(a,b,f){if(a){var g=0,d=a.length;if("number"!=typeof b&&null!=b){var r=d;for(b=e.createCallback(b,
f);r--&&b(a[r],r,a);)g++}else if(g=b,null==g||f)return a[d-1];return c(a,P(0,d-g))}};e.take=La;e.head=La;D(e,function(a,c){e.prototype[c]||(e.prototype[c]=function(c,b){var f=a(this.__wrapped__,c,b);return null==c||b&&"function"!=typeof c?f:new s(f)})});e.VERSION="1.3.1";e.prototype.toString=function(){return T(this.__wrapped__)};e.prototype.value=ob;e.prototype.valueOf=ob;C(["join","pop","shift"],function(a){var c=I[a];e.prototype[a]=function(){return c.apply(this.__wrapped__,arguments)}});C(["push",
"reverse","sort","unshift"],function(a){var c=I[a];e.prototype[a]=function(){c.apply(this.__wrapped__,arguments);return this}});C(["concat","slice","splice"],function(a){var c=I[a];e.prototype[a]=function(){return new s(c.apply(this.__wrapped__,arguments))}});return e}var r,s=[],z=[],Ba=0,S={},$=+new Date+"",t=75,x=40,Jb=/\b__p \+= '';/g,Kb=/\b(__p \+=) '' \+/g,Lb=/(__e\(.*?\)|\b__t\)) \+\n'';/g,Nb=/&(?:amp|lt|gt|quot|#39);/g,Hb=/\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g,xb=/\w*$/,sb=/<%=([\s\S]+?)%>/g,oa=
(oa=/\bthis\b/)&&oa.test(f)&&oa,tb=" \t\x0B\f\u00a0\ufeff\n\r\u2028\u2029\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000",Fb=RegExp("^["+tb+"]*0+(?=.$)"),Aa=/($^)/,Gb=/[&<>"']/g,Ib=/['\n\r\t\u2028\u2029\\]/g,yb="Array Boolean Date Function Math Number Object RegExp String _ attachEvent clearTimeout isFinite isNaN parseInt setImmediate setTimeout".split(" "),Mb=0,ja="[object Arguments]",ra="[object Array]",fa="[object Boolean]",ga="[object Date]",rb=
"[object Function]",ha="[object Number]",V="[object Object]",ia="[object RegExp]",ba="[object String]",O={};O[rb]=!1;O[ja]=O[ra]=O[fa]=O[ga]=O[ha]=O[V]=O[ia]=O[ba]=!0;var J={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1},Ca={"\\":"\\","'":"'","\n":"n","\r":"r","\t":"t","\u2028":"u2028","\u2029":"u2029"},Z=J[typeof exports]&&exports,Wa=J[typeof module]&&module&&module.exports==Z&&module,K=J[typeof global]&&global;!K||K.global!==K&&K.window!==K||(a=K);var X=f();"function"==typeof define&&
"object"==typeof define.amd&&define.amd?(a._=X,define(function(){return X})):Z&&!Z.nodeType?Wa?(Wa.exports=X)._=X:Z._=X:a._=X})(this);!function(){function a(a){this.s=null!==a&&void 0!==a?"string"===typeof a?a:a.toString():a;this.orig=a;null!==a&&void 0!==a?this.__defineGetter__?this.__defineGetter__("length",function(){return this.s.length}):this.length=a.length:this.length=-1}function b(c){return new a(c)}function l(a,b){var g=[],d;for(d=0;d<a.length;d++)g.push(a[d]),b&&b.call(a,a[d],d);return g}var d={},g=String.prototype,q=a.prototype={between:function(c,b){var g=this.s,d=g.indexOf(c),p=g.indexOf(b),l=d+c.length;return new a(p>
d?g.slice(l,p):"")},camelize:function(){var c=this.trim().s.replace(/(\-|_|\s)+(.)?/g,function(a,c,b){return b?b.toUpperCase():""});return new a(c)},capitalize:function(){return new a(this.s.substr(0,1).toUpperCase()+this.s.substring(1).toLowerCase())},charAt:function(a){return this.s.charAt(a)},chompLeft:function(c){var b=this.s;return 0===b.indexOf(c)?(b=b.slice(c.length),new a(b)):this},chompRight:function(c){if(this.endsWith(c)){var b=this.s,b=b.slice(0,b.length-c.length);return new a(b)}return this},
collapseWhitespace:function(){var c=this.s.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"");return new a(c)},contains:function(a){return 0<=this.s.indexOf(a)},count:function(a){for(var b=0,g=this.s.indexOf(a);0<=g;)b+=1,g=this.s.indexOf(a,g+1);return b},dasherize:function(){var c=this.trim().s.replace(/[_\s]+/g,"-").replace(/([A-Z])/g,"-$1").replace(/-+/g,"-").toLowerCase();return new a(c)},decodeHtmlEntities:function(){var c=this.s,c=c.replace(/&#(\d+);?/g,function(a,c){return String.fromCharCode(c)}).replace(/&#[xX]([A-Fa-f0-9]+);?/g,
function(a,c){return String.fromCharCode(parseInt(c,16))}).replace(/&([^;\W]+;?)/g,function(a,c){var b=c.replace(/;$/,""),b=d[c]||c.match(/;$/)&&d[b];return"number"===typeof b?String.fromCharCode(b):"string"===typeof b?b:a});return new a(c)},endsWith:function(a){var b=this.s.length-a.length;return 0<=b&&this.s.indexOf(a,b)===b},escapeHTML:function(){return new a(this.s.replace(/[&<>"']/g,function(a){return"&"+w[a]+";"}))},ensureLeft:function(c){var b=this.s;return 0===b.indexOf(c)?this:new a(c+b)},
ensureRight:function(c){var b=this.s;return this.endsWith(c)?this:new a(b+c)},humanize:function(){if(null===this.s||void 0===this.s)return new a("");var c=this.underscore().replace(/_id$/,"").replace(/_/g," ").trim().capitalize();return new a(c)},isAlpha:function(){return!/[^a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isAlphaNumeric:function(){return!/[^0-9a-z\xC0-\xFF]/.test(this.s.toLowerCase())},isEmpty:function(){return null===this.s||void 0===this.s?!0:/^[\s\xa0]*$/.test(this.s)},isLower:function(){return this.isAlpha()&&
this.s.toLowerCase()===this.s},isNumeric:function(){return!/[^0-9]/.test(this.s)},isUpper:function(){return this.isAlpha()&&this.s.toUpperCase()===this.s},left:function(c){return 0<=c?(c=this.s.substr(0,c),new a(c)):this.right(-c)},lines:function(){return this.replaceAll("\r\n","\n").s.split("\n")},pad:function(c,b){b=b||" ";if(this.s.length>=c)return new a(this.s);c-=this.s.length;var g=Array(Math.ceil(c/2)+1).join(b),d=Array(Math.floor(c/2)+1).join(b);return new a(g+this.s+d)},padLeft:function(c,
b){b=b||" ";return this.s.length>=c?new a(this.s):new a(Array(c-this.s.length+1).join(b)+this.s)},padRight:function(c,b){b=b||" ";return this.s.length>=c?new a(this.s):new a(this.s+Array(c-this.s.length+1).join(b))},parseCSV:function(a,b,g,d){a=a||",";g=g||"\\";"undefined"==typeof b&&(b='"');var p=0,l=[],n=[],q=this.s.length,t=!1;if("undefined"!==typeof d)var x=[];for(b||(t=!0);p<q;){var u=this.s.charAt(p);switch(u){case g:if(t&&(g!==b||this.s.charAt(p+1)===b)){p+=1;l.push(this.s.charAt(p));break}if(g!==
b)break;case b:t=!t;break;case a:t&&b?l.push(u):(n.push(l.join("")),l.length=0);break;case d:t?l.push(u):x&&(n.push(l.join("")),x.push(n),n=[],l.length=0);break;default:t&&l.push(u)}p+=1}n.push(l.join(""));return x?(x.push(n),x):n},replaceAll:function(b,f){var g=this.s.split(b).join(f);return new a(g)},right:function(b){return 0<=b?(b=this.s.substr(this.s.length-b,b),new a(b)):this.left(-b)},slugify:function(){var b=(new a(this.s.replace(/[^\w\s-]/g,"").toLowerCase())).dasherize().s;"-"===b.charAt(0)&&
(b=b.substr(1));return new a(b)},startsWith:function(a){return 0===this.s.lastIndexOf(a,0)},stripPunctuation:function(){return new a(this.s.replace(/[^\w\s]|_/g,"").replace(/\s+/g," "))},stripTags:function(){var b=this.s;l(0<arguments.length?arguments:[""],function(a){b=b.replace(RegExp("</?"+a+"[^<>]*>","gi"),"")});return new a(b)},template:function(c,f,g){var d=this.s;f=f||b.TMPL_OPEN;g=g||b.TMPL_CLOSE;(d.match(RegExp(f+"(.+?)"+g,"g"))||[]).forEach(function(a){var b=a.substring(f.length,a.length-
g.length);c[b]&&(d=d.replace(a,c[b]))});return new a(d)},times:function(b){return new a(Array(b+1).join(this.s))},toBoolean:function(){if("string"===typeof this.orig){var a=this.s.toLowerCase();return"true"===a||"yes"===a||"on"===a}return!0===this.orig||1===this.orig},toFloat:function(a){var b=parseFloat(this.s);return a?parseFloat(b.toFixed(a)):b},toInt:function(){return/^\s*-?0x/i.test(this.s)?parseInt(this.s,16):parseInt(this.s,10)},trim:function(){var b;b="undefined"===typeof g.trim?this.s.replace(/(^\s*|\s*$)/g,
""):this.s.trim();return new a(b)},trimLeft:function(){var b;b=g.trimLeft?this.s.trimLeft():this.s.replace(/(^\s*)/g,"");return new a(b)},trimRight:function(){var b;b=g.trimRight?this.s.trimRight():this.s.replace(/\s+$/,"");return new a(b)},truncate:function(b,f){var g=this.s;b=~~b;f=f||"...";if(g.length<=b)return new a(g);var d=g.slice(0,b+1).replace(/.(?=\W*\w*$)/g,function(a){return a.toUpperCase()!==a.toLowerCase()?"A":" "}),d=d.slice(d.length-2).match(/\w\w/)?d.replace(/\s*\S+$/,""):(new a(d.slice(0,
d.length-1))).trimRight().s;return(d+f).length>g.length?new a(g):new a(g.slice(0,d.length)+f)},toCSV:function(b,f){var g=",",d='"',p="\\",l=!0,n=!1,q=[];"object"===typeof b?(g=b.delimiter||g,g=b.separator||g,d=b.qualifier||d,l=!!b.encloseNumbers,p=b.escape||p,n=!!b.keys):"string"===typeof b&&(g=b);"string"===typeof f&&(d=f);null===f&&(d=null);if(this.orig instanceof Array)q=this.orig;else for(var t in this.orig)this.orig.hasOwnProperty(t)&&(n?q.push(t):q.push(this.orig[t]));p+=d;n=[];for(t=0;t<q.length;++t){var x=
null!==d&&""!==d;"number"==typeof q[t]&&(x&=l);x&&n.push(d);if(null!==q[t]&&void 0!==q[t]){var u=(new a(q[t])).replaceAll(d,p).s;n.push(u)}else n.push("");x&&n.push(d);g&&n.push(g)}n.length-=1;return new a(n.join(""))},toString:function(){return this.s},underscore:function(){var b=this.trim().s.replace(/([a-z\d])([A-Z]+)/g,"$1_$2").replace(/[-\s]+/g,"_").toLowerCase();(new a(this.s.charAt(0))).isUpper()&&(b="_"+b);return new a(b)},unescapeHTML:function(){return new a(this.s.replace(/\&([^;]+);/g,
function(a,b){var g;return b in v?v[b]:(g=b.match(/^#x([\da-fA-F]+)$/))?String.fromCharCode(parseInt(g[1],16)):(g=b.match(/^#(\d+)$/))?String.fromCharCode(~~g[1]):a}))},valueOf:function(){return this.s.valueOf()}},n=[],A=function(){var a;a=[];if(Object.getOwnPropertyNames)a=Object.getOwnPropertyNames(g),a.splice(a.indexOf("valueOf"),1),a.splice(a.indexOf("toString"),1);else{var b={},d;for(d in String.prototype)b[d]=d;for(d in Object.prototype)delete b[d];for(d in b)a.push(d)}b={};for(d=0;d<a.length;++d){var p=
a[d],l=g[p];try{var n=typeof l.apply("teststring",[]);b[p]=n}catch(q){}}return b}(),u;for(u in A)(function(b){var f=g[b];"function"==typeof f&&(q[b]||(q[b]="string"===A[b]?function(){return new a(f.apply(this,arguments))}:f))})(u);q.repeat=q.times;q.include=q.contains;q.toInteger=q.toInt;q.toBool=q.toBoolean;q.decodeHTMLEntities=q.decodeHtmlEntities;b.extendPrototype=function(){for(var a in q)(function(a){var b=q[a];g.hasOwnProperty(a)||(n.push(a),g[a]=function(){String.prototype.s=this;return b.apply(this,
arguments)})})(a)};b.restorePrototype=function(){for(var a=0;a<n.length;++a)delete String.prototype[n[a]];n.length=0};b.VERSION="1.5.0";b.TMPL_OPEN="{{";b.TMPL_CLOSE="}}";b.ENTITIES=d;"undefined"!==typeof module&&"undefined"!==typeof module.exports?module.exports=b:"function"===typeof define&&define.amd?define([],function(){return b}):window.S=b;var v={lt:"<",gt:">",quot:'"',apos:"'",amp:"&"},w={},p;for(p in v)w[v[p]]=p;d={amp:"&",gt:">",lt:"<",quot:'"',apos:"'",AElig:198,Aacute:193,Acirc:194,Agrave:192,
Aring:197,Atilde:195,Auml:196,Ccedil:199,ETH:208,Eacute:201,Ecirc:202,Egrave:200,Euml:203,Iacute:205,Icirc:206,Igrave:204,Iuml:207,Ntilde:209,Oacute:211,Ocirc:212,Ograve:210,Oslash:216,Otilde:213,Ouml:214,THORN:222,Uacute:218,Ucirc:219,Ugrave:217,Uuml:220,Yacute:221,aacute:225,acirc:226,aelig:230,agrave:224,aring:229,atilde:227,auml:228,ccedil:231,eacute:233,ecirc:234,egrave:232,eth:240,euml:235,iacute:237,icirc:238,igrave:236,iuml:239,ntilde:241,oacute:243,ocirc:244,ograve:242,oslash:248,otilde:245,
ouml:246,szlig:223,thorn:254,uacute:250,ucirc:251,ugrave:249,uuml:252,yacute:253,yuml:255,copy:169,reg:174,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,ordf:170,laquo:171,not:172,shy:173,macr:175,deg:176,plusmn:177,sup1:185,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,ordm:186,raquo:187,frac14:188,frac12:189,frac34:190,iquest:191,times:215,divide:247,"OElig;":338,"oelig;":339,"Scaron;":352,"scaron;":353,"Yuml;":376,"fnof;":402,"circ;":710,
"tilde;":732,"Alpha;":913,"Beta;":914,"Gamma;":915,"Delta;":916,"Epsilon;":917,"Zeta;":918,"Eta;":919,"Theta;":920,"Iota;":921,"Kappa;":922,"Lambda;":923,"Mu;":924,"Nu;":925,"Xi;":926,"Omicron;":927,"Pi;":928,"Rho;":929,"Sigma;":931,"Tau;":932,"Upsilon;":933,"Phi;":934,"Chi;":935,"Psi;":936,"Omega;":937,"alpha;":945,"beta;":946,"gamma;":947,"delta;":948,"epsilon;":949,"zeta;":950,"eta;":951,"theta;":952,"iota;":953,"kappa;":954,"lambda;":955,"mu;":956,"nu;":957,"xi;":958,"omicron;":959,"pi;":960,
"rho;":961,"sigmaf;":962,"sigma;":963,"tau;":964,"upsilon;":965,"phi;":966,"chi;":967,"psi;":968,"omega;":969,"thetasym;":977,"upsih;":978,"piv;":982,"ensp;":8194,"emsp;":8195,"thinsp;":8201,"zwnj;":8204,"zwj;":8205,"lrm;":8206,"rlm;":8207,"ndash;":8211,"mdash;":8212,"lsquo;":8216,"rsquo;":8217,"sbquo;":8218,"ldquo;":8220,"rdquo;":8221,"bdquo;":8222,"dagger;":8224,"Dagger;":8225,"bull;":8226,"hellip;":8230,"permil;":8240,"prime;":8242,"Prime;":8243,"lsaquo;":8249,"rsaquo;":8250,"oline;":8254,"frasl;":8260,
"euro;":8364,"image;":8465,"weierp;":8472,"real;":8476,"trade;":8482,"alefsym;":8501,"larr;":8592,"uarr;":8593,"rarr;":8594,"darr;":8595,"harr;":8596,"crarr;":8629,"lArr;":8656,"uArr;":8657,"rArr;":8658,"dArr;":8659,"hArr;":8660,"forall;":8704,"part;":8706,"exist;":8707,"empty;":8709,"nabla;":8711,"isin;":8712,"notin;":8713,"ni;":8715,"prod;":8719,"sum;":8721,"minus;":8722,"lowast;":8727,"radic;":8730,"prop;":8733,"infin;":8734,"ang;":8736,"and;":8743,"or;":8744,"cap;":8745,"cup;":8746,"int;":8747,
"there4;":8756,"sim;":8764,"cong;":8773,"asymp;":8776,"ne;":8800,"equiv;":8801,"le;":8804,"ge;":8805,"sub;":8834,"sup;":8835,"nsub;":8836,"sube;":8838,"supe;":8839,"oplus;":8853,"otimes;":8855,"perp;":8869,"sdot;":8901,"lceil;":8968,"rceil;":8969,"lfloor;":8970,"rfloor;":8971,"lang;":9001,"rang;":9002,"loz;":9674,"spades;":9824,"clubs;":9827,"hearts;":9829,"diams;":9830}}.call(this);(function(){this.H={Check:{},TennisScoreKeeper:{}}}).call(this);(function(a){function b(b){return b===a||null===b}function l(a){this.isBetweenInclusive=function(b,d){return a>=b&&a<=d};this.isBetweenExclusive=function(b,d){return a>b&&a<d}}function d(a,b){var l=typeof a,A=typeof b;if(null===a&&null===b)return!0;if(l!==A)return!1;if("object"!==l&&"object"!==A)return a==b;var l=!0,u;for(u in a)if("function"!==typeof a[u]&&(l=l&&d(a[u],b[u]),!l))return!1;return!0}this.notEmpty=function(b,d){if(b===a||null===b)throw Error("Parameter '"+d+"' cannot be null or undefined");
};this.condition=function(a,b){if(!a)throw Error(b||"An error occured");};this.isEmpty=b;this.isNotEmpty=function(a){return!b(a)};this.areSame=d;this.value=function(a){return new l(a)}}).call(this.H.Check);(function(a,b,l){function d(b,c,f){a.condition("15b6d1fc81a043c081242617308b4fdc"===f,"GameTieMode must not be instantiated. Use TieMode enum.");a.notEmpty(b,"id");a.notEmpty(c,"pointByDifferenceFunc");a.condition("function"===typeof c,"pointByDifferenceFunc must be a function returning tennisPoint via point difference");this.PointByDifference=function(a){return c.call(null,a)};this.id=b}function g(b){a.notEmpty(b,"label");this.label=b;this.id=n(b)}function q(b,c,f,d){a.condition("82ee546ae51f4a77a048186fa13e98f1"===
d,"PointType must not be instantiated. Use PointTypes enum.");a.notEmpty(c,"label");a.notEmpty(f,"shotStyle");a.condition(b===w.PointWinner||b===w.PointLoser,"Point credit goes to winner or loser. Use pointCreditTypes enum");this.label=c;this.creditTo=b;this.shotStyle=f;this.id=n(c)}function n(a){return b(a).trim().replaceAll(" ","").replaceAll("/","").s}var A={Love:{id:"Love",code:"0"},Fifteen:{id:"Fifteen",code:"15"},Thirty:{id:"Thirty",code:"30"},Fourty:{id:"Fourty",code:"40"},Advantage:{id:"Advantage",
code:"Ad"}},u={advantageWin:new d("AdvantageWin",function(b){a.condition(a.value(b).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return a.value(b).isBetweenInclusive(-1,0)?A.Fourty:1===b?A.Advantage:A.Love},"15b6d1fc81a043c081242617308b4fdc"),singlePointWin:new d("SinglePointWin",function(b){a.condition(a.value(b).isBetweenInclusive(-1,1),"Something is wrong, point difference must be [-1,1]");return 0===b?A.Fourty:A.Love},"15b6d1fc81a043c081242617308b4fdc")},v={tiebreak:{id:"TieBreak",
minimumGamePoints:7},superTiebreak:{id:"SuperTieBreak",minimumGamePoints:10},gameDifference:{id:"GameDifference",minimumGamePoints:4}};l={NormalPassing:new g("Normal/Passing"),Volley:new g("Volley"),Smash:new g("Smash"),Lob:new g("Lob"),Drop:new g("Drop")};var w={PointWinner:0,PointLoser:1};this.Model={Player:function(b){a.notEmpty(b,"name");var c=this;this.name=b;this.id=n(b);this.setName=function(a){c.name=a;c.id=n(a)}},MatchDefinition:function(b,c,f){a.notEmpty(b,"playerOne");a.notEmpty(c,"playerTwo");
this.players=[b,c];this.gamesPerSet=6;this.setsCount=3;this.gameTieMode=u.advantageWin;this.lastSetTieMode=v.tiebreak;this.startingPlayer=f?c:b},TieMode:u,LastSetTieMode:v,Point:function(b,c,f,d){a.notEmpty(b,"forPlayer");a.notEmpty(c,"creditedTo");a.notEmpty(f,"type");this.player=b;this.creditedTo=c;this.timestamp=new Date;this.type=f;this.isOnSecondServe=d},ShotStyles:l,PointCreditTypes:w,PointTypes:{WinningShot:function(a){return new q(w.PointWinner,"Winning Shot",a,"82ee546ae51f4a77a048186fa13e98f1")},
ForcedError:function(a){return new q(w.PointWinner,"Forced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},UnforcedError:function(a){return new q(w.PointLoser,"Unforced Error",a,"82ee546ae51f4a77a048186fa13e98f1")},Ace:function(a){return new q(w.PointWinner,"Ace",a,"82ee546ae51f4a77a048186fa13e98f1")},DoubleFault:function(a){return new q(w.PointLoser,"Double Fault",a,"82ee546ae51f4a77a048186fa13e98f1")}},PointType:q,TennisPoints:A}}).call(this.H.TennisScoreKeeper,this.H.Check,this.S);(function(a,b,l){function d(d){a.notEmpty(d,"player");this.Player=d;this.Game=b.TennisPoints.Love;this.Sets=this.Games=this.GamePoints=0}function g(b,d,g,l){a.notEmpty(b,"playerOneScoreProjection");a.notEmpty(d,"playerTwoScoreProjection");a.notEmpty(g,"setsPerMatch");a.notEmpty(l,"servingPlayer");var q=this,p=Math.ceil(g/2);this.PlayerOne=b;this.PlayerTwo=d;this.Winner=function(){return b.Sets===p?b:d.Sets===p?d:null};this.IsWon=function(){return null!==q.Winner()};this.ServingPlayer=function(){return l}}
var q=[b.TennisPoints.Love,b.TennisPoints.Fifteen,b.TennisPoints.Thirty,b.TennisPoints.Fourty];this.ScoreProjector=function(n,A){function u(b){a.notEmpty(b,"points");var c=new d(n.players[0]),f=new d(n.players[1]);z=n.startingPlayer;$=b;for(var l=0;l<b.length;l++){var p=b[l];S=p;p.player===c.Player?v(c,f):v(f,c)}b=new g(c,f,n.setsCount,z);b.IsWon()&&r("raiseOnMatchWon",[new s(c,f,"22eb1d7990b640aab2c47aa9ba18572f")]);return b}function v(d,g){d.GamePoints++;r("raiseOnPointWon",[new s(d,g,"22eb1d7990b640aab2c47aa9ba18572f")]);
if(f(d,g))Ba=z,0!==(d.GamePoints+g.GamePoints)%2&&p(),2<=d.GamePoints-g.GamePoints&&d.GamePoints>=(d.Sets!==g.Sets||d.Sets!==Math.floor(n.setsCount/2)?7:n.lastSetTieMode.minimumGamePoints)&&(z=Ba===d.Player?g.Player:d.Player,w(d,g),c(d,g));else if(3>=d.GamePoints)d.Game=q[d.GamePoints];else if(a.value(d.GamePoints-g.GamePoints).isBetweenInclusive(-1,1)){var l=d.GamePoints-g.GamePoints;d.Game=n.gameTieMode.PointByDifference(l);g.Game=n.gameTieMode.PointByDifference(-l);0<l&&(d.Game==b.TennisPoints.Love&&
g.Game==b.TennisPoints.Love)&&w(d,g)}else w(d,g)}function w(a,d){r("raiseOnGameWon",[new s(a,d,"22eb1d7990b640aab2c47aa9ba18572f")]);a.Game=b.TennisPoints.Love;d.Game=b.TennisPoints.Love;a.GamePoints=0;d.GamePoints=0;a.Games++;p();2<=a.Games-d.Games&&a.Games>=n.gamesPerSet&&c(a,d)}function p(){z=z===n.players[0]?n.players[1]:n.players[0]}function c(a,b){r("raiseOnSetWon",[new s(a,b,"22eb1d7990b640aab2c47aa9ba18572f")]);a.Games=0;b.Games=0;a.Sets++}function f(a,c){var d=a.Games===n.gamesPerSet&&c.Games===
n.gamesPerSet;return a.Sets!==c.Sets||a.Sets!==Math.floor(n.setsCount/2)?d:d&&n.lastSetTieMode!==b.LastSetTieMode.gameDifference}function r(a,b){A&&A[a].apply(l,b)}function s(b,c,d){a.condition("22eb1d7990b640aab2c47aa9ba18572f"===d,"HookArgs must not be instantiated. They are exposed for intellisense");this.WinningPlayer=b.Player;this.WinningGamePoints=b.GamePoints;this.LosingPlayer=c.Player;this.LosingGamePoints=c.GamePoints;this.ServingPlayer=z;this.IsTiebreak=f(b,c);this.DecidingPoint=S;this.AllPoints=
$}a.notEmpty(n,"gameDefinition");var z=n.startingPlayer,Ba=null,S=null,$=[];this.processPoints=this.toTennisScore=u;this.HookArgs=s};this.ScoreProjectorHooks=function(a,b,d,g){function q(a,b){"function"===typeof a&&a.apply(l,b)}var p=this;this.onPointWon=a;this.onGameWon=b;this.onSetWon=d;this.onMatchWon=g;this.raiseOnPointWon=function(){q(p.onPointWon,arguments)};this.raiseOnGameWon=function(){q(p.onGameWon,arguments)};this.raiseOnSetWon=function(){q(p.onSetWon,arguments)};this.raiseOnMatchWon=function(){q(p.onMatchWon,
arguments)}}}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model);(function(a,b,l){function d(){var a=this;this.Points=[];this.Games=[];this.Sets=[];this.SetsScore=0;this.Score=function(){return a.SetsScore};this.SetScore=function(){return 0===a.Sets.length?0:a.Sets[a.Sets.length-1].Score()};this.GameScore=function(){return 0===a.Games.length?0:a.Games[a.Games.length-1].Score()}}function g(){var a=this;this.Games=[];this.TiebreakGame=l;this.Score=function(){return a.Games.length}}function q(){var a=this;this.Points=[];this.Score=function(){return a.Points.length}}
function n(a,b,g){var l=this;this.PlayerOne={Player:a,Score:new d};this.PlayerTwo={Player:b,Score:new d};this.ServingPlayer=g;this.forPlayer=function(a){return l.PlayerOne.Player===a?l.PlayerOne:l.PlayerTwo}}var A=this;this.DetailedScoreProjector=function(b){a.notEmpty(b,"gameDefinition");var d=new n(b.players[0],b.players[1],b.startingPlayer),l=new A.ScoreProjector(b,new A.ScoreProjectorHooks(function(a){d.ServingPlayer=a.ServingPlayer;var b=d.forPlayer(a.WinningPlayer).Score;b.Points.push(a.DecidingPoint);
0===b.Games.length&&b.Games.push(new q);b.Games[b.Games.length-1].Points.push(a.DecidingPoint)},function(a){var b=d.forPlayer(a.WinningPlayer).Score,f=d.forPlayer(a.LosingPlayer).Score;0===b.Sets.length&&b.Sets.push(new g);b.Sets[b.Sets.length-1].Games.push(b.Games[b.Games.length-1]);a.IsTiebreak&&(b.Sets[b.Sets.length-1].TiebreakGame=b.Games[b.Games.length-1],f.Sets[f.Sets.length-1].TiebreakGame=f.Games[f.Games.length-1]);b.Games.push(new q);f.Games.push(new q)},function(a){var b=d.forPlayer(a.WinningPlayer).Score;
b.SetsScore++;b.Sets.push(new g);d.forPlayer(a.LosingPlayer).Score.Sets.push(new g)},function(a){}));this.projectScore=function(a){d=new n(b.players[0],b.players[1],b.startingPlayer);l.processPoints(a);return d}}}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model);(function(a,b,l){function d(d){a.notEmpty(d,"players");a.condition(2===d.length,"The match must have exactly two players");this.pointFor=function(a,g,l){var v=a===d[0]?d[1]:d[0];return new b.Point(a,g.creditTo===b.PointCreditTypes.PointWinner?a:v,g,!0===l?!0:!1)}}var g=this;this.Engine=function(b){a.notEmpty(b,"gameDefinition");var l=[],A=new d(b.players),u=[],v=new g.ScoreProjector(b),u=[b.players[0],b.players[1]];this.scorePointFor=function(a,b,c){a=A.pointFor(a,b,c);l.push(a)};this.undoLatestPoint=
function(){0!==l.length&&l.pop()};this.players=u;this.points=l;this.tennisScore=function(){return v.toTennisScore(l)}};this.PointFactory=d}).call(this.H.TennisScoreKeeper,this.H.Check,this.H.TennisScoreKeeper.Model,this._);